### ISSUE TITLE
Example in https://github.com/xspec/xspec/wiki/Writing-Scenarios#function-scenarios uses true() as parameter value but accompanying text explains false() is being passed in

### ISSUE THREAD

**Issue by martin-honnen** [xspec/xspec#1053]
The section https://github.com/xspec/xspec/wiki/Writing-Scenarios#function-scenarios in the wiki says in the second and third paragraph:

> For example:
> 
> ```
> <x:scenario label="when capitalising a string">
>    <x:call function="eg:capital-case">
>       <x:param select="'an example string'"/>
>       <x:param select="true()"/>
>    </x:call>
>    ...
> </x:scenario>
> ```
> 
> will result in the call eg:capital-case('an example string', false())

So the code example has `<x:param select="true()"/>` with `true()` but somehow the accompanying text claims the resulting function call uses `false()`. That doesn't make sense, either the code sample or the text need to be changed.

**Comment by AirQuick** [comment]
Thanks for spotting this.
I fixed the accompanying text ([diff](https://github.com/xspec/xspec/wiki/Writing-Scenarios/_compare/136911cf2b9f0a18948e96e0db127a4a24108351...55cfb7b75903e45b4cea72da34439a42c2b9f276)). Does it look fine now?

**Comment by martin-honnen** [comment]
@AirQuick , yes, sure, looks fine.

**Comment by AirQuick** [comment]
Thanks @martin-honnen 
If you find another error in Wiki, please open an issue like this at any time and it will be much appreciated.

(If we migrate Wiki to the standalone site (just an idea, not decided yet &mdash; xspec/xspec.github.io#2), we will be able to use pull requests for handling documentation errors.)
