### ISSUE TITLE
Reporting errored out tests

### ISSUE THREAD

**Issue by willemvlh** [xspec/xspec#1147]
Currently, when a runtime error occurs when running a test suite, execution is halted and the test report is not generated. 
Would it be a good addition to, instead, still generate the report with mentioning which tests errored out and report the error? I would think that with XSLT 3's addition of `<xsl:try>`, this is fairly trivial to implement.
(Perhaps this already exists and I didn't find it.)

**Comment by AirQuick** [comment]
There is [`x:scenario/@catch`](https://github.com/xspec/xspec/wiki/Testing-Dynamic-Errors) available on XSpec v1.5.0 or later. It isn't designed to report which tests errored out. It's designed to test your expected errors. But probably it works for you.

**Comment by AirQuick** [comment]
Closing this, assuming `@catch` serves.
