### ISSUE TITLE
Add documentation on how to run the test suite locally

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#117]
Following the work done in #98 and the increased number of contributors, add documentation in the wiki on how to run the test suite locally. The aim is to allow contributors to run the test suite locally before submitting their pull requests thus speeding up the code review process.

The documentation should include the setup required for Windows and MacOS/Linux and the commands to run the tests. The current configuration for [Travis](https://github.com/xspec/xspec/blob/master/.travis.yml) and [AppVeyor](https://github.com/xspec/xspec/blob/master/appveyor.yml) is a good starting point for writing instructions.

**Comment by cirulls** [comment]
As I recently (re)set by Windows environment to run the test suite locally, I'd like to document here what I've done, hopefully it will be useful for other contributors. It would be good if someone on Windows could check that this is correct. @AirQuick: I am aware that #289 may change some of this but that's a start for some documentation on the wiki.

As I don't own a Windows machine, I dowloaded a Windows virtual machine from the [Microsoft website](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and ran it in [VirtualBox](https://www.virtualbox.org/). These Windows VM are available for testing and are valid for 90 days. I'm running a Windows 7 32-bit system but I think this setup should be valid on Windows 8 and Windows 10 virtual machine as well as on bare metal.

This is the list of dependencies that need to be downloaded (for the current version used in XSpec, check the relevant version number in [appveyor.yaml](https://github.com/xspec/xspec/blob/master/appveyor.yml)):

- [JAVA JDK 8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
- [SAXON HE](https://sourceforge.net/projects/saxon/files/Saxon-HE/)
- [Ant](https://ant.apache.org/bindownload.cgi)
- [XML Calabash](https://github.com/ndw/xmlcalabash1/releases)
- [XML Resolver](http://central.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar)
- [Jing](http://central.maven.org/maven2/com/thaiopensource/jing/20091111/jing-20091111.jar)
- [BaseX](http://files.basex.org/maven/org/basex/basex/) (optional on Windows, only required on Linux/MacOS) 

When available, it it recommended to download and extract the full zip files rather than just the .jar file as there are often additional dependencies. 

Once all the tools are installed in their own directories, the corresponding environment variables need to be set. To set up system environment variables in Windows, click on the Start menu, search for system environment variables and click on `Edit the system environment variables`. The System Properties window opens up, select the tab`Advanced`, and click on `Environment Variables`. Click on `New` and set up the environment variables as in the table below (I provide the values on my system as an example). Note that `Path` is likely to exist already on the system so select it, click on `Edit`, go to the end, add a `;` to add a new value, and set it. 


Variable name | Variable value |
--- | --- | 
JAVA_HOME | C:\Program Files\Java\jdk1.8.0_181 |
SAXON_CP | C:\saxon\saxon9he.jar |
ANT_HOME | C:\apache-ant-1.9.9 |
Path | %ANT_HOME%\bin; | 
XMLCALABASH_CP | C:\xmlcalabash\xmlcalabash-1.1.21-97.jar |
XML_RESOLVER_CP | C:\xml-commons-resolver-1.2\xml-resolver-1.2.jar |
JING_CP | C:\jing\jing.jar |
BASEX_CP | C:\basex\BaseX.jar |

You can check that the dependencies are installed correctly with the following commands from the Windows command line:

```console
# check values of all environment variables
set
# check Java JDK
java -version
# check Saxon
java -cp %SAXON_CP% net.sf.saxon.Version
# check ant
ant -version
# check XML Calabash
java -cp %XMLCALABASH_CP% com.xmlcalabash.drivers.Main --version
# check XML Resolver
java -cp %XML_RESOLVER_CP% org.apache.xml.resolver.Version
# check Jing
java -jar %JING_CP%
# check BaseX
java -jar %BASEX_CP%
```

You should now be able to run the XSpec test suites on your machine. Go to the xspec directory on the branch you want to test, navigate to the directory `test`, and run the test suites :

```console
xspec-bat.cmd
run-xspec-tests.cmd
cd end-to-end
run-e2e-test.cmd
```

**Comment by AirQuick** [comment]
Updated the [Linux/MacOS](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally#linuxmacos) section ([diff](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally/_compare/7fca78c4a383cff4e56d06a67df1163ddfdce12f...c0ea38dc24ac149570815768552af55de3bf92ba)). I guess this suffices for now.

**Comment by AirQuick** [comment]
@xspec/xspec 
I restructured the [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally). Now the page is not sectioned by OS but by the steps.
