### ISSUE TITLE
XSpec report breaks when the XSLT and XSpec are located in folder containing simple quote.

### ISSUE THREAD

**Issue by raducoravu** [xspec/xspec#119]
I have a folder called "Radu's samples" (contains a simple quote in its name).
I have an XSLT and and XSpec there, I run the XSpec report, I get:

     [java] Syntax error at char 40 near {...ojects/eXml/samples/xspec/a...} in expression in xsl:variable/@select on line 16 column 84 of personal.xsl:

The problem is that in "generate-xspec-tests.xsl" the value of the "stylesheet-uri" variable ends up having a simple quote in it and then it is used as a string literal in various places.

A possible fix would be to escape simple quotes in the URI with the encoded equivalent character like:

      <xsl:variable name="aposVal">'</xsl:variable>
      <xsl:variable name="stylesheet-uri" as="xs:anyURI" 
        select="resolve-uri(/x:description/@stylesheet, replace(base-uri(/x:description), $aposVal, '%27'))" />

**Comment by cirulls** [comment]
Thanks for raising this issue. Would it be possible to post an example of XSLT and XSpec code as well as your folder structure so that we can reproduce the issue? Thanks.

**Comment by raducoravu** [comment]
I attached a zip containing a folder called "some'path" with two small XSLT and XSpec documents but their content does not matter much

[some'path.zip](https://github.com/xspec/xspec/files/918655/some.path.zip)

You should receive the following error running the XSpec:

     [xslt] Processing C:\Users\radu_coravu\Desktop\some'path\test.xspec to C:\Users\radu_coravu\Desktop\some'path\xspec\test.xsl
     [xslt] Loading stylesheet D:\projects\eXml\frameworks\xspec\src\compiler\generate-xspec-tests.xsl
     [xslt] log4j:WARN No appenders could be found for logger (ro.sync.util.security.Sandbox).
     [xslt] log4j:WARN Please initialize the log4j system properly.
     [java] Syntax error at char 41 near {...radu_coravu/Desktop/some'pa...} in expression in xsl:variable/@select on line 16 column 84 of test.xsl:
     [java]   XPST0003: Unexpected token name "path" beyond end of expression
     [java] Errors were reported during stylesheet compilation
     [java] Java Result: 2

**Comment by cirulls** [comment]
I confirm I was able to reproduce the error, I file this as a bug. I submitted #120 using the fix you suggested.

**Comment by raducoravu** [comment]
👍
