### ISSUE TITLE
Minor fix on Getting Started wiki page

### ISSUE THREAD

**Issue by rolfkleef** [xspec/xspec#125]
Apparently it's not possible to do pull requests on GitHub wiki pages, so a "nano fix" here: the list of generated test report files just above https://github.com/xspec/xspec/wiki/Getting-Started#dive-into-the-xspec-tests says `escape-for-regex.html` rather than `escape-for-regex-result.html`

**Comment by AirQuick** [comment]
Thanks for spotting it. Fixed now.
AFAIK, wiki has no other instances of the same error.

**Comment by cirulls** [comment]
Thanks @rolfkleef for spotting it and @AirQuick for fixing it, I'll close the ticket.
