### ISSUE TITLE
XSLT 3.0 support

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#127]
Xslt 3.0 support should be largely enhanced.

It is impossible to write xspec on xslt that have a ```<xsl:use-package/>```, as ```<xsl:use-package/>``` can not be used in imported XSL, and as xspec implementation generates a XSLT that imports the XSLT we want to test.

I create this issue, but it **must** be completed with all XSLT 3.0 features that are not supported.

**Comment by cirulls** [comment]
Hi Christophe,

could you post an example of XSLT 3.0 with ```<xsl:use-package/>``` and an example of an XSpec test (even if it is not running correctly) so that we can simulate the issue?

Thanks,

Sandro

**Comment by jcronk** [comment]
@cirulls - I'll give you a minimal example:

Package: using the example package [here](https://www.w3.org/TR/xslt-30/#packages)
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:package
    name="http://example.org/complex-arithmetic.xsl"
    package-version="1.0"
    version="3.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:f="http://example.org/complex-arithmetic.xsl">
    
    <xsl:function name="f:complex-number" 
        as="map(xs:integer, xs:double)" visibility="public">
        <xsl:param name="real" as="xs:double"/>
        <xsl:param name="imaginary" as="xs:double"/>
        <xsl:sequence select="map{ 0:$real, 1:$imaginary }"/>
    </xsl:function>
    
    <xsl:function name="f:real" 
        as="xs:double" visibility="public">
        <xsl:param name="complex" as="map(xs:integer, xs:double)"/>
        <xsl:sequence select="$complex(0)"/>
    </xsl:function>
    
    <xsl:function name="f:imag" 
        as="xs:double" visibility="public">
        <xsl:param name="complex" as="map(xs:integer, xs:double)"/>
        <xsl:sequence select="$complex(1)"/>
    </xsl:function>
    
    <xsl:function name="f:add" 
        as="map(xs:integer, xs:double)" visibility="public">
        <xsl:param name="x" as="map(xs:integer, xs:double)"/>
        <xsl:param name="y" as="map(xs:integer, xs:double)"/>
        <xsl:sequence select="
            f:complex-number(
            f:real($x) + f:real($y), 
            f:imag($x) + f:imag($y))"/>
    </xsl:function>
    
    <xsl:function name="f:multiply" 
        as="map(xs:integer, xs:double)" visibility="public">
        <xsl:param name="x" as="map(xs:integer, xs:double)"/>
        <xsl:param name="y" as="map(xs:integer, xs:double)"/>
        <xsl:sequence select="
            f:complex-number(
            f:real($x)*f:real($y) - f:imag($x)*f:imag($y),
            f:real($x)*f:imag($y) + f:imag($x)*f:real($y))"/>
    </xsl:function>    
</xsl:package>
```

Stylesheet with use-package:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:f="http://example.org/complex-arithmetic.xsl"
    exclude-result-prefixes="xs"
    version="3.0">
    <xsl:use-package name="http://example.org/complex-arithmetic.xsl" version="3.0"/>
    <xsl:template name="xsl:initial-template">
        <xsl:variable name="val1" select="f:complex-number(2,5)"/>
        <xsl:variable name="val2" select="f:complex-number(3,2)"/>
        <xsl:variable name="sum" select="f:add($val1, $val2)"/>
        <xsl:sequence expand-text="yes">The sum of the two numbers is {f:real($sum)} + {f:imag($sum)}i</xsl:sequence>
    </xsl:template>
</xsl:stylesheet>
```
XSpec test: 
```
<?xml version="1.0" encoding="UTF-8"?>
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    stylesheet="use-package-example.xsl">
    <x:scenario label="Scenario for testing function initial-template">
        <x:call template="xsl:initial-template"/>
        <x:expect label="it returns the expected message" select="'The sum of the two numbers is 5 + 7i'"/>
    </x:scenario>
</x:description>
```
Here's the saxon config telling it how to find the package:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns="http://saxon.sf.net/ns/configuration">
    <xsltPackages>
        <package name="http://example.org/complex-arithmetic.xsl" version="3.0" sourceLocation="package-example.xsl" />       
    </xsltPackages>  
</configuration>
```

In Oxygen XML, everything shows up without errors, and the test stylesheet will run and produce output, but if you try to run the XSpec test, you will get:
```
run-xslt-test:
     [echo] Running XSLT Tests...
     [java] Error on line 9 column 115 of package-test-compiled.xsl:
     [java]   XTSE3008: xsl:use-package cannot appear in an imported stylesheet
     [java] xsl:use-package cannot appear in an imported stylesheet
```

Hope this helps!

**Comment by cirulls** [comment]
@jcronk: thanks for providing an example and for raising #762 with more details. We labelled #762 as a feature request. We can't promise when/if this will be implemented but if you have ideas and would like to contribute some code or even just reviewing the feature when it's ready it would be great. Thanks!

**Comment by michaelhkay** [comment]
Just to mention another issue that may turn out to be related: static parameters. A particular challenge here is that static coupling of the test driver to the stylesheet under test (whether using xsl:import or xsl:use-package) doesn't allow testing of different values of static parameters in a single run. Dynamic invocation using fn:transform() could solve this problem, as well as the xsl:use-package problem.

**Comment by AirQuick** [comment]
@michaelhkay 
Thanks for the advice. Looks like whatever we do with `xsl:import` or `xsl:include` or `xsl:use-package` in order to keep something working, something else doesn't work.
It's worth trying dynamic invocation. I'm working on it.

**Comment by djbpitt** [comment]
In the hope of helping to restart this issue, which seems to have fallen dormant for a bit: Currently (v. 1.6) XSpec reports that a file with a root `<xsl:package>` element is not an XSLT stylesheet, which is to say that XSpec apparently doesn’t support either packages or stylesheets (whether packages or not) that use packages with `<xsl:use-package>`. The minimal example from @jcronk last January tested an `<xsl:stylesheet>` with an `<xsl:use-package>`, but testing the `<xsl:package>` itself, even when that file does not use other packages, seems to be a different, if related, matter.

I regret that I am not enough of a developer to be able to rewrite XSpec itself, but in the interest of doing what I can, I'd be happy to help test if someone is working on any part of this.

**Comment by AirQuick** [comment]
> testing the `<xsl:package>` itself

#892 is in `master` now. Specifying the explicit packages (`xsl:package`) in `/x:description/@stylesheet` should be possible. (tested in [`test/external_xslt-package_arith.xspec`](https://github.com/xspec/xspec/blob/master/test/external_xslt-package_arith.xspec) and [`external_xslt-package_filter.xspec`](https://github.com/xspec/xspec/blob/master/test/external_xslt-package_filter.xspec))

I'm closing this issue for now. Please feel free to open another issue separately.
