### ISSUE TITLE
XPath issues in x:expect-assert/@location

### ISSUE THREAD

**Issue by yamahito** [xspec/xspec#1277]
Possibly one for @vincentml ?

So it seems that XPath statements like the following:
```
article/front/article-meta/abstract[1]/sec[1]
```
work fine in `x:expect-assert/@location`, but ones that use value comparisons, such as
```
article/front/article-meta/abstract[1]/sec[@id='sec-title-text-lower-case']
```
do not!

May I suggest one or more of the following fixes?

1. Clarify this restriction in the wiki (short-term)
2. Change the comparison of XPath statements to use 'is' function to confirm that the xspec location and the svrl location refer to the same node (long term)

**Comment by AirQuick** [comment]
Can you try out the latest `master` branch? It includes #1107 which uses `is`.

**Comment by yamahito** [comment]
Excellent work!  I will double check that this works using the master branch when I get an opportunity, but I don't think we need to keep the ticket open if you've already fixed the issue - I trust your work ;)

When will we see you at an XML conference, @AirQuick ?  I think quite a few of us owe you some beers/chocolate/appreciation :)
