### ISSUE TITLE
Remove Travis CI

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#1291]
Travis CI has changed its pricing model: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
I pushed a commit to my XSpec fork and it consumed 1420 credits.

We could request their support to claim some "free OSS credits" ([requirements](https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567/15?u=airquick)). But now we have GitHub Actions workflow which does everything our Travis configuration does. I think we can simply remove Travis from our CI systems:

- [x] Move [`.travis.yml`](https://github.com/xspec/xspec/blob/master/.travis.yml) to [`misc/archive/`](https://github.com/xspec/xspec/tree/master/misc/archive).
- [x] Remove Travis badge from [README](https://github.com/xspec/xspec/blob/master/README.md).
- [x] Remove "Travis CI" from [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally).
- [x] Remove "Travis CI - Pull Request" from the required checks in [the branch protection rule](https://github.com/xspec/xspec/settings/branches).
- [x] Uninstall "Travis CI" or remove its `xspec/xspec` repository access from GitHub Apps [settings](https://github.com/xspec/xspec/settings/installations)

**Comment by cirulls** [comment]
I agree, let's fully move to GitHub Actions.

**Comment by AirQuick** [comment]
Done all the TODOs.

> * [x]  Uninstall "Travis CI" or remove its `xspec/xspec` repository access from GitHub Apps [settings](https://github.com/xspec/xspec/settings/installations)

As for this item, I uninstalled "Travis CI" there. Removing only `xspec/xspec` repository access was not possible, because it was the only repo who granted permission.
