### ISSUE TITLE
sch:include and sch:extends doesn't work

### ISSUE THREAD

**Issue by thendarion** [xspec/xspec#1336]
if I have an sch:include or an sch:extends in my schematron file, xspec seems to fail to compile the tests

**Comment by AirQuick** [comment]
Can you possibly narrow down the conditions of the failure?

We have these tests working fine:
- https://github.com/xspec/xspec/blob/master/test/schematron-020.xspec tests https://github.com/xspec/xspec/blob/master/test/schematron/schematron-020.sch with `sch:include` + `@id`
- https://github.com/xspec/xspec/blob/master/test/schematron-022.xspec tests https://github.com/xspec/xspec/blob/master/test/schematron/schematron-022.sch with `sch:extends`
- https://github.com/xspec/xspec/blob/master/test/schematron/schematron-xslt.xspec tests https://github.com/xspec/xspec/blob/master/test/schematron/schematron-xslt.sch with `sch:include` (no `@id`)

So I presume something specific to your use case makes it fail.

**Comment by thendarion** [comment]
I create two sch files and two xspec files for them
that works fine
then I create an sch file that imports the two sch files and create and xspec file that imports the two xspec files, so that I can run them at once
that breaks

tested in the following environments:
XSpec plugin 2.1.1 in oXygen Editor
xspec-1.6.0 in xspec-maven-plugin-2.0.0


error from oXygen:
```
compile:
     [echo] Compiling Tests...
     [xslt] Processing main.xspec to main-compiled.xsl
     [xslt] Loading stylesheet compile-xslt-tests.xsl
     [xslt]  

run-xquery-test:

run-xslt-test:
     [echo] Running XSLT Tests...
     [java] Static error at sch:schema on line 3 column 70 of main.sch:
     [java]   XTSE0150: The supplied file does not appear to be a stylesheet
     [java] Errors were reported during stylesheet compilation

```
error from Maven:
```
Processing XSpec: main.xspec
[INFO] Compiling main.xspec.xslt

[INFO] XSpec has been compiled
Static error at sch:schema on line 3 column 70 of main.sch:
  XTSE0150: The supplied file does not appear to be a stylesheet
[ERROR] while processing main.xspec
net.sf.saxon.s9api.SaxonApiException: Errors were reported during stylesheet compilation
    at net.sf.saxon.s9api.XsltCompiler.compile (XsltCompiler.java:793)
    at io.xspec.maven.xspecMavenPlugin.utils.XmlStuff.compileXsl (XmlStuff.java:367)
    at io.xspec.maven.xspecMavenPlugin.XSpecRunner.processXsltXSpec (XSpecRunner.java:399)
    at io.xspec.maven.xspecMavenPlugin.XSpecRunner.processXSpec (XSpecRunner.java:238)
    at io.xspec.maven.xspecMavenPlugin.XSpecRunner.execute (XSpecRunner.java:199)
...
```
