### ISSUE TITLE
Suggestion: Compile schematron using SchXslt

### ISSUE THREAD

**Issue by markdunnoup** [xspec/xspec#1366]
The code for compiling Schematron files to XSLT is (a version of) the code archived at https://github.com/Schematron/schematron 

The README.md file in that repository currently says

"new applications of Schematron were advised to use the SchXslt Schematron implementation at https://github.com/schxslt/schxslt."

**Comment by AirQuick** [comment]
Right now XSpec does not come bundled with SchXslt.

However, with XSpec v2.0.4 or later, you can use SchXslt by setting
- [`SCHEMATRON_XSLT_*` environment variables](https://github.com/xspec/xspec/wiki/Environment-Variables) (in case of `xspec.bat` and `xspec.sh`)
- [`xspec.schematron.preprocessor.step?` properties](https://github.com/xspec/xspec/wiki/Running-with-Ant#ant-properties) (in case of Ant).

You can find some command line examples at ["Using another implementation of Schematron" section](https://github.com/xspec/xspec/wiki/Testing-Schematron-with-Text-Nodes#using-another-implementation-of-schematron) of a Wiki page.

**Comment by markdunnoup** [comment]
Perfect, thanks!

**Comment by AirQuick** [comment]
Now we have [`schxslt` branch](https://github.com/xspec/xspec/tree/schxslt) where SchXslt is available out of the box and fully tested with our [test suite](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally).
