### ISSUE TITLE
Suggestion: allow SchXslt compilation parameters

### ISSUE THREAD

**Issue by markdunnoup** [xspec/xspec#1369]
SchXslt introduced a parameter $schxslt.base-uri-fixup to control whether `@xml:base` is added to parameters etc. Its default value is true() but it would be good to have the option of setting it to false()

Currently it is possible to override the default compilation to use the SchXslt stylesheets, but not to override the parameters of those stylesheets.

**Comment by AirQuick** [comment]
(edited slightly in order to remove an unintended mention)

**Comment by AirQuick** [comment]
If `$schxslt.base-uri-fixup` were only for the step 3, it could be controlled by `/x:description/x:param` as mentioned in ["Writing Tests" section](https://github.com/xspec/xspec/wiki/Writing-Scenarios-for-Schematron#writing-tests) of Wiki. Unfortunately, `$schxslt.base-uri-fixup` seems to be used in the step 1 and 2.

Maybe we may want to introduce a way to skip the step 1 and 2. Then probably we can use `pipeline-for-svrl.xsl` as the (sole) step 3 and `<x:param name="schxslt.base-uri-fixup" select="false()" />` in `x:description` will work. (I haven't tested it.)

**Comment by markdunnoup** [comment]
Just to complicate this, if XSpec compiles Schematron using SchXslt with `$schxslt.base-uri-fixup` set to `false()`, the location of *-compiled.xsl means that tests will fail if they rely on locations relative to the *.sch file.

This is because SchXslt with this configuration omits `@xml:base` from the root element of *-sch-preprocessed.xsl

**Comment by AirQuick** [comment]
> This is because SchXslt with this configuration omits `@xml:base` from the root element of *-sch-preprocessed.xsl

If that's not a bug but by design, we probably have to enable the [patch](https://github.com/xspec/xspec/blob/f568c9d32509e39fa6e0610eb1ecf045095db36b/src/schematron/patch-step3.xsl#L39-L51) either whenever `/element()/@xml:base` is missing or when `$schxslt.base-uri-fixup` is false. Right now the patch is injected only for the *skeleton* implementation bundled with XSpec.

**Comment by markdunnoup** [comment]
I've raised the question in SchXslt - https://github.com/schxslt/schxslt/issues/181

**Comment by AirQuick** [comment]
> Maybe we may want to introduce a way to skip the step 1 and 2. Then probably we can use `pipeline-for-svrl.xsl` as the (sole) step 3 and `<x:param name="schxslt.base-uri-fixup" select="false()" />` in `x:description` will work. (I haven't tested it.)

Opened #1371 for this.

With #1371 and the following configuration, I confirmed `<x:param name="schxslt.base-uri-fixup" select="false()" />` as a direct child of `/x:description` took effect:
- `SCHEMATRON_XSLT_INCLUDE=#none`
- `SCHEMATRON_XSLT_EXPAND=#none`
- `SCHEMATRON_XSLT_COMPILE=https://github.com/schxslt/schxslt/raw/964ed9c/core/src/main/resources/xslt/2.0/pipeline-for-svrl.xsl`

**Comment by AirQuick** [comment]
> This is because SchXslt with this configuration omits `@xml:base` from the root element of *-sch-preprocessed.xsl

#1388 ensures `@xml:base` on that element.
