### ISSUE TITLE
XSpec confused by <xsl:variable> populated by XPath from document root

### ISSUE THREAD

**Issue by markdunnoup** [xspec/xspec#137]
Here is my stylesheet written to illustrate the problem. Note the xsl:variable

```xml
<xsl:stylesheet version="2.0" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
    exclude-result-prefixes="#all" 
    >
    
    <xsl:variable name="root-name" as="xs:string" select="name(/*)"/>
    
    <xsl:template match="input">       
        <xsl:element name="output">
            <xsl:attribute name="old-root-name" select="$root-name"/>
        </xsl:element>
    </xsl:template>        
</xsl:stylesheet>
````

Here is my XSpec file:
```xml
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec" stylesheet="demo-01.xsl"> 
        
    <x:scenario label="External file">
        <x:context href="demo-01.xml"/>
        <x:expect label="Specific output for given context">
            <output old-root-name="input"/>
        </x:expect>
    </x:scenario>

</x:description>
````

Here is the external demo-01.xml file:
```xml
<input>
    <chemical_element id="hydrogen"/>
    <chemical_element id="helium"/>
    <chemical_element id="barium"/>
    <chemical_element id="sodium"/>
</input>
````

This should pass the XSpec test, but it fails because the output is:
```xml
<output old-root-name="x:description" />
````

I can't believe I haven't seen this before. Either there is a bug or I've forgotten how to run XSpec!

This was discovered during testing of XSpec for Schematron. Our Schematron QA rules declare a number of variables based on XPath statements.

But it's a problem in XSPec 0.5 as well.

**Comment by vincentml** [comment]
I am glad to hear that you are testing XSpec for Schematron!

When XSpec processes a test scenario the context XML is put inside a wrapper. This wrapper causes a difficulty when using XSpec to test stylesheets that contain XPaths that start with the document root (/). Would it be possible to try modifying your XPaths so that they do not begin with / ?

**Comment by markdunnoup** [comment]
Thanks Vincent. It may be possible to modify the XPaths, but this is not ideal.

For example, in a Schematron rule set we may have several rules that refer to the root DOI, so we set a variable 

```xml
<iso:let name="rootDOI" value="/*/@doi"/>
````

It may be possible to get the DOI for each rule individually, but that would create its own problems.

Ideally we want some way of localizing these global variables for each context fragment. But I can see that being very tricky to implement, and possibly leading to unwanted side effects.

So maybe this is a fundamental limitation of the XSpec approach, and our Schematron rule sets are bumping against this limitation.

I will continue to test XSpec for Schematron - it's a great achievement and will be useful enough despite this limitation. 

What I want is to be able to use <expect-valid>. Next step is to see if I can override the variable in the XSpec file so that <expect-valid> works.

**Comment by markdunnoup** [comment]
Update: If I override the global variable with an x:param I can get x:expect-valid to work. This is an acceptable workaround.

**Comment by cirulls** [comment]
@markdunnoup: thanks for posting your workaround. Are you happy with it? Can I close this issue?

**Comment by markdunnoup** [comment]
Yes, I'm happy for this to be closed.
