### ISSUE TITLE
Global x:param does not override global XSLT variable in external transformation

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1375]
An element `x:description[@run-as="external"]/x:param` does not seem to override `xsl:stylesheet/xsl:variable`. Is that a bug, or a limitation that should be documented? A similar `x:param` element *does* override if `run-as="import"` or if the global in the SUT is `xsl:param` instead of `xsl:variable`.

The explanation in [External Transformations](https://github.com/xspec/xspec/wiki/External-Transformation#xspec-global-parameters-xdescriptionxparam) mentions a corresponding `xsl:param` but doesn't say anything about corresponding `xsl:variable`. The more general discussion in [Writing Scenarios](https://github.com/xspec/xspec/wiki/Writing-Scenarios#global-parameters) does mention global XSLT variables.

**Sample XSpec:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description run-as="external"
    xmlns:x="http://www.jenitennison.com/xslt/xspec"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    stylesheet="override-global-var.xsl">
    <x:param name="global-var-in-sut" select="'override-var'" as="xs:string"/>
    <x:param name="global-param-in-sut" select="'override-param'" as="xs:string"/>
    <x:scenario label="Value of globals as seen from SUT">
        <x:call template="mirror-global-var"/>
        <x:expect label="Reflects override via /x:description/x:param"
            select="('override-var','override-param')"/>
    </x:scenario>
</x:description>
```

**Corresponding XSLT:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    version="3.0">
    <xsl:variable name="global-var-in-sut" select="'original-var'" as="xs:string"/>
    <xsl:param name="global-param-in-sut" select="'original-param'" as="xs:string"/>
    <xsl:template name="mirror-global-var" as="xs:string+">
        <xsl:sequence select="($global-var-in-sut,$global-param-in-sut)"/>
    </xsl:template>
</xsl:stylesheet>
```

**Comment by AirQuick** [comment]
Although I don't know the formal W3C specification, Saxon command line works in the same way:

```console
C:\test>java -jar "%SAXON_JAR%" -it:mirror-global-var -xsl:override-global-var.xsl global-var-in-sut=override-var global-param-in-sut=override-param
<?xml version="1.0" encoding="UTF-8"?>original-var override-param
```

So I presume `x:param` is working as intended. It's backed by tests:

- For [@run-as=import](https://github.com/xspec/xspec/blob/master/test/end-to-end/cases/global-override.xspec) ([result](https://refined-github-html-preview.kidonng.workers.dev/xspec/xspec/raw/master/test/end-to-end/cases/expected/stylesheet/global-override-result.html))
- For [@run-as=external](https://github.com/xspec/xspec/blob/master/test/end-to-end/cases/external_global-override.xspec) ([result](https://refined-github-html-preview.kidonng.workers.dev/xspec/xspec/raw/master/test/end-to-end/cases/expected/stylesheet/external_global-override-result.html))

**Comment by galtm** [comment]
I didn't expect to be able to override a global XSLT variable by running Saxon at the command line, but I did expect to be able to override it from XSpec. I must have forgotten the part of the test that says, "x:param should override xsl:variable unless run-as=external". Thanks for pointing that out.

Would you like me to own this issue and use it for updating the wiki about External Transformations?

(It's a shame not to have this support, though. I would like to use your scenario-level global-param feature #1354 that I'm in the midst of code reviewing now, but some of the XSLT globals that I need to override are global variables rather than global parameters.)

**Comment by AirQuick** [comment]
> Would you like me to own this issue and use it for updating the wiki about External Transformations?

Yes! Also please feel free to edit the other parts of the page. That Wiki page in its current form is at best just a dumped list of things I had noticed in `@run-as=external` development.

> (It's a shame not to have this support, though. I would like to use your scenario-level global-param feature #1354 that I'm in the midst of code reviewing now, but some of the XSLT globals that I need to override are global variables rather than global parameters.)

That would be nice to have. Seems impossible, unfortunately...

**Comment by galtm** [comment]
I added the basic information ([diff](https://github.com/xspec/xspec/wiki/External-Transformation/_compare/8dce8917e16020b6279e1d90414c24b494846d2a)) but I'll also look at this page as a whole before marking this issue complete.

**Comment by galtm** [comment]
I made some stylistic changes in the page ([diff](https://github.com/xspec/xspec/wiki/External-Transformation/_compare/40ab4ebfad2c32a7430c4aa814fab38d220df059)). @AirQuick , is there more I should do for this issue?

**Comment by AirQuick** [comment]
Thanks @galtm. They all look good!
