### ISSUE TITLE
Generating coverage report fails in output-lines with message: ERROR: unmatched string: &lt;

### ISSUE THREAD

**Issue by jhellingman** [xspec/xspec#1411]
When running xspec -c on my tests, I commonly get ERROR: unmatched string: &lt; when producing the coverage reports. When setting terminate to "no" on the xsl:message, the report appears to be generated, but I am not sure it is still correct.

A small xspec test I am having this issue with is here: https://github.com/jhellingman/tei2html/blob/master/xspec/betacode.xspec. Most of the other test I prepared have the same issue.

**Comment by AirQuick** [comment]
Looks like [`src/reporter/coverage-report.xsl`](https://github.com/xspec/xspec/blob/db8f7cab593efce15bb5029fef7991285b94bef9/src/reporter/coverage-report.xsl#L152-L182) cannot parse [`DOCTYPE` line](https://github.com/jhellingman/tei2html/blob/11d80ce47d710b32e5a9bc2c05609feec9e44709/betacode.xsl#L1).
