### ISSUE TITLE
x:import and x:description/attribute()

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#1421]
https://github.com/xspec/xspec/pull/1397#pullrequestreview-622778963
> If I have `timing` in an XSpec file, and that file imports another XSpec file with the opposite `timing` value, then only the parent file's attribute takes effect. I think this behavior is fine, but I don't know what users' expectations would be. Is it worth documenting, or too obscure?

**Comment by galtm** [comment]
Related to #1497 is a similar behavior: If you set `@threads` on `x:description` and then use `x:import` to run a suite of tests, the `@threads` values in the imported files have no effect. That might surprise some users and make them wish they had organized their code differently from the start.

**Comment by galtm** [comment]
Will plan to add information to this page, where `x:import` is documented: https://github.com/xspec/xspec/wiki/Focusing-Your-Efforts

**Comment by galtm** [comment]
I updated the page [Focusing Your Efforts](https://github.com/xspec/xspec/wiki/Focusing-Your-Efforts).

Here is an earlier draft that I *didn't* use, but I'm including it here in case a reviewer likes this approach better.

* The following attributes of `x:description` take effect across all imported XSpec description documents. Make sure the *main* XSpec description document has your desired value.
  - `measure-time`
  - `result-file-threshold`
  - `run-as`
  - `threads`
* The following attributes of `x:description`, take effect in each *individual* XSpec description document. Make sure each individual XSpec description document has your desired value.
  - `expand-text`
  - `preserve-space`

**Comment by galtm** [comment]
Closing based on [change in "Focusing Your Efforts"](https://github.com/xspec/xspec/wiki/Focusing-Your-Efforts/_compare/36a85ab4f6feec2799ee050393d9d0ad85e30fa6...713fdde36c316496fe8928d2480c3551374d5930).
