### ISSUE TITLE
Jeni's name

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#143]
Some files say, `Jeni Tennison`.
Some `Jeni Tennsion`.

We might want to bulk fix it at some point.

**Comment by cirulls** [comment]
The correct version is `Jeni Tennison`. I've seen this misspelling for so long that I suspect this may have been introduced by Jeni herself by mistake! I agree this should be fixed.

**Comment by cirulls** [comment]
Fixed in #401
