### ISSUE TITLE
prefixed elements are not correctly processed in 0.5

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#150]
[demo-library.zip](https://github.com/xspec/xspec/files/1499583/demo-library.zip)
Hello,

attached a sample project with 1 XSL and 1 XSpec. It's a maven project, your can reproduce the problem with `mvn test`, or you can execute in oXygen 19.0, the problem occurs too.

For each element, my XSL calculates a new element name, where prefix is unchanged, and element local-name is upper-cased. When applying the XSL on itself, it works correctly.
The xspec fails when constructing the new element.

Best regards,
Christophe

**Comment by AirQuick** [comment]
I think Michael wrote [something about it](http://www.google.com/search?q=%22interpreted+in+the+light+of+namespace+declarations+appearing+in+the+stylesheet%2C+not+namespace+declarations+in+the+original+source+document%22&oq=%22interpreted+in+the+light+of+namespace+declarations+appearing+in+the+stylesheet%2C+not+namespace+declarations+in+the+original+source+document%22
).
So, in `demo-library/src/main/xsl/demo/uppercase-elements.xsl`, changing
```xml
    <xsl:element name="{$elementName}">
```
to
```xml
    <xsl:element name="{upper-case(local-name())}" namespace="{namespace-uri()}">
```
made the test return Success on my end.

**Comment by cmarchand** [comment]
Ok, I've frogotten this. Thanks a lot, @AirQuick  !
