### ISSUE TITLE
Question about use of serialize(., map {}) in https://github.com/xspec/xspec/blob/master/src/reporter/format-utils.xsl#L260

### ISSUE THREAD

**Issue by martin-honnen** [xspec/xspec#1538]
I am currently exploring whether I can use Saxon-JS 2.3 and its `xslt3` command line tool instead of Saxon Java to run XSLT specific XSpec tests.

On my way to doing this I found some oddity in the way Java based Saxon and Node.js based Saxon-JS handle the use of `serialize(., map {})` in https://github.com/xspec/xspec/blob/master/src/reporter/format-utils.xsl#L260, while Saxon Java doesn't output any XML declaration with `serialize($someTextNode, map{})` but seems to treat it as `serialize($someTextNode)` which the spec defines as `serialize($someTextNode, ())` Saxon-JS outputs an XML declaration for the code used in the XSpec code (i.e. `serialize(., map {})`) while not doing this for a simple `serialize(.)` or `serialize(., ())`.

Before "patching" my local copy of https://github.com/xspec/xspec/blob/master/src/reporter/format-utils.xsl#L260 to use `serialize(.)` instead of `serialize(., map{})`, I was wondering whether anyone here knows why the empty `map{}` is passed as the second argument to the `serialize` function.

I will also look into filing a bug on Saxon-JS as the spec https://www.w3.org/TR/xpath-functions/#func-serialize seems to suggest the default values for an empty map are to `omit-xml-declaration`.

**Comment by AirQuick** [comment]
`map{}` is to make sure that all the parameters take their default values.
If I understand https://www.w3.org/TR/xpath-functions-31/#func-serialize correctly, `serialize(.)` or `serialize(., ())` leaves the parameters implementation-defined. In fact, `serialize(.)` on Saxon 9.6.0.10 was turning off `omit-xml-declaration` (#40).

**Comment by martin-honnen** [comment]
Thanks for the (air) quick response. As Saxon-JS currently doesn't use the default for the empty map, I will temporarily go with `serialize(., map { 'omit-xml-declaration' : true() })`. Saxonica seems to be busy this week with some other project but Norm has promised to look at the issues I have raised so far later on. So hopefully some future maintenance release of Saxon-JS 2 doesn't need me "patching" up XSpec files to get them to run with `xslt3` or in this case to get some normal output without lots of pesky XML declarations showing up in all places where you don't want them.

**Comment by AirQuick** [comment]
I also gave Saxon-JS 2.3 a try and encountered these problems, all or some of which you're aware of:
- `FORG0006 at xpath.xsl#786` and wrong `resolve-uri()` (https://saxonica.plan.io/boards/5/topics/8286)
- Whitespace-only text nodes are lost in some cases (https://saxonica.plan.io/issues/5001)
- `inherit-namespaces="no"` doesn't set `xmlns=""` (https://saxonica.plan.io/issues/5082)
