### ISSUE TITLE
Run only one test

### ISSUE THREAD

**Issue by kalaspuffar** [xspec/xspec#155]
Hi.

Don't know if this is a feature that is available or not but I saw that many have talked about this feature in rspec and it's used in many other testing frameworks.

Run only one test is a feature during development when you want to scope your runs to ensure that you don't get extra information not important to solve the current problem.

Could be implemented by for example an attribute on a scenario.

Sorry to take up your time if I just missed it in the documentation. Keep up the great work.

Best regards
Daniel

**Comment by AirQuick** [comment]
`focus` in the [**Focusing Your Efforts**](https://github.com/xspec/xspec/wiki/Writing-Scenarios#focusing-your-efforts) section might help.

**Comment by cirulls** [comment]
@AirQuick is right, find below the part of the documentation explaining the `focus` attribute, it also contains an example. @kalaspuffar, does this address your request?


Third, you can mark any scenario as having the current "focus" by adding a `focus` attribute to a `<x:scenario>` element. Effectively, this marks every *other* scenario as "pending", with the label given as the value of the `focus` attribute. For example:

```xml
<x:scenario focus="getting capitalisation working" label="when capitalising a string">
   <x:call function="eg:capital-case">
      <x:param select="'an example string'"/>
      <x:param select="true()"/>
   </x:call>
   <x:expect label="it should capitalise every word in the string" select="'An Example String'"/>
</x:scenario>
```

Using focus is a good way of working through one particular scenario, but once your code is working with that scenario, you should always test all the others again, just in case you've broken something else.

**Comment by kalaspuffar** [comment]
Hi again.

Thank you all for a quick and easy resolve of an issue. I was so used to using keywords like only one and the like that I didn't find the documentation about focus.

This helped me a lot while debugging my examples so thanks.

Best regards
Daniel
