### ISSUE TITLE
Fails to test imported Schematron XSpec with href

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#161]
Put these 2 files in `[XSpec installation]/test/schematron/`.

**xslt-import.xspec**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description stylesheet="../xspec-30.xsl" xmlns:x="http://www.jenitennison.com/xslt/xspec">
	<x:import href="../xspec-30.xspec" />
</x:description>
```

**schematron-import.xspec**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../../src/schemas/xspec.rnc" type="application/relax-ng-compact-syntax"?>
<x:description schematron="../../tutorial/schematron/demo-01.sch"
	xmlns:x="http://www.jenitennison.com/xslt/xspec">
	<x:import href="../../tutorial/schematron/demo-01.xspec" />
</x:description>
```

And test each of them. XSLT has no problem, but Schematron terminates:

```
V:\xspec>bin\xspec.bat test\schematron\xslt-import.xspec
...
passed: 1 / pending: 0 / failed: 0 / total: 1
Report available at V:\xspec\test\schematron\xspec\xslt-import-result.html
Done.
```

```
V:\xspec>bin\xspec.bat -s test\schematron\schematron-import.xspec
...
Error at char 4 in xsl:variable/@select on line 57 column 87 of schematron-import.xsl:
  FODC0002: I/O error reported by XML parser processing
  file:/V:/xspec/test/schematron/demo-01.xml: V:\xspec\test\schematron\demo-01.xml (The
  system cannot find the file specified)
I/O error reported by XML parser processing file:/V:/xspec/test/schematron/demo-01.xml: V:\xspec\test\schematron\demo-01.xml (The system cannot find the file specified)

*** Error running the test suite
```

Probably `src/schematron/schut-to-xspec.xsl` should have had a template like this: https://github.com/xspec/xspec/blob/ffd5eda3cea37a0fbd40791fef17e1ec31506607/src/compiler/generate-common-tests.xsl#L88-L90

**Comment by vincentml** [comment]
Thanks, AirQuick! I've reproduced the issue, and adding a template as you suggested helps to resolve href's in imported XSpec tests. Take a look at branch test/161

However, this change causes some of the existing tests to fail so I'll need to update these tests before creating the pull request.

**Comment by AirQuick** [comment]
Thanks, @vincentml.

I added another test to the branch. (e503c6c1f6439d6e9b8fa91f5dc566a1878e8758)
The test fails, because Apache catalog resolver seems to have a bug. You can see it in an [AppVeyor log](https://ci.appveyor.com/project/xspec/xspec/build/1.0.402/job/spm8k1345pcorn4n#L316) of a diagnostic message which I added temporarily (e55c7e16b63e5a730a8195b44b8c9463d1e575dd):
> [DIAG] base-uri: file:C:/projects/xspec/tutorial/schematron/demo-01.xspec

Note that `/` is missing between `file:` and `C:/`. This bad URI affects [`resolve-uri()`](https://github.com/xspec/xspec/commit/5e79c7b6c518648d0ffca2dffee3c7b1ebbb048f#diff-bfd457e7888bd125b4ced7a86affbcfaR180) later.
A workaround like [this](https://github.com/xspec/xspec/commit/63cf95d7eade5678e5c994fae18ff69d3410ac5d#diff-c074fa5f04c5d8e5c250c0dce9507623R22) would be needed. I'm committing it.
