### ISSUE TITLE
Question on Schematron operation

### ISSUE THREAD

**Issue by rjelliffe** [xspec/xspec#165]
I have a particular use case, and I would like to check if Xspec supports it.

This is that I want to run a Schematron test on a document. And then I want to look at the SVRL output, but I don't want to check the assertions. I want to check whether other things were generated, in particular  diagnostic and property elements.  

I know that XSpec now provides special elements to check if assertions failed etc.  But can I use those at the same time as normal Xspec  tests on the data generated?

**Comment by vincentml** [comment]
Yes, you can write expectations using `<x:expect>` to test the SVRL output from Schematron. For example:

`<x:expect label="assert" test="exists(svrl:schematron-output/svrl:failed-assert)"/>`

You can mix `<x:expect>` with Schematron-specific expect-* elements in the same scenario.

Within XSpec, the Schematron-specific expect-* elements actually test the SVRL output from Schematron XSLTs using tests like the example above.

**Comment by rjelliffe** [comment]
Thanks!
