### ISSUE TITLE
[Question] Running xspec xslt with external jars

### ISSUE THREAD

**Issue by tigoli** [xspec/xspec#1659]
Hi. 

I have a problem to run Xspec with external classes.
How do I specify external .jar-files when running from windows shell?

The tests is working from oXygen

In the beginning of my xslt file looks like this: 

```
<?xml version="1.0" encoding="iso-8859-1"?>
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:mc="xalan://com.tigoli.myclass">
```

Reslut: 
```
Running Tests...
Testing with SAXON HE 9.9.1.8
FinancialAccount template
..Scenario 1 - all account types
Error evaluating (error("Cannot find a 2-argument function named Q{xalan://com.tigoli.myclass}isValid()")) in xsl:when/@test on line 1079 column 125 of transformation.xslt:
```

Any ideas how to solve this?

**Comment by vincentml** [comment]
Hi @tigoli 
The environment variable SAXON_CP is used to provide a location of the Saxon jar and XML Resolver jar. Additional jars can be included as well. For example:

Windows:

set SAXON_CP=C:\path\to\saxon9he.jar;C:\path\to\xml-resolver-1.2.jar;C:\path\to\other.jar

Linux/macOS:

export SAXON_CP=/path/to/saxon9he.jar:/path/to/xml-resolver-1.2.jar:/path/to/other.jar

Does this help?

**Comment by tigoli** [comment]
Hi again. 

I included the jars in environment variable SAXON_CP. 
I’m using same jar file in oxygen software and in test/production environment. 

Any more suggestions that might be wrong?

**Comment by AirQuick** [comment]
If you're invoking XSpec with `xspec.bat` or `xspec.sh`, then `SAXON_CP` should work.
If you're invoking XSpec using the standard **Run XSpec Test** transformation scenario on Oxygen, then you should duplicate the **Run XSpec Test** scenario and add your jar files to [**Libraries**](https://www.oxygenxml.com/doc/versions/24.1/ug-editor/topics/ant-transformation-options-tab.html#ant-transformation-options-tab__dlentry_axl_cgk_54b). Running this customized scenario with your `.xspec` file should execute your test scenarios with the specified jar files. `SAXON_CP` has no effect in this case.
