### ISSUE TITLE
[Question] Setting value for current-dateTime

### ISSUE THREAD

**Issue by Lotan21** [xspec/xspec#1676]
Hello,

I've not been able to find this anywhere.
Is there a way to set a fix value of current date and time for specific scenarios? This would be required for testing of functions including the current-dateTime() function.

The only thing that seems available is the Saxon "-now" command line parameter which does not feel like a correct solution (I imagine this would break the reports dateTime mark).

**Comment by vincentml** [comment]
Hello @Lotan21 

One method is to use `...` in test expectations to elide nodes that will contain an unpredictable generated value such as a value generated by current-dateTime().  The `...` feature is described at https://github.com/xspec/xspec/wiki/Writing-Scenarios#ignoring-some-portions--in-the-expected-result

Another method is write test expectations using XPath functions. For example, `<x:expect label="generated value 'Now: ' || current-dateTime()" test="starts-with(., 'Now: ') and (substring-after(., 'Now: ') castable as xs:dateTime)"/>`

**Comment by AirQuick** [comment]
You can set the Saxon `-now` parameter in [`saxon.custom.options`](https://github.com/xspec/xspec/wiki/Running-with-Ant#ant-properties) (Ant and Oxygen) or [`SAXON_CUSTOM_OPTIONS`](https://github.com/xspec/xspec/wiki/Environment-Variables) (`xspec.bat` and `xspec.sh`). The entire test scenarios are tested with the specified Saxon parameters.

XSpec consists of three steps: Compile, Test and Report. `saxon.custom.options` and `SAXON_CUSTOM_OPTIONS`
is used only for Test. So they will not break the test result reports.

**Comment by Lotan21** [comment]
Thank you for the suggestions, since the saxon options affect only the test step, using the -now parameter seems like the best solution.
