### ISSUE TITLE
Schematron tests run using the ANT build.xml always fail

### ISSUE THREAD

**Issue by AlexJitianu** [xspec/xspec#168]
Hi,

I use the new build.xml script to execute one of the sample Schematron test files from {xspec}/tutorial/schematron . I use a simple command line, like this one:
`ant -Dxspec.xml=tutorial\schematron\demo-03.xspec  -Dtest.type=s`

All scenarios fail with reports like the one below. The test passes when I use xspec.bat .

![compare](https://user-images.githubusercontent.com/7802649/36265113-2cc5f04a-1277-11e8-8f08-091679a05b81.png)

I hope there isn't something obvious that I overlooked....

**Comment by AirQuick** [comment]
`demo-03.xspec` does not have `phase`. The way `build.xml` handles `phase` is different from `xspec.bat/sh`. Can you try this?
`ant -Dxspec.xml=tutorial\schematron\demo-03.xspec -Dtest.type=s -Dxspec.phase=#ALL`

**Comment by AirQuick** [comment]
If the .xspec file defines a phase, you don't have to provide `-Dxspec.phase=#ALL`. So this also should work:
`ant -Dxspec.xml=tutorial\schematron\demo-02-PhaseA.xspec -Dtest.type=s`

This is how the original PR #160 behaved. It was one of the things I was wondering about when I reviewed and updated the PR. But I didn't have time to pursue it. So the updated and merged version kept the behavior.
We should align `build.xml` with `xspec.bat/sh` which behaves more nicely. I'll create a PR.

**Comment by AlexJitianu** [comment]
Hi,

Thank you for your quick reply. Sorry for my late one.... I took the build.xml version from your pull request and now everything is working great!

Alex
