### ISSUE TITLE
Improve support for testing XPath functions defined in XSLT variables or XQuery variables

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1748]
In either XSLT or XQuery, you can define a variable whose value is an XPath function and then call that function using the variable.

It would be nice if XSpec could test an XPath function stored in variable. You can do this in some circumstances, but it's not that intuitive. This issue is to see if we can make the support more intuitive and agree on what that design would look like.

@xspec/xspec : Any thoughts from the XSpec community?

### XSLT
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:myf = "x-urn:example:xpath-fcn"
    version="3.0">
    
    <xsl:variable as="function(*)" name="myf:my-xpath-fcn" select="
            function ($x as xs:string) as xs:string {
                'input was ' || $x
            }"/>

</xsl:stylesheet>
```

### XQuery
```xml
module namespace myf = "x-urn:example:xpath-fcn";

declare variable $myf:my-xpath-fcn as function(*) :=
    function ($x as xs:string) as xs:string {
        'input was ' || $x
    }
;
```

### XSpec Design Ideas
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec"
    xmlns:myf = "x-urn:example:xpath-fcn"
    stylesheet="../xpath-fcn.xsl"
    query="x-urn:example:xpath-fcn"
    query-at="../xpath-fcn.xq"
    run-as="import">

    <x:scenario label="Design 1: Test an XPath function using XSpec variable">
        <!-- Does not work with run-as="external", but that limitation aligns with other
             limitations of external transformations -->
        <!-- Requires irrelevant x:call or x:context to avoid compiler error -->
        <x:variable name="fcn-call-result" select="$myf:my-xpath-fcn('xyz')"/>
        <x:call function="true"/>
        <x:expect label="XSpec variable value stores expected result of XPath function call"
            test="$fcn-call-result"
            select="'input was xyz'"/>
    </x:scenario>
    
    <x:scenario label="Design 2: Test an XPath function using x:call" pending="compiler error">
        <!-- x:call/@function value is not schema-valid due to $ -->
        <!-- If function variable name is in a namespace, compiler returns
            src\compiler\base\util\compiler-eqname-utils.xsl:30:14: Fatal Error! Invalid namespace prefix '$myf'
            -->
        <x:call function="$myf:my-xpath-fcn">
            <x:param select="'xyz'"/>
        </x:call>
        <x:expect label="$x:result stores expect result of XPath function call"
            select="'input was xyz'"/>
    </x:scenario>

</x:description>
```

### Design 1
In the XSpec compiler, remove the requirement to provide `x:call` or `x:context` in each scenario, or consider `x:variable` an acceptable substitute.

As a side benefit, that would make it easier to test other things besides functions stored in variables, such as

- XSLT accumulators ([example](https://github.com/xspec/xspec/pull/1734/files?diff=unified&w=0#diff-1bd59c4646b63558e1fa94b95dac8cbd81e3ebc672024a9742e5ce1426f9f8e4))
- XSLT keys
- XML content that you generated using a language other than XSLT or XQuery, where you'd like to make assertions about patterns in the XML. Maybe this is an edge case or out of scope, but I did come across a real-life situation once where it seemed like a useful thing to do.

### Design 2
Update XSpec schema so `x:call/@function` can hold a reference to a variable whose value is a function.

Investigate the `compiler-eqname-utils.xsl` error and adjust whatever is treating the `$` as part of the namespace prefix. I haven't looked into this yet, but I can do so if we want to support this design.

**Comment by AirQuick** [comment]
Maybe a new attribute for `x:call[@function]` is the easiest to implement, has virtually no impact on the other areas and requires only a few tests.

Suppose it's `x:call[@function]/@type`

```xml
        <x:call function="myf:my-xpath-fcn" type="variable">
            <x:param select="'xyz'"/>
        </x:call>
```

and then `x:function-call-text()` in `src/compiler/base/compile/compile-scenario.xsl` can prepend `$` when `@type` is `variable`.

**Comment by galtm** [comment]
Ease of implementation sounds good, especially since this would be kind of a niche feature. Your idea makes sense from the perspective that `myf:my-xpath-function` is the name and the prepended `$` is just the syntax for referring to the variable.

It would be nice if `type="variable"` had a counterpart representing the default behavior, to help distinguish the two choices from each other. However, the ideas I have so far all seem unclear or not really correct. In the spirit of brainstorming, here's what I thought of. Does any pair look reasonable?

1. `type="function-declaration"` (default) vs. `type="variable"`
2. `declaration-type="function"` (default) vs. `declaration-type="variable"`
3. `type="module-function"` (default) vs. `type="function-item"` (The [XSLT 3.0 spec](https://www.w3.org/TR/xslt-30/#dt-stylesheet-function) uses terms "stylesheet function" and "function item." I tried to broaden "stylesheet function" to make it less XSLT-centric but I'm afraid the meaning is not exactly the same.)
4. `call-as="function"` (default) vs. `call-as="variable"`
5. `language="native"` (default) vs. `language="xpath"`
6. `language="host"` (default) vs. `language="xpath"`

**Comment by galtm** [comment]
A data point: I showed your proposed syntax to someone who has some applicable instances, and they thought it was a nice improvement over the syntax they're currently using.

**Comment by galtm** [comment]
More possibilities to add to the list:

7. `type="module-function"` (default) vs. `type="variable"`
8. `call-as="module-function"` (default) vs. `call-as="variable"`
