### ISSUE TITLE
Adding a @original-location in compiled xspec for schematron

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#176]
When processing XSpec for Schematron, tested schematron is compiled to propduce a XSL, and original XSpec is "compiled" with `schut-to-xspec.xsl`.
Then, "compiled" XSpec is processed as it were a XSpec for XSLT, via the standard way.

    xspec.xspec -> xspec-compiled.xspec
    to-test.sch -> to-test.sch.xsl

I normal implementation, compiled XSpec is created in the same directory than original XSpec. In a maven project, it implies that compiled XSpec is created in `src/test/xspec`directory structure. `xspec-maven-plugin` generates all files in `target/xspec-report`, then all generated files can be safely deleted on `mvn clean`.

In xspec-maven-plugin, a general index is generated, which lists all xspecs processed. In this index, the file which is listed is `xspec-compiled.xspec` instead of `xspec.xspec`.
Would it be possible to add an information in `xspec-compiled.xspec`, to store the original location of xspec file, to be able to query it when generating index ?

This would generate a file that is not valid, regarding to `xspec.rnc`, but there is no validation in xspec process, so it doesn't matter.

I can submit a pull request for this.

Christophe

**Comment by vincentml** [comment]
Hi Christophe,

This makes sense. I have been thinking to change schut-to-xspec.xslt to retain the `x:description/@schematron` attribute, instead of removing it, in order to help improve the HTML report. As you mention, this would not be valid to xspec.rnc but that does not matter for the intermediary XML. Would retaining the `schematron` attribute do what you need?

The reason that the xspec-compiled.xspec file is saved to the same folder as the original xspec.xspec file is so that if the xspec file contains relative file paths to dependencies the files can be located correctly. How does xspec-maven-plugin handle locating dependencies with the compiled files being placed in target/xspec-report?

**Comment by cmarchand** [comment]
Accessing relative file paths dependencies has been an important challenge ! xspec-maven-plugin explores the xspec file and all its dependencies (imported / included / hrefed files), and copy them to target location, respecting relative pathes. I use [a library from Matthieu Ricaud](https://github.com/mricaud/xml-utilities/blob/master/src/main/xsl/org/mricaud/xml-utilities/get-xml-file-static-dependency-tree.xsl) to do this, and then copy - almost - all files listed.

What I need is not the schematron location, but the XSpec location. So retaining the `@schematron` is not a solution for me (even if it's also a good idea ! Maybe moving those attributes to a different namespace).

**Comment by vincentml** [comment]
Thanks for the explanation and the link. Please do send the pull request that you mentioned.

**Comment by cmarchand** [comment]
... Hum... I have to code it, before !
;)

**Comment by vincentml** [comment]
I just pushed a commit to branch test/176 with [these two changes](https://github.com/xspec/xspec/commit/076e39f9ffb9e62ca3033360c9412b2ef8fe912b). Does this do what you need?

**Comment by vincentml** [comment]
I've slightly improved this in commit 6d5330b on branch test/176, which can be seen [here](https://github.com/xspec/xspec/blob/6d5330b8741c22dddc0bd677c0aa9d80b6aa07e4/src/schematron/schut-to-xspec.xsl). Does this do what you need?

**Comment by cmarchand** [comment]
That's perfect for me.
Thanks a lot
