### ISSUE TITLE
Error if text value template in test for XQuery has line break

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1765]
In a test for XQuery, if user content has a text value template that contains a line break, the compiled query has a static error. I expected the white space to be insignificant. Is there a reason this isn't actually supposed to work?

### Reproducing the issue

I'm using an up-to-date master branch of XSpec. In the file

https://github.com/xspec/xspec/blob/c7d3facda100ed55d6ad207d2a38d07bc843dd18/test/tvt.xspec#L123C9-L123C9

insert a line break at the beginning of (and within) the TVT on line 123. That is, change it from
```
select="text()/string()" test="'}false{'">}}{myfn:false()}{{</x:expect>
```
to
```
select="text()/string()" test="'}false{'">}}{
myfn:false()}{{</x:expect>
```

Run this test against XSLT and XQuery. The XSLT test works, but the XQuery test shows an error.
```
>bin\xspec.bat -q test\tvt.xspec
Creating Test Stylesheet...
Checking for deprecated Saxon versions: Passed

Running Tests...
Static error near {...itennison.com/xslt/xspec" v...} on line 2063 at column 8 of file:/.../xspec/test/xspec/tvt-compiled.xq
  XPST0003  Invalid character '&' (x26) in expression
Static error(s) in query

*** Error running the test suite
```

The indicated line of the compiled query has the following:
```
text { <x:dummy xmlns:mirror="x-urn:test:mirror" xmlns:myfn="http://www.w3.org/2005/xpath-functions" xmlns:x="http://www.jenitennison.com/xslt/xspec" vt="}}{&#xA;myfn:false()}{{"/>/@vt }
```
where the relevant part is `vt="}}{&#xA;myfn:false()}{{"`.

**Comment by galtm** [comment]
Is the issue like the TODO in this line, related to #1021?
https://github.com/xspec/xspec/blob/c7d3facda100ed55d6ad207d2a38d07bc843dd18/src/compiler/xquery/node-constructor/node-constructor.xsl#L122

**Comment by AirQuick** [comment]
Changing `local:avt-or-tvt()` as follows seems to fix the crash.

```diff
-   <xsl:template name="local:avt-or-tvt" as="node()+">
+   <xsl:template name="local:avt-or-tvt" as="element(x:dummy)">
 
-         <xsl:attribute name="vt" select="." />
+         <xsl:value-of select="." />

-      <xsl:text>/@vt</xsl:text>
```

But I don't remember why #1077 used `@vt`. There may be a reason...

**Comment by galtm** [comment]
I don't know what the reason might have been, but your idea seems worth pursuing. In the `avt.xspec` and `tvt.xspec` test files, I can try adding some scenarios where AVTs and TVTs contain line feeds and tabs, and see if the results and the compiled tests look fine.
