### ISSUE TITLE
Document variables x:context and x:xspec-uri in wiki

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1771]
#1089 introduced `$x:context` in v2.0 and #435 introduced `$x:xspec-uri` in v1.3, but neither is documented in the XSpec wiki. I think these variables can be useful for end users.

* When you want to refer to the context both in `<x:context>` and elsewhere, `$x:context` avoids repetition and is a drop more convenient than defining an XSpec variable.
* When you want to read external content using `doc()` or `unparsed-text()` and you have to adjust for the compiled test being in a subdirectory compared to the original XSpec file, `$x:xspec-uri` is clearer than hard-coding `../` as a path adjustment.

**Comment by galtm** [comment]
It's OK to split this issue into separate ones for the two variables, if that seems clearer or more practical.

**Comment by AirQuick** [comment]
Random thoughts:
- https://github.com/xspec/xspec/blob/master/test/x-context.xspec should test `$x:context` with nested `x:context`.
- Doc for `$x:xspec-uri` should be clear about `x:import`, Schematron intermediate XSpec files and XML catalog. https://github.com/xspec/xspec/blob/master/test/xspec-uri.xspec should test it.
- I personally do not have a use case of `$x:context`.
- My only use case of `$x:xspec-uri` is to resolve test resource file URIs in `x:param` or `x:variable`, as mentioned in #435.

**Comment by galtm** [comment]
Created new wiki page: https://github.com/xspec/xspec/wiki/Special-Names

The page also includes `$x:result`, `$x:saxon-config`, and `@x:expand-text`. If we have any other user-facing special names, we can add them to the page, too. 

Feel free to modify the page as you wish, create a new issue to request modifications, or reopen this issue if you think that makes more sense.
