### ISSUE TITLE
How to test function with x:context?

### ISSUE THREAD

**Issue by tofi86** [xspec/xspec#18]
Hey there,

at the moment, I don't see a chance to test a function within a specific context.

Let's say I have this function which builds an absoulte XPath string from the current node:

```xslt
<xsl:function name="pa:get-current-xpath" as="xs:string">
	<xsl:param name="current-node"/>
	<xsl:variable name="temp">
		<xsl:for-each select="$current-node/ancestor-or-self::*">
			<xsl:variable name="current-ancestor-name" select="name()"/>
			<xsl:value-of select="concat('/',name(),'[',count(preceding-sibling::*[name()=$current-ancestor-name])+1,']')"/>
		</xsl:for-each>
	</xsl:variable>
	<xsl:sequence select="string-join($temp,'')"/>
</xsl:function>
```

And I want to write a test for this xml snippet:
```xml
<root>
	<element>
		<child>Content <inline>in</inline> child</child>
	</element>
</root>
```

And the test should call the function `pa:get-current-xpath()` from the context of the `<inline>` element so that the expected result is: `/root[1]/element[1]/child[1]/inline[1]`

```xslt
<x:scenario label="Scenario for testing function get-current-xpath">
	<x:context select="/root/element/child/inline/node()">
		<root>
			<element>
				<child>Content <inline>in</inline> child</child>
			</element>
		</root>
	</x:context>
	<x:expect label="Absolute XPath for inline element" test="pa:get-current-xpath(.)" select="'/root[1]/element[1]/child[1]/inline[1]'" />
	<x:expect label="Absolute XPath for inline element" test="pa:get-current-xpath(/root/element/child/inline)" select="'/root[1]/element[1]/child[1]/inline[1]'" />
	<x:expect label="Absolute XPath for inline element" test="pa:get-current-xpath(/root/element/child/inline/node())" select="'/root[1]/element[1]/child[1]/inline[1]'" />
</x:scenario>
```

None of the three `<x:expect>` statements is working. And it seems that `<x:context select="/root/element/child/inline/node()">` isn't working either for selcting a context...

Is there some other way? Probably with using `<x:call function="">`? If so I haven't found it yet...
Any ideas appreciated! Thanks!

Cheers,
Tobias

**Comment by cirulls** [comment]
Hi @tofi86,

thanks for the detail request and for posting code snippets. I should be able to have a look at your request during the weekend and let you know if I need more detail. I'll keep you posted.

Sandro

**Comment by tofi86** [comment]
Thanks, Sandro! 👍 

Also I was wondering which one of both the repos is the official repository? The `expath` one or this one?

**Comment by cirulls** [comment]
Hi Tobias,

you were right in guessing that you should use the ```<x:call function="">``` element in your XSpec test. You need to put the context inside the ```<x:param>``` element and use a ```select``` attribute to select the node you want to pass to the function. Given your function ```pa:get-current-xpath``` you posted above, here is an example of XSpec test for this function:

```xml  
<x:scenario label="When passing a node to function get-current-xpath">
    <x:call function="pa:get-current-xpath">
        <x:param name="current-node" select="/root/element/child/inline/node()">
	    <root>
		<element>
		    <child>Content <inline>in</inline> child</child>
		</element>
	    </root>
	</x:param>
    </x:call>

    <x:expect label="it should return the absolute path of the node" select="'/root[1]/element[1]/child[1]/inline[1]'"/>
</x:scenario>
```
I was able to run this test successfully. Let me know if it works at your end so that I can close the issue.

Sandro

**Comment by cirulls** [comment]
Regarding your question about the official xspec repository, I originally forked the xspec repository from the xpath organisation and submitted several pull requests to the project as well as reviewed pull requests from other people. Unfortunately I don't have write access to that repository and pull requests have been sitting there for almost a year now. Recently I have been given admin access to the [xspec organisation](https://github.com/xspec/) which was created when the code was moved from Google Code and I transferred my fork here. 

I'm hoping to revive XSpec project and I would be very interested in knowing how you are using XSpec, which features/bug fixes you'd like to see in the next XSpec release, etc. Feel free to post other issues/requests.

Thanks,

Sandro

**Comment by tofi86** [comment]
Hi Sandro,

great, your solution works like a charm! I wasn't aware that you can use `@select` on `<x:param>` WITH having context content inside...

This should probably be added in the Wiki as it's missing at the moment.
I tested and it seems my change to the wiki page was accepted:

https://github.com/xspec/xspec/wiki/Writing-Scenarios#function-scenarios

----

You can also the `@select` attribute on `<x:param>` PLUS context content inside to provide a specific data context to the function:

```xml
<x:scenario label="When passing a node to function do-something-with-element">
    <x:call function="eg:do-something-with-element">
        <x:param name="current-node" select="/root/element/child/node()">
            <root>
                <element>
                    <child>Text content</child>
                </element>
            </root>
        </x:param>
    </x:call>

    <x:expect label="it should return the name of the parent node" select="'element'"/>
</x:scenario>
```

----

We just started using Xspec as we're doing a lot of XSLT development in our company and I tried setting up Travis CI with automated Xspec tests in a small sample repository:
https://github.com/paginagmbh/xLib

It would be great if the Xspec group would revive and we would have ONE spot to post issues and questions to...
I will add an issue in the `expath` original repository to clarify the status as there have been new issues recently as well...

Thanks for your work, Sandro! 👍

**Comment by cirulls** [comment]
Thanks a lot for updating the documentation, I just slightly rephrased it. Great that you added a code snippet, that's the best example for the documentation!

**Comment by tofi86** [comment]
You're welcome! :)

**Comment by cirulls** [comment]
I subscribed to the xspec repository in the xpath organisation so if issues are raised there I receive a notification and I should be able to integrate them in here.

**Comment by tofi86** [comment]
Great! 👍 I also opened a new issue at https://github.com/expath/xspec/issues/85 to clarify the status of the two repositories...

If there's feedback on the topic, one could probably move the old open tickets over here...
