### ISSUE TITLE
Adding a reference to original XSpec file in report

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#180]
The xml report has no reference to the original XSpec file. It's not a matter when we have only few XSpec files, but when you have 100+ XSpec files, it may be difficult to identify which report you are consulting.

It'll be great to add an attribute on `x:report` :

    <x:report original-xspec-location="file:/...">
       ...
    </x:report>

This will be consistent with [Issue 176](https://github.com/xspec/xspec/issues/176).

Christophe

**Comment by AirQuick** [comment]
Closing this as resolved by #188
