### ISSUE TITLE
Clarify license for XSpec wiki

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1809]
Along the lines of #1786 : Would it be OK to put the XSpec wiki explicitly under the MIT license? I'm not sure what license, if any, covers the wiki because it's not part of what you get when you clone the repo. Maybe the main `README.md` could say something like, "XSpec, including the XSpec wiki, is released under..."

Cc: @xspec/xspec

**Comment by AirQuick** [comment]
https://web.archive.org/web/20090407011945/http://code.google.com/p/xspec/
> Code license: MIT License
> Content license: Creative Commons 3.0 BY

Maybe "Content license" applies to Wiki?

**Comment by galtm** [comment]
That seems like a good guess. The page [Introducing Content Licenses on Google Code](https://developers.googleblog.com/2008/07/introducing-content-licenses-on-google.html) (7/23/2008) mentions a content license being applicable to "non-source code materials" such as "data, documentation, and related media". So, I would expect the wiki to fall under those categories.

If it's simpler or more appropriate to put the XSpec wiki under one of the Creative Commons licenses rather than MIT license, that's fine with me. I'm mainly interested in having some clarity.

Side question: [This page](https://creativecommons.org/licenses/by/3.0/) says Creative Commons 3.0 BY is an older version and recommends [Creative Commons 4.0 BY](https://creativecommons.org/licenses/by/4.0/deed.en) instead. The [summary of differences in 4.0](https://creativecommons.org/Version4/) looks reasonable to me -- especially the "ready-to-use around the world" part. Do we want to use the newer license, and if so, who would need to agree to the change?
