### ISSUE TITLE
Strict mode to disallow focus

### ISSUE THREAD

**Issue by nkutsche** [xspec/xspec#1811]
Sometimes you forget to remove a `focus` attribute in your XSpec script. For a release process this can be very bad if the XSpec tests say everything is fine though it isn't.

The main [Maven Plugin](https://github.com/xspec/xspec-maven-plugin-1) fails if a `focus` is set, but since [my plugin](https://github.com/nkutsche/xspec-maven-plugin) is mainly just an Ant wrapper, it will only fail if the Ant process underneath throws an exception. Of course I could create a workaround for this by looking into the XSpec files, but maybe it is also interessting for you to introduce something like a strict mode that causes a failure by `focus` attributes. It might also be of interest to some non-Maven users?

**Comment by galtm** [comment]
The suggestion makes sense to me. I have a checklist for my own purposes where "search for and remove any remaining focus attributes" is one item, and automating it would be nice.

What and where would the indicator of strict mode be? If it's some attribute in the XSpec file itself, then when you start using `focus` during your development process, you'll remove strict mode temporarily and could have the same problem where you forget to both remove `focus` and restore strict mode.

In light of #1654, what if we had a Schematron check that reports on `focus` attributes? Maybe it's an "info" type check in the absence of strict mode. If we also add a strict mode indicator in the XSpec markup, then strict mode plus `focus` attribute could be a Schematron error (perhaps with SQF to remove either `focus` or strict mode).

Regarding usage by non-Maven users: I know of one organization that automates running XSpec tests in a home-grown way that does not use Maven. I don't know how common that is, though.

**Comment by nkutsche** [comment]
> What and where would the indicator of strict mode be?

Well my expectation would be an execution parameter of the framework - in our case an Ant property. An Oxygen transformation scenario could deactivate the strict mode, but a releasing script should activate it. I don't think it should be part of the XSpec script. You may have multiple XSpec scripts, but you execute them in a releasing process or for debugging. Not mixed.

> In light of https://github.com/xspec/xspec/issues/1654, what if we had a Schematron check that reports on focus attributes?

It could make sense to implement the check with Schematron. Maybe with an extra phase for the strict mode?

**Comment by nkutsche** [comment]
That sounds like exactly what I'm looking for! Do I understand the logic correctly, that if I call XSpec with `xspec.force.focus=NONE` and my XSpec contains a `<x:scenario label="NONE">` this scenario would be in focus and any other wouldn't? So as plugin developer who does not know the given XSpec scripts the "challenge" would be to use a value which is not expected as label of a scenario to avoid unexpected behaviors, right?

**Comment by AirQuick** [comment]
`xspec.force.focus` doesn't correspond with labels; it matches scenario IDs generated internally at runtime based on their hierarchical position. You can find the assigned IDs in the test result XML, like this example:
https://github.com/xspec/xspec/blob/d7350ed9a8a54a00f8bf6ab8bc1ce3fa2eec430c/test/end-to-end/cases/expected/stylesheet/force-focus_escape-for-regex-result.xml#L30

So, although the implementation details may change, it is unlikely `xspec.force.focus=NONE` will match any scenarios in the future. `xspec.force.focus=#NONE` would be even more safe, considering that the ID is also used as `@id` in the test result HTML and therefore unlikely to start with `#`.

**Comment by nkutsche** [comment]
Thanks @AirQuick! Now I understand why it is undocumented! 🙂

So for my initial purpose, this hidden feature covers my needs. Shall we close the issue or do you think it is worth to implement a public feature for other users?

**Comment by AirQuick** [comment]
#1814 adds a test which verifies that `xspec.force.focus=#none` (case sensitive) invalidates `@focus`. Once merged, we can update Wiki to include this information.

**Comment by AirQuick** [comment]
[Updated](https://github.com/xspec/xspec/wiki/Running-with-Ant/_compare/04e1933dcf26e9d3ba69180fb25b6b52b4c43696...9f8ddb8ae38483433637775bd82e345db5d9c7af) the Wiki.
