### ISSUE TITLE
Enhance XSLTCoverageTraceListener to be able to specify the output to use

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#182]
Using XSpec from command line, XSLTCoverageTraceListener write results to standard error output. That's perfect as it's possible to redirect output anywhere.
But, when using from a Java program ([xspec-maven-plugin](https://github.com/xspec/xspec-maven-plugin-1), in fact), it is not very easy because playing with standard outputs can be a nightmare.

More, each instance should be thread-safe to be able to run many XSpec multi-threaded.

Adding a constructor XSLTCoverageTraceListener(java.io.PrintStream) should solve this issue.

A bit of refactoring could also be done to specify output properties.

I'll attach a pull request for this.

**Comment by AirQuick** [comment]
I'm not sure what your pull request will be like, but if you could, I hope the pull request fixes a problem I wrote before: "[The coverage XML is not well-formed](https://github.com/xspec/xspec/issues/36#issuecomment-269933284)"

**Comment by AirQuick** [comment]
@cmarchand 
If you're working on the pull request, would it be possible to include these?
* Output the coverage XML to a file.
* The output file path (not file URL) can be specified from Ant `java` task as well as a `java` command line in shell script.
* Optionally, these hard-coded file URL checks should be based on file paths (not file URLs) provided externally (again including Ant and command line):
https://github.com/xspec/xspec/blob/c9fdb91a6bcd7d1b160fadedf87f35be2c5f57c4/java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java#L77
https://github.com/xspec/xspec/blob/c9fdb91a6bcd7d1b160fadedf87f35be2c5f57c4/java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java#L81

That would be of help in resolving not only the problem I mentioned in a previous message but also #147.

**Comment by cmarchand** [comment]
Yes, I'm gonna do this.
As we can only specify to Saxon the class name, from command-line or ant, I planned to use System Properties. For a API use, it's much more easy.

Say :
 - if a system property call `com.jenitennison.xsl.tests.coverage.generate-tests-utils` is defined, then use its value instead of constant used a line 77
 - if a system property call `com.jenitennison.xsl.tests.coverage.xspec-path` is defined, then use its value instead of constant used at line 81
 - add two setters `setGenerateTestsUtilsValue(String)` and `setXSpecPath(String)` to use from API. If these method are called, it overwrites the values defined via system properties (now way to change code behavior from launch)
 - if a system property call `com.jenitennison.xsl.tests.coverage.output` is defined, use its value to construct the output file ; if not, use `System.err` for backward compatibility
 - add a new `Constructor(java.io.PrintStream)` to allow to define another output from API.

Does this match what you need to use from command line or from ant ?

**Comment by AirQuick** [comment]
Thanks. The logic seems fine!
* Please make sure to expect the value of those system properties to be an OS native file path (not a file: URL).
* The name `[...].xspec-path` looks as if it were a `.xspec` file or the XSpec installation path. Maybe `[...].temp-output-dir` or `[...].ignore-dir` or something would be better, if I understand correctly?

**Comment by cmarchand** [comment]
Spec proposal updated

**Comment by AirQuick** [comment]
Thanks!
Just for your reference. On Windows, command-line and Ant will be setting sys props like these for example:
```
com.jenitennison.xsl.tests.coverage.generate-tests-utils=F:\xspec\src\compiler\generate-tests-utils.xsl
com.jenitennison.xsl.tests.coverage.ignore-dir=P:\XSpec\temp out
com.jenitennison.xsl.tests.coverage.output=P:\XSpec\temp out\escape-for-regex-coverage.xml
```

**Comment by cmarchand** [comment]
I'm gonna write a dedicated test-case for windows

**Comment by AirQuick** [comment]
Closing this issue, because I think it is now obsolete.
