### ISSUE TITLE
Breaking changes in v3.0

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1825]
Are we anticipating any breaking changes in v3.0? If so, we can keep a running list here and eventually add content to the release notes.

### For end users

- Saxon 9.9 is no longer supported
  - 10 or later is required
  - 12 is recommended

- Code Coverage requires Saxon 12.4 or later

- The *skeleton* Schematron implementation is no longer supported. Use [SchXslt](https://github.com/schxslt/schxslt) instead, as [advised](https://github.com/Schematron/schematron#readme).

### For those who access XSpec internals

- (**_Deferred_**) XSLT trace listener Java class `com.jenitennison.xslt.tests` is changed to `io.xspec.xspec.saxon.something`

**Comment by AirQuick** [comment]
Added some ideas that are on the horizon.

**Comment by galtm** [comment]
For the record: As a result of #1847, `<x:like>` no longer permits the `expand-text` attribute, which did not accomplish anything on that element tree anyway. Maybe this change doesn't need to be in the release notes because `<x:like>` isn't documented in the wiki yet. Any user who knows about the feature and was using the `expand-text` attribute should remove the attribute; the test will behave the same way.

**Comment by galtm** [comment]
Hi, @AirQuick . About version 3.0:

1. Do you want me to do the release steps that I did for our last release?
2. Will you be able to generate the release notes using the code you can't share?
3. The milestone has a date of Jan. 27, but we still have a number of unfinished items. I think we should delay the release and get more of the planned items completed. Do you agree?

**Comment by galtm** [comment]
@AirQuick : Not hearing any replies from you yet, I will do my best under the assumption that the answers to my questions are

1. Yes
2. No (but if the answer is actually yes, that will be great)
3. Yes

I changed the date of the v3.0 milestone to April 15, 2024. I have been chipping away at open items and the backlog of pull requests.

I've been leaving the code coverage upgrade for last, in the hope that Saxonica releases their fix for some code coverage regressions in Saxon v12.x and I can confirm the fixes in XSpec. If that doesn't happen before we release v3.0, we can say something in our release notes to alert users.
