### ISSUE TITLE
Drop the skeleton Schematron implementation

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#1828]
v3.0 may be a good chance to stop maintaining two branches ([`master`](https://github.com/xspec/xspec/tree/master) for the *skeleton* Schematron implementation and [`schxslt`](https://github.com/xspec/xspec/tree/schxslt) for SchXslt).

1. Rebase the `master` branch to the `schxslt` branch
1. Delete the `schxslt` branch
1. Move `.github/workflows/rebase-schxslt.yml` to `misc/archive/` (and maybe reuse it for [`SchXslt2`](https://git.sr.ht/~dmaus/schxslt2) later)

**Comment by galtm** [comment]
Fixed by  #1881
