### ISSUE TITLE
fix travis configuration

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#19]
After the repo transfer from cirulls/xspec to xspec/xspec, the travis configuration needs to be updated as it is still trying to trigger from the previous repository. Amend configuration in the ```.travis.yml``` and ```README```. Plus, move the Saxon processing to its own directory.

**Comment by tofi86** [comment]
As I wrote in 7303f0d moving saxon caused all existing travis build pipelines to fail!

You may probably consider reverting this change!

**Comment by tofi86** [comment]
Also, the example bash script described on the Travis Wiki page

```bash
for xspectest in *.xspec; 
    do ../bin/xspec.sh $xspectest &> result.log; 
    if grep -q ".*failed:\s[1-9]" result.log || grep -q "*\sError\srunning\sthe\stest\ssuite" result.log; 
        then echo "$xspectest failed" && exit 1; 
        else echo "ok $xspectest";
    fi  
done
```

did not properly detect compiling issues (e.g. when Saxon is not available at the given path).

I updated the wiki entry with better detection:

```bash
for xspectest in *.xspec;
    do ../bin/xspec.sh $xspectest &> result.log;
    if grep -q ".*failed:\s[1-9]" result.log || grep -q -E "\*+\sError\s(running|compiling)\sthe\stest\ssuite" result.log;
        then echo "FAILED: $xspectest" && exit 1;
        else echo "OK: $xspectest";
    fi
done
```

**Comment by cirulls** [comment]
I answered about the location of the Saxon processor in https://github.com/xspec/xspec/commit/7303f0dce788fd8d0e091705b261d4aa284e75d2.

Thanks for updating the documentation, I will add the extra bit to [run-xspec-tests.sh](https://github.com/xspec/xspec/blob/master/test/run-xspec-tests.sh).

**Comment by tofi86** [comment]
> Thanks for updating the documentation, I will add the extra bit to run-xspec-tests.sh.

Great! I didn't see that it's also part of the repository...

**Comment by cirulls** [comment]
I created #20 and #21 and I close this ticket.
