### ISSUE TITLE
Coverage and Schematron

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#191]
Hello,

some questions on coverage reporting when unit-testing schematron.
 1. schematron file is compiled as an XSLT
 2. xspec for schematron is compiled as a *normal* XSpec that references the compiled schematron XSLT
 3. `sch-location-compare.xsl` is used in process, as a utility module.

Asserts :
 - The only coverage reporting we can have is on the XSL generated at 1), not on schematron file. Correct ?
 - `sch-location-compare.xsl` should be excluded, as `generate-tests-utils.xsl` is. Correct ?

**Comment by AirQuick** [comment]
At the moment, I don't think the code coverage is made to support XQuery and Schematron.
At a glance `xspec.sh` appears to support XQuery, but actually it doesn't work. (#36)

In terms of the current behavior, I think your asserts are right. But I'm not sure if the current behavior makes sense.

**Comment by cmarchand** [comment]
Ok, I'm gonna limit xspec-maven-plugin coverage to pure XSLT, and exclude XQuery and Schematron

**Comment by AirQuick** [comment]
I'll also do so in Ant in the upcoming pull request.
I'll leave `xspec.sh` and `xspec.bat` as they are.

Can we close this issue now?

**Comment by cmarchand** [comment]
Sure !
And done...

**Comment by AirQuick** [comment]
Pinging @vincentml and @tgraham-antenna , just in case.
