### ISSUE TITLE
Testing on macos-latest fails with Java 8

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#1919]
The failure commented on in https://github.com/xspec/xspec/pull/1918#issuecomment-2078454284 looks like https://github.com/actions/setup-java/issues/625 .

Based on links from that issue 625 to other GitHub issues/PRs, I see two resolutions that different repos are using (at least temporarily):

A) Using zulu distribution instead of temurin for macOS
B) Requesting macos-13 instead of macos-latest

**Comment by galtm** [comment]
@cmarchand : Do you have any thoughts on the best solution for this repo?

For reference: [List of distributions supported by setup-java](https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions)

**Comment by galtm** [comment]
You asked:

> Where is the script source for this build ?

This is the configuration file for the test workflow:

https://github.com/xspec/xspec/blob/master/.github/workflows/test.yml

**Comment by cmarchand** [comment]
There no JDK 8 available for MacOs ARM : https://adoptium.net/temurin/releases/?version=8&os=mac&arch=arm&package=jdk

I don't know if it's new or not. Probably not.

And I'm not able to find if macos-latest runner is a Intel or an Arm. 

We probably should add a `uname -a` in the build process, before installing Java, to check this. Maybe GitHub has changed its default infra recently...

**Comment by cmarchand** [comment]
Ok, it's now on M1, Arm. So yes, it's the same problem than [actions/setup-java#625](https://github.com/actions/setup-java/issues/625).

I'm reluctant to use an old MacOs OS version.

I'd prefer using either :
- [Bell Liberica](https://bell-sw.com/pages/downloads/#jdk-8-lts)
  - it's coherent with [this](https://github.com/galtm/xspec-book-reviews/pull/26#discussion_r1581604952)
- [Azul Zulu](https://www.azul.com/downloads/?package=jdk#zulu)

**Comment by galtm** [comment]
Your idea of sticking to `macos-latest` while picking a different distribution, with Bell Liberica as the first choice, sounds good to me. I can try that in the coming week (probably imitating the syntax in https://github.com/apache/logging-parent/pull/169/files except with liberica instead of zulu), but if you want to pursue this yourself, feel free.
