### ISSUE TITLE
xsl:assert Code Coverage Non-Conformance

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#1940]
### Current Non-Conformance
The `xslt-code-coverage-behavior-by-element.md` file says that `xsl:assert` elements should be marked based on their child elements.
The `coverage-report.xsl` in 3.0.3 marks them as 'missed' because there is no hit element in the XSpec trace file and there is no specific rule in `coverage-report.xsl` to process them.

### Changes in `coverage-report.xsl`
A rule needs to be added to `coverage-report.xsl` as follows for `xsl:assert`:
If node has no children, mark it as 'unknown'.
If the trace data has a "hit" element for a child of this node, then mark this node as a 'hit'.
Otherwise, mark it as 'missed'.

### Changes in `test/end-to-end/cases-coverage/expected`
In the coverage report `xsl-assert-01-coverage.html` the first `xsl:assert` element with a test "100 lt 0" will be marked as 'hit' rather than 'missed'. There will be no change for the second `xsl:assert` element.

**Comment by galtm** [comment]
Alert - According to #1963, Saxon 12.5 traces neither `xsl:assert` nor its children. If we follow the Saxon 12.4 suggestion in this issue, a report generated with Saxon 12.5 might say "missed" when it should say "unknown".

**Comment by galtm** [comment]
Repeating relevant portion of #1963:

> ### xsl:assert
> The `xslt-code-coverage-by-element.md file` says `xsl:assert` is not traced and rule is Use Child Data. I hadn't noticed in Saxon 12.4, but it was traced on the first child, however in Saxon 12.5 it is NOT traced and neither are the children. The TRACE row should be changed to 'No'. The RULE row should be changed to 'Element Specific - set to 'unknown', including all descendants.

@birdya22 : Given that Saxon 12.4 produces incorrect data and Saxon 12.5 produces no data about `xsl:assert` or its child nodes, what do you think about using the "unknown, including all descendants" rule immediately, even before this repo upgrades from Saxon 12.4 to 12.5? Even with 12.4, "unknown" could be seen as an improvement over "always missed" (the behavior right now on the `master` branch), which is wrong for an element that executes.

**Comment by birdya22** [comment]
That makes sense to me.

Can I check something about your statement:

> even before this repo upgrades from Saxon 12.4 to 12.5

I was wondering what that actually means. The [Requirements](https://github.com/xspec/xspec/wiki/Requirements) page of the Wiki says 'XSpec is tested on Saxon 12, 11, 10, and 9.9. Support for 9.9 is on a deprecation path.'. I'm fine with that from an end user point of view.
From an internals point of view each version of XSpec is 'built' against a specific version of Saxon, so I would expect 100% success if I ran the 3.0.3 [Test Suite Locally](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) using Saxon 12.4 but not if I used Saxon 12.5 (the reason being that the 'expected' files are produced using the XSpec version of Saxon, which was 12.4 for release 3.0.3).

Are there a set of files that could be extracted that represent Saxon 12.4 'expected' output once 'this repo upgrades from Saxon 12.4 to 12.5?

Or, more concisely, does XSpec support builds with different versions of Saxon?

**Comment by galtm** [comment]
> Are there a set of files that could be extracted that represent Saxon 12.4 'expected' output once 'this repo upgrades from Saxon 12.4 to 12.5?

I'm pretty sure I could implement a way to to test XSpec in GitHub against both 12.4 and 12.5 for some period of time. A Git branch-based option could be to maintain a long-running `saxon12.4` branch alongside the `master` branch, update only the latter branch's 'expected' coverage results to Saxon 12.5, and have tests running on each branch with the corresponding Saxon version. A single-branch option could be to have side-by-side `expected/` directories on the `master` branch and have the end-to-end testing infrastructure know which directory to use during testing.

It would be nice if we didn't feel compelled to do that, though -- that is, if code coverage reporting could reach a point where one 12.x version (preferably the latest one) is the obvious best version to use.

**Comment by birdya22** [comment]
I wasn't suggesting it was needed, but was just trying to make sure I understand the current situation.
