### ISSUE TITLE
xsl:fallback Code Coverage Non-Conformance

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#1942]
### Current Non-Conformance
The `xslt-code-coverage-behavior-by-element.md` file says that `xsl:fallback` elements should be marked based on their child elements.
The `coverage-report.xsl` in 3.0.3 marks them as 'missed' because there is no hit element in the XSpec trace file and there is no rule in coverage-report.xsl to process them.

### Changes in `xsl-fallback-01.xsl` and `xsl-fallback-01.xspec`
The `xsl-fallback-01` test should have a test where the children of the `xsl:fallback` element are not executed, showing the `xsl:fallback` element is correctly marked as 'missed'. 

### Changes in `coverage-report.xsl`
A rule needs to be added to `coverage-report.xsl` as follows for xsl:fallback:
If node has no children, mark it as 'unknown'. 
If the trace data has a "hit" element for a child of this node, then mark this node as a 'hit'. 
Otherwise, mark it as 'missed'. 
 

### Changes in `test/end-to-end/cases-coverage/expected`
In the coverage report `xsl-fallback-01-coverage.html` the `xsl:fallback` element  will be marked as 'hit' rather than 'missed'.

**Comment by galtm** [comment]
Regarding "Changes in `coverage-report.xsl`" above, see the amendment mentioned in item 2 of https://github.com/xspec/xspec/issues/1943#issuecomment-2227139850.
