### ISSUE TITLE
xsl:with-param Code Coverage Non-Conformance

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#1947]
### Current Non-Conformance
The `xslt-code-coverage-behavior-by-element.md` file says that `xsl:with-param` elements should be marked based on their parent element.
There are hit elements in the XSpec trace file for `xsl:with-param` in some circumstances so `xsl:with-param` elements are sometimes marked as 'hit' and sometimes marked as 'missed'.

### Changes in `coverage-report.xsl`
A rule needs to be added to `coverage-report.xsl` for `xsl:with-param` elements to check the parent.
If the trace data has a "hit" element for this node's parent, mark this node as a 'hit'.
Otherwise, mark it as 'missed'.

### Changes in `test/end-to-end/cases-coverage/expected`
In the coverage report `xsl-with-param-01-coverage.html` the 3 `xsl:with-param` elements marked as 'missed' will be marked as 'hit'.
In the coverage report `xsl-iterate-01-coverage.html` the 2 `xsl:with-param` elements will be marked as 'hit' rather than 'missed'.

There will be no change in `xsl-next-match-01-coverage.html` or `xsl-param-01-coverage.html` coverage reports.

The change will also have an effect on the `xsl:with-param` elements in the `xsl-evaluate-01-coverage.html` coverage report. Once a decision has been made on the rules for `xsl:evaluate` this issue will be updated with details of any changes to the `xsl:with-param` elements.

**Comment by galtm** [comment]
#1978 implements Use Parent Status, which is a bit different from Use Parent Data; see explanation in the pull request description. I checked that the changes in `test/end-to-end/cases-coverage/expected` in that pull request match what's written in this issue.
