### ISSUE TITLE
Coverage Test xsl-map-01 Needs Additional Tests

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#1953]
The current `xsl:map` Coverage Test has only `xsl:map-entry` elements as children of `xsl:map` and only `xsl:sequence` elements as children of `xsl:map-entry`.
As `xsl:sequence` and `xsl:map-entry` elements are not in the XSpec trace file the current test implies that children of `xsl:map` and `xsl:map-entry` are not in the XSpec trace file.
The test needs expanding to check this.
Also, it is possible to use `xsl:map-entry` outside of `xsl:map`. This needs a test as well. 

The xsl-map-01 coverage test needs to cover the following scenarios:

- `xsl:map-entry` with a child element that is in the XSpec trace file e.g. `xsl:copy`
- `xsl:map` with a child element that is not `xsl:map-entry` e.g. `xsl:for-each`
- `xsl:map` as a child of `xsl:variable`

For added coverage some `xsl:sequence` elements will have a sequence constructor instead of using a select attribute.

Attached is a suggested test case (the files have had .txt added to allow them to be attached).

The suggested test case shows that children of `xsl:map` and `xsl:map-entry` do appear in the XSpec trace file e.g. the `xsl-copy` and `xsl:for-each` are seen.

#### Possible Rule
Based on the XSpec trace data, the Rule could be Use Child Data for `xsl:map-entry` and maybe Use Parent Data for `xsl:map`.

However, using this Rule will cause some confusion for the users because there might be the following, very unlikely, situation (see attached mock up - blue = 'unknown', green = 'hit' and pink = 'missed'.):
1. `xsl:map-entry` with select attribute marked as 'unknown'.
2. `xsl:map-entry` with `xsl:sequence` sequence constructor using select attribute. `xsl:sequence` marked as 'unknown' and `xsl:map-entry` marked as 'missed'.
3. `xsl:map-entry` with `xsl:copy` sequence constructor. `xsl:copy` marked as 'hit' and `xsl:map-entry` marked as 'hit'.
4. `xsl:map-entry` with `xsl:sequence` and `xsl:copy` that is in the XSpec trace file. `xsl:sequence` marked as 'hit' and `xsl:map-entry` marked as 'missed'.

The 4 `xsl:map-entry` elements are marked as 'unknown', 'missed', 'hit' and 'unknown'.
In this case the `xsl:map` parent is marked as 'hit' because the parent is in the XSpec trace file.

It looks a mess and I don't have a solution to make it better.
It is obviously very unlikely but I don't know  how users normally use these elements, but they could end up with  mixture of results.

My current inclination is to do the simple thing and mark `xsl:map` and all descendants as 'unknown'.

What are your thoughts?

[xsl-map-01.xspec.txt](https://github.com/user-attachments/files/15926004/xsl-map-01.xspec.txt)
[xsl-map-01.xsl.txt](https://github.com/user-attachments/files/15926006/xsl-map-01.xsl.txt)
![xsl-map-01_Mock_up](https://github.com/xspec/xspec/assets/168069809/41ef1cfd-36d0-48c3-9cbc-ccac905ce7bc)

**Comment by galtm** [comment]
@birdya22 , thanks for identifying and filling these gaps. In the test updates, all the `xsl:map` elements and their descendants look good.

It is a little confusing that many of the `xsl:map` and `xsl:map-entry` elements (e.g., lines 57-59) appear as "hit" not because they're traced but rather due to logic in `coverage-report.xsl` where descendants of variables take on the coverage status of the variable if those descendants don't have a hit in their own right.
```
<xsl:when test="ancestor::xsl:variable">
   <xsl:sequence select="local:coverage(ancestor::xsl:variable[1], $module-id)" />
</xsl:when>
```
But you didn't create this confusion. I think we should use your attached files' content as is. Maybe when we revisit logic for `xsl:variable` in `coverage-report.xsl`, this confusion will go away (either with no test changes, or by making the variables global in the test).

---

Another thing I noticed about the trace is that the hit for the template param (line 17) shows up for the _grandchild_ `xsl:map-entry` element (line 20) -- not the first child element of the template param, which is `xsl:map` on line 18. Do you know if the misplaced hits for `xsl:param` are mentioned in a Saxonica bug report? I did a few quick searches and couldn't find anything.

**Comment by galtm** [comment]
> #### Possible Rule
> Based on the XSpec trace data, the Rule could be Use Child Data for `xsl:map-entry` and maybe Use Parent Data for `xsl:map`.
> 
> However, using this Rule will cause some confusion

This is tricky, and I need more time to think about it. One clarifying question: when you say Use Parent Data do you mean

a) Follow the usual Use Trace Data rule for the parent node, and assign the result to the child node?

b) Look at the coverage status of the parent node (even if that was assigned in some element-specific way, not Use Trace Data) and assign the child the same status as the parent?

Perhaps (a) is like "Use Parent Trace Data," while (b) is like "Use Parent Status." In the current `coverage-report.xsl` logic, elements like `xsl:context-item` use (b).

**Comment by birdya22** [comment]
> This is tricky, and I need more time to think about it. One clarifying question: when you say Use Parent Data do you mean

> a) Follow the usual Use Trace Data rule for the parent node, and assign the result to the child node?

This is what I was thinking of, but it does cause problems when it's the child of `xsl:param` and sometimes `xsl:variable` which are not traced directly in the XSpec trace file.

> b) Look at the coverage status of the parent node (even if that was assigned in some element-specific way, not Use Trace Data) and assign the child the same status as the parent?

I like this better, but do you know how it would be implemented?

**Comment by galtm** [comment]
> > Another thing I noticed about the trace is that the hit for the template param (line 17) shows up for the grandchild xsl:map-entry element (line 20) -- not the first child element of the template param, which is xsl:map on line 18. Do you know if the misplaced hits for xsl:param are mentioned in a Saxonica bug report? I did a few quick searches and couldn't find anything.
> 
> I haven't seen anything about that in Saxonica issues. A quick test seems to indicate that it depends on whether the first child is normally traced and whether it has a child. 3 examples (`xsl:sequence` not traced, `xsl:value-of` traced):
> 
> `<xsl:sequence select="22" />` - param trace appears on here
> 
> `<xsl:sequence>` `<xsl:value-of select="22" />` - param trace appears on here i.e. grandchild `</xsl:seuqnece>`
> 
> If you use xsl:value-of `<xsl:value-of>` - param trace appears on here `<xsl:text>22</xsl:text>` `</xsl:value-of>`

Thanks for the additional cases. I just created this issue report (feel free to add to it if you like):
https://saxonica.plan.io/issues/6457
