### ISSUE TITLE
xsl:merge* Code Coverage Rule Definition

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#1959]
### Rule Definition
The `xslt-code-coverage-behavior-by-element.md` file has "Element Specific - TBD" for the rule for descendants of `xsl:merge`, but does have information about trace details for the element.
This issue proposes a specific rule.
The `xsl:merge` element has a well defined structure where the child elements are always present. Although only the `xsl:merge` element is traced the state of its children can be based on the state of the `xsl:merge` element. 

`xsl:merge-source` can only appear as a child of `xsl:merge`. If `xsl:merge` is hit then it is safe to say that `xsl:merge-source` is also hit.
`xsl:merge-source` can only have `xsl:merge-key` children.
`xsl:merge-key` can only appear as a child of `xsl:merge-source`. If `xsl:merge` is hit then it is safe to say that `xsl:merge-key` is also hit.
`xsl:merge-key` can contain a sequence constructor. The sequence constructor is never traced. If `xsl:merge-key` is marked as 'missed' all elements in its sequence constructor are marked as 'missed'. If the `xsl:merge-key` is marked as 'hit' all elements in its sequence constructor are marked as 'unknown' because the sequence constructor could contain `xsl:if`, `xsl:choose` etc. and there is no trace data about whether these are executed.
`xsl:merge-action` can only appear as a child of `xsl:merge-source`. If `xsl:merge` is hit then it is safe to say that `xsl:merge-action` is also hit.
`xsl:merge-action` contains a sequence constructor. The elements of the sequence constructor are traced so nothing special needs to be done for them, they can Use Trace Data.
Note: it would be possible for `xsl:merge-action` to Use Child Data, but the suggestion is that it follows the same rule as other `xsl:merge-*` descendants of `xsl:merge`.

So the rules are:
`xsl:merge-source` - Use Parent Data
`xsl:merge-key` - use the result for the `xsl:merge` ancestor.
`xsl:merge-key` descendants - if `xsl:merge` is marked as 'hit' then mark all elements as 'unknown', otherwise mark them as'missed'.
`xsl:merge-action` - Use Parent Data

### Changes in `coverage-report.xsl`
Additional rules for the xsl:merge-* elements.

### Changes in test/end-to-end/cases-coverage/expected
In the coverage report `xsl-merge-01-coverage.html` all the descendants of `xsl:merge` will be marked as 'hit' with the exception of the descendants of `xsl:merge-action` which will be marked as 'unknown'.

**Comment by galtm** [comment]
I'm not very familiar with `xsl:merge` but what you've written here sounds entirely sensible.

The `xsl-merge-01.xsl` test file could use an `xsl:merge` element that isn't reached, so we can confirm that `xsl:merge-key` descendants are marked as "missed" instead of "unknown". I think I'll include that in #1961, which is still open and already a grab bag of coverage test additions.
