### ISSUE TITLE
Add Saxon 12.5 GetLocation method into XSLTCoverageTraceListener

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#1971]
Saxon 12.5 added a new method, `GetLocation`, into the `AbstractTraceListener`. Its description is:

> Get the location information for the traceble expression or instruction.
> This method adjusts the location for XPath expressions contained in attributes
> of XSLT instructions, to give the location of the containing element, which
> supplies a simple line number and column number.

This should be a link to the diff of the [change](https://saxonica.plan.io/projects/saxonmirrorhe/repository/he/diff/src/main/java/net/sf/saxon/trace/AbstractTraceListener.java?utf8=%E2%9C%93&rev=9ad01ba2ce9ed395bdd21f2ee8e7933862020f37&rev_to=eee61b5e99ae49c1d20fff93b681cccd9502d871) in the Saxonica SaxonMirrorHE repo. 
 
The effect of this method is to produce a better value for the column number in some cases e.g. instead of producing 0, it produces valid values that reflect the end of the element tag. 

Having added the method to a copy of the `XSLTCoverageTraceListener` and changed the first line in the `enter` method to `Location location = getLocation(traceable);` I got the following differences in the `xsl-xxx-0n.xsl` tests locally, which would result in a 'hit' for these elements:

```
xsl-map-01.xsl line 12 - xsl:sequence with select attribute (Col 34 rather than 0)
xsl-map-01.xsl line 50 - xsl:for-each (Col 39 rather than 0)
xsl-on-non-empty.xsl line 28 - xsl:sequence with select attribute (Col 57 rather than 22)
xsl-perform-sort-01.xsl line 24 - xsl:copy-of with select attribute (Col 40 rather than 4)
xsl-sequence-01.xsl line 10 - xsl:sequence with select attribute (Col 40 rather than 0)
```

If this is implemented it will affect the comments I made about `xsl:copy-of`, `xsl:for-each` and `xsl:sequence` in [1963](https://github.com/xspec/xspec/issues/1963) and the current design decisions in [xslt-code-coverage-by-element.md](https://github.com/xspec/xspec/blob/master/docs/xslt-code-coverage-by-element.md).

Note: I have had a quick look at the differences if I use `-Tlevel:high` in my `TraceListener` but I need to do more investigation. In particular I think there will be an issue when using `run-as="external` because I don't think the `-Tlevel` value will be propagated to all the `transform()` calls, but I need to check.

**Comment by galtm** [comment]
Thanks for this investigation, which will surely help with the Saxon 12.5 upgrade. For the moment, I'll keep working on the XSLT bug fixes, but I look forward to seeing what else you learn here.

**Comment by galtm** [comment]
@birdya22 : When I downloaded the ZIP-file, Windows said it was empty. Can you please try uploading it again?

It sounds like you're saying that -Tlevel:high produces better results in the `run-as="import"` (default) case and doesn't change anything in the `run-as="external"` case. From your comments in #1963, the down sides I see for -Tlevel:high are

- https://saxonica.plan.io/issues/6467 about `xsl:merge`. It is on track to be fixed in a future Saxon release, although that could be months away.
- "using Tlevel:high can cause Saxon to fail". Even if we think `xsl:merge` is not commonly used, there is still a possibility that a hard error from Saxon with -Tlevel-high can happen in cases not represented in our test suite here.
- The effort needed to make the XSpec trace listener pass the trace level to Saxon. You have probably already done some of the work, at least at a prototype level.

If we pursue -Tlevel:high, I think we should provide a mechanism<sup>1</sup> for a user who runs into a Saxon failure to work around the issue. The mechanism could be whatever requires low development effort (environment variable, maybe?).

Cc: @cmarchand , @xspec/xspec - if you're listening, feel free to jump into the discussion.

---
<sup>1</sup> Possibly undocumented or documented as "experimental", especially if we're fairly confident that failures would be infrequent for users

**Comment by birdya22** [comment]
Sorry about the zip file.
I forgot to say that I changed my local copy of `xsl-merge-01.xspec` to add `catch="yes"` into the scenario.

[TlevelHighExample.zip](https://github.com/user-attachments/files/16282620/TlevelHighExample.zip)

> If we pursue -Tlevel:high, I think we should provide a mechanism1 for a user who runs into a Saxon failure to work around the issue. The mechanism could be whatever requires low development effort (environment variable, maybe?).

It will need to be set as a command line parameter (there is no mechanism to set it in a config file).
It cannot be set twice e.g. once by XSpec and once by the user via `%SAXON_CUSTOM_OPTIONS%`  because Saxon complains with `Command line option -Tlevel appears more than once` (at least when running via a .bat file).

**Comment by galtm** [comment]
Thanks, I got the new ZIP-file and I see its three folders.

> It will need to be set as a command line parameter (there is no mechanism to set it in a config file).

I should have also mentioned that there are a few entry points to consider: .bat file, corresponding .sh file, and Ant. There are additional documented ways to run XSpec tests (like Maven and XProc) but I don't actually know if they support generating code coverage reports.

**Comment by birdya22** [comment]
One thing I had forgotten about was the fact that XSpec supports multiple versions of Saxon. For code coverage the range is very limited: [Code Coverage page in the Wiki](https://github.com/xspec/xspec/wiki/Code-Coverage) says "Starting in XSpec v3.0: Code coverage requires Saxon 12.4 or later."
It does mean that the `GetLocation()` method from the Saxon 12.5 `AbstractTraceListener` needs to be copied into the `XSLTCoverageTraceListener` so that it works in Saxon 12.4 (a couple of `import` statements are also required:

```
- import net.sf.saxon.expr.parser.XPathParser;
- import net.sf.saxon.tree.AttributeLocation;
```
The reason for mentioning this is that as part of a prototype to test `-Tlevel` in a `TraceListener` I was using `extends AbstractTraceListener` and just calling `GetLocation()` in the `AbstractTraceListener` and didn't need to copy it into my TraceListener..

**Comment by galtm** [comment]
Good point. I had been wondering if `getLocation` was good, bad, or neutral with Saxon 12.4, but hadn't gotten around to checking. I just tried it today with the end-to-end coverage tests and am seeing these lines of the HTML report changing from "missed" to "hit":

```
- xsl-evaluate-01.xsl line 20, xsl:evaluate with no child nodes
- xsl-map-01.xsl line 20, xsl:map-entry with no child nodes
- xsl-on-empty-01.xsl line 10, xsl:on-empty with no child nodes
- xsl-on-non-empty-01.xsl lines 11, xsl:on-non-empty with no child nodes; also line 28, xsl:sequence with no child nodes
- xsl-try-01.xsl, lines 11, 24, 30, all xsl:try with select attribute
- xsl-where-populated-01.xsl, lines 27-28. Now `xsl:perform-sort` with select attribute is marked "hit" instead of "missed", causing its parent `xsl:where-populated` to be marked "hit" instead of "unknown".
```

All look like good changes. There are some other coverage data files that changed but the HTML reports are the same, at least under the current code base. In at least one of the cases, the special-case rule for `xsl:variable` descendants (to be adjusted with #1978) is masking a "missed" status value that `getLocation` would change to "hit". Those changes in coverage data files also look good, either changing columnNumber="0" to a positive number or changing an incorrect positive number to a correct one.

Using `getLocation` might have a ripple effect on the list of "untraceable" elements as far as the Use Child/Descendant Data rule goes. Actually, the list of untraceable elements will probably differ between 12.4 and 12.5.

**Comment by galtm** [comment]
I created a separate issue, #1982, for `-Tlevel:high` so that if we add `getLocation` in a pull request that closes this issue, the other issue will remain open for the trace level investigation.

Sorry to say I haven't had a chance to look at your ZIP-file yet. I hope to do so in the coming week.
