### ISSUE TITLE
retrieve Saxon processor from Maven repository

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#20]
Following discussions with @tofi86 in https://github.com/xspec/xspec/commit/7303f0dce788fd8d0e091705b261d4aa284e75d2#commitcomment-20062004 and #19, retrieve Saxon from a [Maven repository](https://mvnrepository.com/artifact/net.sf.saxon/Saxon-HE/9.7.0-14) instead of uploading the binaries in XSpec. Change the .travis configuration and check with @tofi86 before committing the change to branch master.

**Comment by cirulls** [comment]
@tofi86: I implemented this in branch develop. I removed the saxon jar file and retrieved it directly from the maven repository inside the [.travis.yml](https://github.com/xspec/xspec/blob/develop/.travis.yml), see the changes in https://github.com/xspec/xspec/pull/22/files.

Could you confirm this does not break your builds? As soon as you confirm I will merge the change into the master branch. 

Thanks,

Sandro

**Comment by cirulls** [comment]
@tofi86: could you confirm this is fine with you so that I can merge the code into the master branch?

**Comment by tofi86** [comment]
I try to have a look tomorrow!

**Comment by tofi86** [comment]
Sorry, haven't had any time yesterday...

As far as I see from https://github.com/xspec/xspec/pull/22/files#diff-354f30a63fb0907d4ad57269548329e3 I have to change my travis build file to pull saxon from maven. Either the way you did it or any other way/version...
Think this only makes sense for me with testing when you merged it to master, right?

I would also suggest to update the README file or any other build instructions that users who just download the repo to use it locally have to install a saxon binary in the defined directory...

**Comment by cirulls** [comment]
Yep, I'll merge the change into master towards the end of this week as I won't have time to work on XSpec before then. I'll alert you when it's done so you can amend your configuration. 

Regarding the Saxon dependency, I think it is clearly explained in the [installation instructions on the wiki](https://github.com/xspec/xspec/wiki/Installation-on-Mac-and-Linux) but I can certainly review the README page and add it there, it's pretty important otherwise XSpec won't work.

**Comment by cirulls** [comment]
@tofi86 : I merged the changes into branch master, see the configuration in [.travis.yml](https://github.com/xspec/xspec/blob/master/.travis.yml). Let me know if this works for you, thanks.

**Comment by tofi86** [comment]
yep, it works! thanks! 👍

**Comment by cirulls** [comment]
Thanks for confirming, I'll close the issue.
