### ISSUE TITLE
Lack of support for testing text output produced by Schematron property elements

### ISSUE THREAD

**Issue by birdya22** [xspec/xspec#2044]
I've noticed that XSpec doesn't support testing the text content of Schematron `properties` in the output produced by an `assert` or `report` (unlike `diagnostics` output).

The [Writing Scenarios for Schematron](https://github.com/xspec/xspec/wiki/Writing-Scenarios-for-Schematron) Wiki page has the following, which looks like `property` output is specifically excluded: "Starting in XSpec v3.0.3, the `x:expect-assert` and `x:expect-report` elements can also have text content that identifies an expected `assert` or `report` by its message or diagnostic."

Is there a reason for this?

**Comment by galtm** [comment]
The text support in XSpec v3.0.3 was a response to feature request #1634. That issue didn't mention properties and when working on the support for #1634, I didn't think about whether properties should be in scope or not.

Are you requesting support for `properties`/`property` as described in https://schematron.com/home/whyisschematrondifferent_.html#fragment-9-toc-16 ? If so, is there anything else you'd like to share about your use case that might help with the design or prioritization?

Cc: @AndrewSales

**Comment by galtm** [comment]
I like your idea of supporting the testing of property text in a way similar to testing diagnostic text and message text.

_Possible alternative:_ I considered whether the support for testing properties should be different from the support for testing diagnostics. From Erik Siegel's [Schematron book](https://xmlpress.net/publications/schematron/), I get the impression that diagnostics are like alternative messages for end users, while properties are more for arbitrary post-processing of SVRL validation results (possibly to benefit someone other than owners of the documents being validated). _Maybe_ in properties used for post-processing, descendant elements are important and the string value isn't what's most worthwhile to test. However, after consideration, I feel inclined to keep the simple things simple (see Example 1).

XSpec users can always use `x:expect` to test properties in more flexible ways (see Example 2).

### Example 1

If we enhance XSpec to handle properties and diagnostics in a similar manner, then a text-oriented Schematron property like

```
<sch:property id="prop-simple">String value of
this property</sch:property>
```

would be testable with a simple XSpec element that isn't fussy about whitespace.

```
<x:expect-assert>String value of this property</x:expect-assert>
<!-- or -->
<x:expect-assert>
  String value of this property
</x:expect-assert>
```

### Example 2

A more data-centric Schematron property like

```
<sch:property id="prop-data">
    <user-data>
        <elem1 id="id1">user content</elem1>
        <elem2 id="id2">More user content</elem2>
    </user-data>
</sch:property>
```

is testable with `<x:expect>`, even without an XSpec enhancement:

```
<x:expect label="prop-data captured with SchXslt (Note: Fails in skeleton implementation)"
    test="//svrl:failed-assert/svrl:property-reference[@property='prop-data']"
    as="element(svrl:property-reference)">
    <svrl:property-reference property="prop-data">
        <svrl:text>
            <user-data>
                <elem1 id="id1">user content</elem1>
                <elem2 id="id2">More user content</elem2>
            </user-data>
        </svrl:text>
    </svrl:property-reference>
</x:expect>
```

Note that the skeleton implementation of Schematron uses different SVRL markup, and the `<x:expect>` element would look like this:

```
<x:expect label="prop-data captured with skeleton (Note: For skeleton only; fails in SchXslt)"
    test="//svrl:failed-assert/svrl:property[@id='prop-data']"
    as="element(svrl:property)">
    <svrl:property id="prop-data">
        <user-data>
            <elem1 id="id1">user content</elem1>
            <elem2 id="id2">More user content</elem2>
        </user-data>
    </svrl:property>
</x:expect>
```

**Comment by dmj** [comment]
+1 from me as well. The discrepancy between SchXslt and Skeleton is due to a different interpretation of the SVRL grammar in Annex D. 

I raised https://github.com/Schematron/schematron-enhancement-proposals/issues/79 to clarify.
