### ISSUE TITLE
runner script for XSpec test suite does not detect compiling issues

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#21]
@tofi86 wrote in #19

> The example bash script described on the Travis Wiki page
> 
> ```bash
> for xspectest in *.xspec; 
>     do ../bin/xspec.sh $xspectest &> result.log; 
>     if grep -q ".*failed:\s[1-9]" result.log || grep -q "*\sError\srunning\sthe\stest\ssuite" result.log; 
>         then echo "$xspectest failed" && exit 1; 
>         else echo "ok $xspectest";
>     fi  
> done
> ```
> 
> did not properly detect compiling issues (e.g. when Saxon is not available at the given path).
> 
> I updated the wiki entry with better detection:
> 
> ```bash
> for xspectest in *.xspec;
>     do ../bin/xspec.sh $xspectest &> result.log;
>     if grep -q ".*failed:\s[1-9]" result.log || grep -q -E "\*+\sError\s(running|compiling)\sthe\stest\ssuite" result.log;
>         then echo "FAILED: $xspectest" && exit 1;
>         else echo "OK: $xspectest";
>     fi
> done
> ```

Apply the change to [run-xspec-tests.sh](https://github.com/xspec/xspec/blob/master/test/run-xspec-tests.sh)

**Comment by cirulls** [comment]
@tofi86: I added the feature to make XSpec tests fail for both running and compilation errors and mentioned you as co-author in the script. Your change allowed me to spot a compilation issue in the test suite that got unnoticed so far, I amended the test in [unit-expect-xsl.xspec](https://github.com/xspec/xspec/test/unit-expect-xsl.xspec). This is also part of the tests I need to rewrite for #4.

**Comment by tofi86** [comment]
Perfect, thanks! :)
