### ISSUE TITLE
Document catalog option

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#213]
wiki needs to be updated as described in #172

**Comment by cirulls** [comment]
Thanks @vincentml for creating this documentation ticket. It would be good to mention in the documentation that the XML resolver should be named `xml-resolver-1.2.jar` (see https://github.com/xspec/xspec/pull/172#pullrequestreview-108680238). I was one of those that downloaded the XML resolver from [here](https://xerces.apache.org/xml-commons/) and had to rename it.

**Comment by vincentml** [comment]
I've created a [XML Catalog support](https://github.com/xspec/xspec/wiki/XML-Catalog-support) page in the documentation and updated the [Environment Variables](https://github.com/xspec/xspec/wiki/Environment-Variables) page. 

I'm leaving this ticket open for now as a reminder to remove the line that contains "will be available in XSpec version 1.1.0" after the official release.

**Comment by AirQuick** [comment]
Thanks for the clear documentation!

I added a link to an Ant doc in the [XML Catalog support](https://github.com/xspec/xspec/wiki/XML-Catalog-support#using-an-xml-catalog-with-ant) page. Also made cosmetic edits in the [Environment Variables](https://github.com/xspec/xspec/wiki/Environment-Variables) page.

**Comment by cirulls** [comment]
> I'm leaving this ticket open for now as a reminder to remove the line that contains "will be available in XSpec version 1.1.0" after the official release.

@vincentml : I've just [released v1.1.0](https://github.com/xspec/xspec/releases/latest). As you wrote back in July, could you please update that line on the [wiki page for XML Catalog support](https://github.com/xspec/xspec/wiki/XML-Catalog-support)?

**Comment by vincentml** [comment]
@cirulls I've updated the wiki.
