### ISSUE TITLE
Problem testing a template inside a XSLT, which is the output of the current XSLT

### ISSUE THREAD

**Issue by divStar** [xspec/xspec#225]
Hello,

I am not sure whether my problem has something to do with this issue, but it seems so.

I have the following example:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:gen="dummy-namespace-for-the-generated-xslt" xmlns:avx="allegro-avx">
	<xsl:namespace-alias stylesheet-prefix="gen" result-prefix="xsl"/>

	<xsl:template match="/">
		<gen:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions">
			<gen:output method="xml" encoding="ISO-8859-1"/>
			<gen:template name="buildLink">
				<gen:param name="link"/>
				<gen:param name="linkValue"/>
				<gen:param name="pos"/>
				<a href="{{$link}}#{{number($pos) - 1}}">
					<gen:value-of select="{'$linkValue'}"/>
				</a>
			</gen:template>
		</gen:stylesheet>
	</xsl:template>
</xsl:stylesheet>
```

**I cannot seem to find a way to test the template "buildLink"**, because it has a different namespace, but no matter what I try, it does not seem to find the template when I use <x:call template="buildLink">...</x:call>. Note the namespace-alias - perhaps that's the deal breaker?

The XSpec I am writing:
```
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:avx="allegro-avx" xmlns:gen="dummy-namespace-for-the-generated-xslt" stylesheet="dl2genmini.xsl" version="1">
  <x:scenario focus="The only test causing trouble" label="Trying to execute a named template">
    <x:call template="buildLink" xmlns:gen="dummy-namespace-for-the-generated-xslt">
      <x:param name="link" select="'http://www.a.b.c.de'" />
      <x:param name="linkValue" select="'SomeLink'" />
      <x:param name="pos" select="1" />
    </x:call>
    <x:expect>
      <a href="{{http://www.a.b.c.de}}#{{number(1) - 1}}">
        <gen:value-of select="{'SomeLink'}" />
      </a>
    </x:expect>
  </x:scenario>
</x:description>
```

Note, that the XSLT as well as the test is shortened, but it does not work either way (even with this shortened version). Is there a way to somehow test the "buildLink"-template? Is it my fault? Is it a bug? Or is it a limitation?

**Comment by cirulls** [comment]
Thanks @divStar for asking (it may be useful for other people too) and thanks @AirQuick for replying with an example. @divStar, did you manage to try it? Are you happy with the reply so that we close this issue? Thanks!

**Comment by divStar** [comment]
Thank you very much for your help @AirQuick,
your suggestion worked out for me.

I had to generate the inner XSLT using the xml-maven-plugin inside the pom.xml file before I run the XSpec-Tests. This way I could ensure to always have the most up-to-date version of the inner XSLT for testing purposes, which is way better than having some static inner-XSLT, because eventual changes on the inner XSLT might not show up otherwise.

Essentially I did the following:
```
<build>
	...
	<plugins>
		...
		<plugin>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>xml-maven-plugin</artifactId>
			<version>1.0.2</version>
			<executions>
				<execution>
					<id>generate-gen</id>
					<phase>process-test-resources</phase>
					<goals>
						<goal>transform</goal>
					</goals>
				</execution>
			</executions>
			<dependencies>
				<dependency>
					<groupId>net.sf.saxon</groupId>
					<artifactId>Saxon-HE</artifactId>
					<version>9.8.0-12</version>
				</dependency>
			</dependencies>
			<configuration>
				<forceCreation>true</forceCreation>
				<transformationSets>
					<transformationSet>
						<dir>${transform.source.dir}</dir>
						<includes>
							<include>${transform.source.dummy-xml}</include>
						</includes>
						<outputDir>${transform.target.dir}</outputDir>
						<fileMappers>
							<fileMapper implementation="org.codehaus.plexus.components.io.filemappers.MergeFileMapper">
								<targetName>${transform.target.xslt}</targetName>
							</fileMapper>
						</fileMappers>
						<stylesheet>${transform.source.xslt}</stylesheet>
						<!-- Insert parameters for the stylesheet here (if required) -->
						<parameters>...</parameters>
					</transformationSet>
				</transformationSets>
			</configuration>
		</plugin>
	</plugins>
</build>
```
This transforms my "outer" XSLT into the desired "inner" XSLT using a dummy-xml. Then I just have the xspec-maven-plugin in the test-phase run over this generated XSLT as well. This works flawlessly.

Thanks again, guys. Great work you are doing here :+1: !

P.s.: @cirulls : if you want, you may close the ticket (I do not know if I am supposed to do so myself).

**Comment by cirulls** [comment]
Thanks for posting your solution too, it may be useful to other people. Feel free to come back here if you need help or if you'd like to contribute to XSpec. I'm closing this issue.
