### ISSUE TITLE
Cannot compare whole documents

### ISSUE THREAD

**Issue by tofi86** [xspec/xspec#227]
Hi,

I tried to use XSpec to compare a whole document with an expected result but have multiple issues.
This is my setup:

<details>
 <summary>article.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://docbook.org/xml/5.0/rng/docbook.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://docbook.org/xml/5.0/rng/docbook.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<article xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" version="5.0">
	<info>
		<title>A Short Introduction To XSpec</title>
	</info>
	<sect1>
		<title>A short introduction to the XSpec Unit Testing Framework</title>
		<para>XSpec is a unit test and <link xlink:href="http://en.wikipedia.org/wiki/Behavior_Driven_Development">behaviour driven development</link> (BDD) framework for XSLT, XQuery and Schematron. It is based on the Spec framework of <link xlink:href="http://rspec.info/">RSpec</link>, which is a BDD framework for Ruby.</para>
		<para>XSpec consists of a syntax for describing the behaviour of XSLT or XQuery code and some code that enables to test the code against those descriptions.</para>
		<sect2>
			<title>Getting Started</title>
			<para>To get started, check out the installation instructions for <link xlink:href="https://github.com/xspec/xspec/wiki/Installation-on-Mac-and-Linux">MacOS/Linux</link> and <link xlink:href="https://github.com/xspec/xspec/wiki/Installation-on-Windows">Windows</link> and how to <link xlink:href="https://github.com/xspec/xspec/wiki/Getting-Started">write your first XSpec test</link>.</para>
		</sect2>
		<sect2>
			<title>Support</title>
			<para></para>
		</sect2>
	</sect1>
</article>
```
</details>

<details>
 <summary>article-to-html.xsl</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.w3.org/1999/xhtml"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:math="http://www.w3.org/2005/xpath-functions/math"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:pa="https://www.pagina.gmbh"
	exclude-result-prefixes="xs math xlink pa"
	xpath-default-namespace="http://docbook.org/ns/docbook"
	version="3.0">
	
	<xsl:output method="xhtml" encoding="UTF-8" indent="yes" html-version="5.0"/>
	
	
	<xsl:template match="/">
		<xsl:apply-templates/>
	</xsl:template>
	
	<xsl:template match="article">
		<html>
			<head>
				<xsl:apply-templates select="info"/>
			</head>
			<body>
				<xsl:apply-templates select="* except info"/>
			</body>
		</html>
	</xsl:template>
	
	<xsl:template match="info/title">
		<title>
			<xsl:apply-templates/>
		</title>
	</xsl:template>
	
	<xsl:template match="info/author"/>
	
	<xsl:template match="sect1 | sect2">
		<section>
			<xsl:apply-templates/>
		</section>
	</xsl:template>
	
	<xsl:template match="sect1/title">
		<h1>
			<xsl:apply-templates/>
		</h1>
	</xsl:template>
	
	<xsl:template match="sect2/title">
		<h2>
			<xsl:apply-templates/>
		</h2>
	</xsl:template>
	
	<xsl:template match="para">
		<p>
			<xsl:apply-templates/>
		</p>
	</xsl:template>
	
	<xsl:template match="link">
		<a href="{@xlink:href}">
			<xsl:apply-templates/>
		</a>
	</xsl:template>
	
</xsl:stylesheet>
```
</details>

This is what oXygen 20 (Saxon 9.8.0_8) produces as output:

<details>
 <summary>article_expected.html</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
      		
      <title>A Short Introduction To XSpec</title>
      		
      	
   </head>
   <body>
      <section>
         		
         <h1>A short introduction to the XSpec Unit Testing Framework</h1>
         		
         <p>XSpec is a unit test and <a href="http://en.wikipedia.org/wiki/Behavior_Driven_Development">behaviour driven development</a> (BDD) framework for XSLT, XQuery and Schematron. It is based on the Spec framework
            of <a href="http://rspec.info/">RSpec</a>, which is a BDD framework for Ruby.
         </p>
         		
         <p>XSpec consists of a syntax for describing the behaviour of XSLT or XQuery code and
            some code that enables to test the code against those descriptions.
         </p>
         		
         <section>
            			
            <h2>Getting Started</h2>
            			
            <p>To get started, check out the installation instructions for <a href="https://github.com/xspec/xspec/wiki/Installation-on-Mac-and-Linux">MacOS/Linux [SECURE LINK]</a> and <a href="https://github.com/xspec/xspec/wiki/Installation-on-Windows">Windows [SECURE LINK]</a> and how to <a href="https://github.com/xspec/xspec/wiki/Getting-Started">write your first XSpec test [SECURE LINK]</a>.
            </p>
            		
         </section>
         		
         <section>
            			
            <h2>Support</h2>
            			
            <p></p>
            		
         </section>
         	
      </section>
   </body>
</html>
```
</details>

Then I wrote an XSpec scenario to compare actual transformation result with expected result from oXygen:

<details>
 <summary>article-to-html.xspec</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec"
	stylesheet="article-to-html.xsl">
	
	<x:scenario label="The integration test output">
		<x:context href="article.xml"/>
		<x:expect label="should match the expected result." href="article.html"/>
	</x:scenario>
	
</x:description>
```
</details>

First of all: the results do not match:

![bildschirmfoto 2018-07-24 um 12 41 58](https://user-images.githubusercontent.com/365118/43133427-01eebf88-8f3f-11e8-8677-12426dc1ab65.png)

Obviously it's because of the indentation which is different when the XSpec framework transforms the data.

However, if I remove the `indent="yes"` or change to "no", it doesn't get any better.

Second: The `method="xhtml"` produces a `<meta>` element in oXygen which is totally missing in the XSpec result, as you can see on the screenshot.

Third: If I change the output declaration to `<xsl:output encoding="UTF-8" indent="no" method="xml"/>` the XSpec result seems to match the expected result from oXygen, all highlights in the HTML report are green, but the test fails anyway:

![bildschirmfoto 2018-07-24 um 12 47 28](https://user-images.githubusercontent.com/365118/43133715-e7d77e54-8f3f-11e8-84ac-5f6dc4bb29fc.png)

This seems like a bug to me.

Fourth: When looking at the XML report, there are lots of empty `<test:ws xmlns:pkg="http://expath.org/ns/pkg">` elements which seem to be irrelevant and should be removed, right?

----

How can both of these issues be resolved?

How can I compare whole documents as kind of an "integration test"?

Thanks,
Tobias

**Comment by AirQuick** [comment]
You expect that a serialized result is equal to another serialized doc when both are parsed again.
So you need to actually serialize the result and parse it. How about this?
```xml
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec"
	stylesheet="article-to-html.xsl" xslt-version="3.0">
	
	<x:scenario label="The integration test output">
		<x:context href="article.xml"/>
		<x:expect label="serelized result should match the expected result when parsed" href="article_expected.html"
			test="
				serialize(
					.,
					map {
						'method': 'xhtml',
						'indent': true(),
						'html-version': 5.0
						}
					)
				=> parse-xml()"/>
	</x:scenario>
	
</x:description>
```

**Comment by AirQuick** [comment]
> <test:ws xmlns:pkg="http://expath.org/ns/pkg"> elements which seem to be irrelevant and should be removed, 

`test:ws` represents a non-ignorable whitespace-only text node. (`xmlns:pkg` is just a garbage.)
For how whitespace-only text nodes are ignored or recognized in XSpec, see `xspec-space.xspec` in #179.
Every `x:expect` there results in Success.

**Comment by AirQuick** [comment]
> Third: If I change the output declaration to <xsl:output encoding="UTF-8" indent="no" method="xml"/> ...

Note that in your screenshot, the right-hand **Expected Result** has `XPath / from` while the left-hand **Result** doesn't. It suggests that the expected result is a document node while the actual result is an element. So they are different items and the test must be Failure.

You should either fix the stylesheet to produce a document node
```xml
<xsl:template match="/">
    <xsl:document><xsl:apply-templates/></xsl:document>
</xsl:template>
```
*or* fix `x:expect` to select an outermost element in the document loaded by `@href`
```xml
<x:expect label="should match the expected element." href="article_expected.xml" select="element()"/>
```
whichever meets your actual goal.

**Comment by tofi86** [comment]
Hi, thanks for your replies @AirQuick!

Regarding your latest comment:

I wasn't aware of the `<xsl:template match="/">` template, must have been there by mistake 🙈 

However, I also didn't knew, that without a root template with a `<xsl:document>` a transformation creates an `element()` node by default and not a `document()`.

Removing the root remplate and using `select="element()"` on the `<x:expect>`-Element works fine. Thanks.

Now the next step is to take a closer look at the serialized results.

Thanks, Tobias

**Comment by tofi86** [comment]
> You expect that a serialized result is equal to another serialized doc when both are parsed again.
> So you need to actually serialize the result and parse it. How about this?

Unfortunately, this doesn't work for me. The "result" is always empty `()` and it seems to be an issue with the XSLT 3 `serialize()` function. If I just use `test="."` the result is available but doesn't match the expected XML. As soon as I use `test=". => serialize(...) => parse-xml()` the result gets empty `()`.

Any ideas?

**Comment by tofi86** [comment]
> As soon as I use `test=". => serialize(...) => parse-xml()` the result gets empty `()`.
> 
> Any ideas?

Okay, this seems to be an issue with the serialization parameter `'html-version' = 5.0`. If I leave this out, the results match and the tests succeed. Although I have set `html-version="5.0"` in my XSLT... 🤷‍♂️

**Comment by AirQuick** [comment]
What is your Saxon edition and version? My example worked on Saxon-EE 9.8.0.12 and 9.8.0.14 on my end.

**Comment by AirQuick** [comment]
Looks like Saxon `fn:serialize()` is not good at handling `html-version` until recently:
* https://saxonica.plan.io/issues/3746
* https://saxonica.plan.io/issues/3781

**Comment by tofi86** [comment]
I was running Saxon-HE 9.8.0.7. Now I'm using 9.8.0.14 and it works with the serialization parameter `'html-version'`. Thanks!

**Comment by tofi86** [comment]
Next question: Is it somehow possible to 

a) ignore indentation whitespace or any other whitespace differences when comparing the result document and expected document?

b) ignore certain special elements within a document? (e.g. a timestamp element)?

**Comment by tofi86** [comment]
Regarding b) I was able to come up with the following solution to only compary partial trees of result and expected:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec"
  xmlns:html="http://www.w3.org/1999/xhtml"
  stylesheet="../xslt/docbook-to-html-serialized.xsl" xslt-version="3.0">
  
  <x:scenario label="The integration test">
    <x:context href="demo2/article.xml"/>
    <x:expect label="should match the expected result." href="demo2/article.html" select="/html:html/html:body"
      
      test="
      /html:html/html:body
      => serialize(
        map {
          'method': 'xhtml',
          'indent': true(),
          'html-version': 5.0
        }
      )
      => parse-xml()"/>
  </x:scenario>
  
</x:description>
```

But it only works partially.

<img width="1244" alt="bildschirmfoto 2018-07-26 um 15 46 55" src="https://user-images.githubusercontent.com/365118/43266244-2e7ae95c-90eb-11e8-925f-137dde1fe905.png">

The expected result (via `select=""` attribute) is treated as document node despite selecting an element, and the result is treated as element() although the `parse-xml()` function should return a document node. I got stuck here. Any idea?

**Comment by AirQuick** [comment]
I think what you really extract from the actual result is this `@test`:
```xml
    <x:expect label="/html/body should match the expected result."
      href="demo2/article.html"
      select="/html:html/html:body"
      test="
      (
          .
          => serialize(
            map {
              'method': 'xhtml',
              'indent': true(),
              'html-version': 5.0
            }
          )
          => parse-xml()
      )/html:html/html:body"/>
```

**Comment by AirQuick** [comment]
> b) ignore certain special elements within a document? (e.g. a timestamp element)?

The three dot feature mentioned in [Wiki](https://github.com/xspec/xspec/wiki/Writing-Scenarios#expectations) could help to some extent. I'm not aware of a built-in feature beyond that.

When I have to verify complicated thing, I usually write a wrapper XSLT. For example, if I have to test `actual.xsl` and if it's difficult to test the outcome in XSpec directly, I would write:

**wrapper.xsl**
```xml
<xsl:stylesheet xmlns:my="my">
    <!-- Test target -->
    <xsl:include href="../src/actual.xsl" />

    <!-- Test helper -->
    <xsl:function name="my:test-filter" as="node()">
        <xsl:param name="input-node" as="node()" />
        
        <!-- do whatever filtering on $input-node and return the filtered node -->
    </xsl:function>
</xsl:stylesheet>
```

**test.xspec**
```xml
<x:description stylesheet="wrapper.xsl" xmlns:my="my">
    <x:scenario>
        <x:context>foo...</x:context>
        <x:expect test="my:test-filter($x:result)">bar..</x:expect>
    </x:scenario>
</x:description>
```

This usually works for me, although I might have a bug in `my:test-filter`... :grin:

**Comment by tofi86** [comment]
Awesome! 👏  Both of these solutions work very well!

I totally forgot about the "three dot" feature ;-)

**Comment by tofi86** [comment]
Alright, that sounds reasonable.

Thanks a lot for your support, @AirQuick!

We did a team training for XSpec and I think we will come up with a couple of changes and additions to the wiki docs. Stay tuned.

Best, Tobias

**Comment by AirQuick** [comment]
> test:ws represents a non-ignorable whitespace-only text node. (xmlns:pkg is just a garbage.)

The garbage `xmlns:pkg` is removed by #338.
