### ISSUE TITLE
XInclude in <x:expect> not resolved

### ISSUE THREAD

**Issue by tofi86** [xspec/xspec#231]
Seems that XIncludes in `<x:expect>` are not resolved.

Tried that as an alternative solution to #227 but 

```
<x:expect label="should match the expected result.">
	<xi:include href="demo1/article.html"/>
</x:expect>
```
the XInclude is just parsed as a normal element.

**Comment by AirQuick** [comment]
This is by design at the moment.

**Comment by AirQuick** [comment]
#1128 supports this.

Usage is demonstrated in tests:

- [Saxon config](https://github.com/xspec/xspec/blob/28d56244de2fc313f91b0a3ec8c17e8ed1405a2b/test/compiler-saxon-config/config.xml)
- [Ant command line](https://github.com/xspec/xspec/blob/28d56244de2fc313f91b0a3ec8c17e8ed1405a2b/test/xspec.bats#L1534-L1556)
