### ISSUE TITLE
test fails when comparing values with a sequence

### ISSUE THREAD

**Issue by duenckel** [xspec/xspec#232]
_XSLT_

```xml
<xsl:function name="t:giveMeASequence">
    <xsl:sequence select="('a', 'b', 'c')" />
</xsl:function>
```
_XSPEC_

```xml
<x:scenario label="The sequence ('a','b','c') ...">
    <x:call function="t:giveMeASequence"/> 
    <x:expect label="contains the atomic value 'a'" test=".='a'" />
</x:scenario>
```

Report

```
Failure
    Result: ('a', 'b', 'c')
    Expected Result: ()
```

Using the same node test in a stylesheet returns true

**Comment by AirQuick** [comment]
If the function returns a sequence of nodes, `x:expect` wraps the sequence in a document node and evaluates `@test` expression in the context of the document node.
But your function returns a sequence of xs:string, so `x:expect` evaluates `@test` expression in an undefined context. So accessing `.` in `@test` does not make sense in that case.
You can use `$x:result`:
```xml
<x:expect label="contains the atomic value 'a'" test="$x:result='a'" />
```
See [Writing Scenarios](https://github.com/xspec/xspec/wiki/Writing-Scenarios#expectations) for details.

**Comment by duenckel** [comment]
Thank you for your help!
It works perfectly.
