### ISSUE TITLE
why does <xsl:value-of> not return a string

### ISSUE THREAD

**Issue by duenckel** [xspec/xspec#233]
_XSLT_

```xml
<xsl:function name="t:parentName">
    <xsl:param name="current-node"/>
    <xsl:value-of select="$current-node/../name()"/>
</xsl:function>
```

_XSPEC_

```xml
<x:scenario label="parent of 'b'">
    <x:call function="t:parentName">
        <x:param name="current-node" select="/a/b">
            <a><b/></a>
        </x:param>
    </x:call>
    <x:expect label="is 'a'" select="'a'"/>
</x:scenario>
```

_Result_
```
Failed
    Expected: a
    Result: 'a'
```

_XSLT 2.0 Rec_

> The xsl:value-of instruction is evaluated to construct a new text node; the result of the instruction is the newly constructed text node.
>The string value of the new text node may be defined [...] by using the select attribute

https://www.w3.org/TR/xslt20/#value-of

----

I already found out that this problem does not occur if I use <xsl:copy-of>, or type the return value of the function as xs:string. 
However, I want to understand why <xsl:value-of> does not create a string.

**Comment by AirQuick** [comment]
Your function returns a text node and your `x:expect` expects an xs:string. They are different items. So the test result is a failure.

You can either make the function return an xs:string
```xml
<xsl:function name="t:parentName" as="xs:string">
```

*or* make `x:expect` expect a text node

```xml
<x:expect label="is a text node of 'a'">a</x:expect>
```

whichever meets your intention.

**Comment by duenckel** [comment]
Thank you for your help!
It works perfectly.
