### ISSUE TITLE
xspec.bat: coverage does not work on Windows

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#25]
With the latest master running on Windows, xspec.bat does not work at all for coverage:
```
C:\xspec>bin\xspec.bat tutorial\escape-for-regex.xspec coverage
Creating XSpec Directory at "C:\xspec\tutorial\xspec" ...

Creating Test Stylesheet...
"C:\xspec\tutorial\xspec\escape-for-regex.xsl"
tutorial\escape-for-regex.xspec

Running Tests...
Collecting test coverage data; suppressing progress report...
Transformation failed: Failed to load com.jenitennison.xslt.tests.XSLTCoverageTraceListener
Testing with SAXON EE 9.7.0.14
No escaping
Must not be escaped at all
Test simple patterns
..When encountering parentheses
escape them.
..When encountering a whitespace character class
escape the backslash
result should have one more character than source
When processing a list of phrases
All phrase elements should remain
Strings should be escaped and status attributes should be added
      FAILED

Formatting Report...
passed: 5 / pending: 0 / failed: 1 / total: 6
Error on line 1 column 1 of escape-for-regex-coverage.xml:
  SXXP0003: Error reported by XML parser: Content is not allowed in prolog.
org.xml.sax.SAXParseException; systemId: file:/C:/xspec/tutorial/xspec/escape-for-regex-coverage.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
'"C:\xspec\tutorial\xspec\escape-for-regex-coverage.html"' is not recognized as an internal or external command,
operable program or batch file.
Report available at "C:\xspec\tutorial\xspec\escape-for-regex-result.html"
Done.
C:\xspec>
```
Problems:
* XSLTCoverageTraceListener not found
* Invalid command line wrap by \
* Coverage XML is not well-formed, due to a bytecode generation warning before `<trace>`
* **pwd** parameter is the bat file dir with backslash, when it should've been the current dir with the forward slash
* %COVERAGE_HTML% is supplied as a command line

**Comment by AirQuick** [comment]
To get it work, I needed to patch as follows:
```
--- master\xspec.bat    Sun Dec 11 07:55:23 2016
+++ work\xspec.bat      Sun Dec 11 08:29:06 2016
@@ -62,8 +62,7 @@
 GOTO endif3
 :coverage
 echo Collecting test coverage data; suppressing progress report...
- java -cp "%CP%" net.sf.saxon.Transform -T:com.jenitennison.xslt.tests.XSLTCoverageTraceListener       \
-     -o:%RESULT% -s:%XSPEC% -xsl:%TEST_STYLESHEET% -it:{http://www.jenitennison.com/xslt/xspec}main 2> %COVERAGE_XML%
+ java -cp "%CP%;%~dp0..\java" net.sf.saxon.Transform -T:com.jenitennison.xslt.tests.XSLTCoverageTraceListener -o:%RESULT% -s:%XSPEC% -xsl:%TEST_STYLESHEET% -it:{http://www.jenitennison.com/xslt/xspec}main --generateByteCode:off 2> %COVERAGE_XML%

 :endif3

@@ -82,8 +81,9 @@
 IF %COVERAGE%x == coveragex GOTO coverage2
 GOTO endif4
 :coverage2
- java -cp "%CP%" net.sf.saxon.Transform -l:on "-o:%COVERAGE_HTML%" "-s:%COVERAGE_XML%" "-xsl:%~dp0\..\src\reporter\coverage-report.xsl" "tests=%XSPEC%" "pwd=file:///%~dp0"
- %COVERAGE_HTML%
+ set PWD=%CD:\=/%/
+ java -cp "%CP%" net.sf.saxon.Transform -l:on "-o:%COVERAGE_HTML%" "-s:%COVERAGE_XML%" "-xsl:%~dp0\..\src\reporter\coverage-report.xsl" "tests=%XSPEC%" "pwd=file:///%PWD%"
+ echo Report available at %COVERAGE_HTML%
 :endif4

 REM =============
```

**Comment by cirulls** [comment]
@AirQuick, thanks for the patch, it's very much appreciated. That's correct, the code coverage is currently working only with the shell script (see #3). Could you submit the patch as a pull request on branch master? Could you also let me know with version of Windows you're using? I don't have a Windows machine at hand but I can simulate it on a Windows-like environment.

**Comment by AirQuick** [comment]
Two more problems:
* If you have JAVA_TOOL_OPTIONS set, the coverage XML is not well-formed.
* When coverage is enabled, the test runs twice; Once with coverage, again without coverage. The latter doesn't seem necessary.

Also, the current xspec.bat looks somewhat peculiar... particularly its chaining of IF GOTO.
So I would rather perform a semi refactoring. Do you think it's feasible at this time?

**Comment by cirulls** [comment]
It would be awesome if you can refactor the batch script and improve it, I must say I'm not experienced at all with Windows batch scripting. The batch script has not been extended for years and is lagging behind the shell script so it would be really useful to get feature parity between Windows/Linux/MacOs.

**Comment by AirQuick** [comment]
For the record, yet another problem.
* **tests** parameter for coverage-report.xsl does not work with absolute path

Thanks, @cirulls for inputting your thoughts. I have revised the batch file by imitating what the shell script is doing. In consequence it doesn't look like the original xspec.bat at all but resembles the shell script. So I'll submit it as a new file (xspec.cmd), in a few days.

**Comment by cirulls** [comment]
I look forward to see the script and try it out! It may be easier to call it xspec.bat as the current one so this won't break things for all the Windows users of XSpec.
