### ISSUE TITLE
Namespace issue and indentation issue while comparing whole document.

### ISSUE THREAD

**Issue by anuragguptagithub** [xspec/xspec#288]
Hello ,

My input is xml file(s) and expected result is also an xml file(s). The problem is that in the expected result we have namespace prefix being used, while in the result xml, there is no namespace prefix but every tag has xmlns="some-namespace". and this is resulting in failure of the test cases.

How can i solve this ?

![image](https://user-images.githubusercontent.com/28867358/44208559-f5594200-a160-11e8-978e-ced0898656de.png)

**Comment by AirQuick** [comment]
Closing now. Please feel free to reopen this with more details.
