### ISSUE TITLE
Wrong error message if x:expect has assert and test

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#31]
If you have
```xml
<x:expect assert="true()" label="Expect-1" test="true()" />
```

The latest master XSpec complains

```
Creating Test Stylesheet...
ERROR in scenario "Expect-1": can't have both @context and @test at the same time
```

In the message, `context` and `test` attributes are blamed. But actually x:expect has no `context` attribute.

**Comment by cirulls** [comment]
Thanks for reporting this issue, it may be a mismatch between the test conditions and the error message in the XSpec code. I'll have a look and keep you posted. Please allow me 7-10 days to get back to you as it is Christmas time.

**Comment by cirulls** [comment]
As confirmed by @AirQuick in https://github.com/xspec/xspec/issues/30#issuecomment-269759116, #38 made this issue obsolete so I close it.
