### ISSUE TITLE
Schema does not allow x:expect assert

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#32]
Looks like at some point `assert` and `context` attributes were invented for `x:expect`.
But the current schema (src\schemas\xspec.rnc) has not incorporated them yet.

**Comment by cirulls** [comment]
Thanks for reporting this issue, I'll have a look at the schema and see if they can be easily added. Please allow me 7-10 days to get back to you as it is Christmas time.

**Comment by cirulls** [comment]
As confirmed by @AirQuick in https://github.com/xspec/xspec/issues/30#issuecomment-269759116, #38 made this issue obsolete so I close it.
