### ISSUE TITLE
xspec.bats specifies -j option by accident?

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#39]
In xspec.bats, these test cases specify `-j` option:
* [`"invoking xspec generates XML report file"`](https://github.com/xspec/xspec/blob/706b4e6bafd338cbe45540d9757c90e82ac4848c/test/xspec.bats#L93)
* [`"invoking xspec generates HTML report file"`](https://github.com/xspec/xspec/blob/706b4e6bafd338cbe45540d9757c90e82ac4848c/test/xspec.bats#L100)

Are they really intentional? They don't appear so, because
* their `@test` messages do not mention `-j`
* [L93-96](https://github.com/xspec/xspec/blob/706b4e6bafd338cbe45540d9757c90e82ac4848c/test/xspec.bats#L93-L96) is a dup of [L132-135](https://github.com/xspec/xspec/blob/706b4e6bafd338cbe45540d9757c90e82ac4848c/test/xspec.bats#L132-L135)

**Comment by cirulls** [comment]
Thanks for spotting this. In fact, these tests should be testing that XSpec is generating the XML and HTML reports when it is executed without any option. The ```-j``` option was erroneous. I fixed this in #49. 

Could you please review #49 and approve it or request further changes? Thanks.

**Comment by cirulls** [comment]
#49 approved and code merged into `master`.
