### ISSUE TITLE
Move oXygen documentation from build.xml to Wiki

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#392]
How to replace the oXygen built-in XSpec is described in `build.xml`: https://github.com/xspec/xspec/blob/17cc79321011f4e4192e973f7109b39a5303ec6e/build.xml#L42-L57

For more flexibility, I think the description should be moved to Wiki. ([Running with Oxygen](https://github.com/xspec/xspec/wiki/Running-with-Oxygen) and/or [Running with Ant](https://github.com/xspec/xspec/wiki/Running-with-Ant))

---

As for the command-line usage, #266 transfers the responsibility to Wiki: https://github.com/xspec/xspec/blob/1513f23dd2efdf7fce57c6f76864ec3327648011/build.xml#L12-L14

**Comment by cirulls** [comment]
Thanks for raising this. I agree that the wiki is a better place to put the full documentation. A reference to the wiki in the `build.xml` as in #266 would be good.

**Comment by AirQuick** [comment]
Added a section in the Wiki [page](https://github.com/xspec/xspec/wiki/Running-with-Oxygen#running-the-latest-version-of-xspec-with-oxygen).

**Comment by cirulls** [comment]
Thanks, this is really useful and didn't know you could set it up like this in oXygen (I used to replace the code in `frameworks/xspec` for each new pull request I needed to test). I could set this up successfully using your documentation and will use this method for testing XSpec in oXygen from now.
