### ISSUE TITLE
[Event] A new Webinar about XSpec and unit testing XSLT and Schematron

### ISSUE THREAD

**Issue by AlexJitianu** [xspec/xspec#394]
Hello everybody,

I just wanted to let you know that we will host a new Webinar about XSpec in an effort to encourage Test Driven Development of XSLT and Schematron. We plan to present an overview of XSpec and how to take full advantage of the support Oxygen XML Editor has for XSpec. So, even if you already are an XSpec power user, chances are you can still learn a few tips and tricks about how Oxygen can help you write/execute/fix XSpec scenarios. If you know other persons that might be interested in learning a bit about XSpec or about working with XSpec in Oxygen, please spread the word.

The event will be hosted on October 10, 2018 at 11:00 AM US Eastern time. You can register for free at:
https://www.oxygenxml.com/events/2018/webinar_xspec_unit_testing_for_xslt_and_schematron.html
Even if you cannot attend, by registering, you will receive an email with a link to the recording of the event.

PS: I apologize for using GItHub's issue support to spread the word about this event but I couldn't think of a better way to reach out to people interested in XSpec. After the webinar takes place I will post here a link to the recording and close the issue.

Thank you,
Alex
\-\-
Alex Jitianu
<oXygen/>  XML Editor, Schema Editor and XSLT Editor/Debugger
http://www.oxygenxml.com

**Comment by AirQuick** [comment]
And maybe [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Oxygen) should be updated later.

**Comment by cirulls** [comment]
We could also add a link in the list of [presentations on XSpec](https://github.com/xspec/xspec/wiki/Presentations-and-demos-on-XSpec) and, if slides are available, add them to [this repository](https://github.com/xspec/xspec-presentations).

**Comment by AlexJitianu** [comment]
The recording, slides and samples are now available on the event's page:
https://www.oxygenxml.com/events/2018/webinar_xspec_unit_testing_for_xslt_and_schematron.html

**Comment by cirulls** [comment]
Well done Alex, thanks a lot for doing this webinar, it's really useful to get more people into testing in the XML world, using XSpec and spreading the word about the Schematron support. I haven't followed the live streaming as I was still at work but I look forward to watch the recording.

I updated the following documentation with the link:

-  [Running with Oxygen](https://github.com/xspec/xspec/wiki/Running-with-Oxygen)
- [Presentations and demos on XSpec](https://github.com/xspec/xspec/wiki/Presentations-and-demos-on-XSpec#articles-videos-and-more)
- [xspec-presentations repository](https://github.com/xspec/xspec-presentations/tree/master/2018/oxygen-webinar)

As discussed, I'm closing this issue after the event and documentation update.
