### ISSUE TITLE
Release 1.1.0 required

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#395]
Hi all !

I need a release to be able to build a release for [XSpec maven plugin](https://github.com/xspec/xspec-maven-plugin-1). Could you build one ?

A release is a delivery build from a known state of sources (i.e. a tag), and published somewhere (Maven central will be great). It can be build from sources, with `mvn -Prelease install deploy`, after defining correctly `<version>x.v.z</version>` in `pom.xml`. A release is not required to be bug-free, only to follow release rules (mapping commit / name, correct version numbering).

A lot of work has been done since last release [1.0.0](http://repo1.maven.org/maven2/io/xspec/xspec/1.0.0/), and all these work should be released quickly to be available to other projects, without copying code...

As old xspec unit-tests written to run with XSpec 1.0.0 still work, changing minor number should be enough, so a **1.1.0** is, in my opinion, a good target.

As I have passwords to publish to maven central for `io.xspec` groupId, I can do this, but I'm not enough in xspec dev to know from which branch / commit should I create the release.

Thanks in advance

**Comment by cirulls** [comment]
@cmarchand: I'm happy to create a new release by the end of this week, would that be ok for you? Release notes are up-to-date and hopefully it shouldn't take me too long. I would be greateful if you could publish XSpec to maven central as usual. The new release number will be v1.1.0, this is what we have been using so far, there are few new functionalities but nothing too revolutionary (which I believe it is good).

@AirQuick: I would like to review and merge your pull requests up to #264 (included) since these changes are not impacting any existing functionality. I should be able to review and merge them in the next days. #265 provides some changes to the code and I would like to review it in more detail after the release of v1.1.0. Would that be ok for you?

If anyone else has other pull requests that should absolutely be in v1.1.0, please post a comment here.

**Comment by AirQuick** [comment]
OK for me, though #265 is a trivial change and won't take time. (#266 and later will definitely take some time.)

**Comment by cmarchand** [comment]
End of the week is perfect for me !
Thanks a lot, Sandro !

**Comment by cirulls** [comment]
Thanks @AirQuick and @cmarchand for your feedback. @AirQuick, I may be able to include #265 in my review if it's trivial. @cmarchand I may have the password to publish from when you created it the first time (if it hasn't changed). Thanks for the info via email. I'll keep you posted on my progress on Wednesday or Thursday (can't work on XSpec tomorrow).

**Comment by cirulls** [comment]
XSpec v1.1.0 is now officially released, you can download a zip or tar file of the latest `master` branch at https://github.com/xspec/xspec/releases/latest  In there you can also read the release notes and probably find your name in the list of contributors!

I'm going to promote the release by posting a message to be included in [xml.com news section](https://www.xml.com/news/) and [Google Groups XSpec user mailing list](https://groups.google.com/forum/#!forum/xspec-users). If you are into social media (I know @cmarchand and @yamahito are 😉 ) please spread the word about this release. 

@cmarchand : if that's all you need for the XSpec Maven plugin, feel free to close this issue.

**Comment by cmarchand** [comment]
Did you publish it to [Sonatype OSSRH](https://oss.sonatype.org/service/local/staging/deploy/maven2/) ? I can not see it in [Maven central](http://repo1.maven.org/maven2/io/xspec/xspec/), but it may not having being mirrored yet...

**Comment by cirulls** [comment]
@cmarchand : No, I only did the release on GitHub. As discussed in [here](https://github.com/xspec/xspec/issues/395#issuecomment-427800101), I would be grateful if you could publish XSpec to Maven Central as you did last time. But if you can't, I can give it a go tomorrow. Let me know.

**Comment by cmarchand** [comment]
Done. Attached 2 patches I can not push. It is only `pom.xml` modifications, to follow release numbers. It'll be great if you could apply them on master ASAP.

[change-release-pom.zip](https://github.com/xspec/xspec/files/2476656/change-release-pom.zip)

**Comment by yamahito** [comment]
Posted on twitter via @markupukorg (and retweeted as me) :)

Shall I also post on xml-dev?

**Comment by cirulls** [comment]
Thanks @yamahito. Yes, it would be great to post it on xml-dev too.

**Comment by yamahito** [comment]
Done!
