### ISSUE TITLE
Schematron: text() node fails

### ISSUE THREAD

**Issue by shudson310** [xspec/xspec#396]
I get a failure when a rule context is a text node: text(). For example:

    <sch:pattern>
        <sch:rule context="text()">
            <sch:report id="above-mentioned"
                test="matches(., 'above-mentioned')"
                role="info" >Forbidden word: above-mentioned</sch:report>
        </sch:rule>
    </sch:pattern>

    <x:scenario label="above-mentioned" focus="test this framework">
        <x:context><conbody><p>above-mentioned</p></conbody></x:context>
        <x:expect-report id="above-mentioned" role="info" location="/conbody[1]/p[1]"/>
    </x:scenario>

If I change the rule to match the p element than the XSpec begins to work. I cannot change my .sch for many of my rules, so the XSpec framework should accommodate text() node matches.

**Comment by AirQuick** [comment]
When I insert this pair of `x:param`

```xml
<x:description schematron="test.sch" xmlns:x="http://www.jenitennison.com/xslt/xspec">
	<x:param name="only-child-elements">false</x:param>
	<x:param name="visit-text">true</x:param>
	<x:scenario focus="test this framework" label="above-mentioned">
...
```

and run XSpec command line (`bin\xspec.bat -s` or `bin/xspec.sh -s`), then the test succeeds.

**Comment by cirulls** [comment]
@shudson310 : does @AirQuick 's reply answer your question? Can we close the issue?

**Comment by shudson310** [comment]
The suggested params do fix the issue, but you may want to emphasize this in the documentation and tutorials. Thanks! You can close this issue.

**Comment by AirQuick** [comment]
@vincentml 
I think XSpec should set `allow-foreign=true`, `only-child-elements=false` and `visit-text=true` for convenience, unless specified otherwise in `/x:desciption/x:param`. What do you think?

I have such changes both for command line and Ant.

**Comment by shudson310** [comment]
Sorry to report, but I have tried all of these:
   <x:param name="only-child-elements">false</x:param>
   <x:param name="visit-text">true</x:param>
   <x:param name="allow-foreign">true</x:param>

Still getting errors reported in oXygen plugin. Not sure if it is an XSpec issue or a plugin issue.

**Comment by AirQuick** [comment]
Both oXygen transformation scenario and plugin are Ant based. Parameters aren't implemented there yet.
I'll soon submit a pull request for it.

In the meantime, you have to modify `[oXygen installation]/frameworks/xspec/build.xml` (in case of transformation scenario) or `[Home]/.com.oxygenxml/extensions/.../oxygen-results-view/build_report.xml` (in case of plugin) to hardcode `only-child-elements` and `visit-text` just like `allow-foreign` is hardcoded:
https://github.com/xspec/xspec/blob/7361f1995416ad30777d4546ec3d970977d2abb2/build.xml#L214

**Comment by shudson310** [comment]
Thanks for the tip!

On OS X, this was in [Home]/Library/Preferences/com.oxygenxml/extensions/.../oxygen-results-view/build_report.xml

After making this change and adding the parameters, the <x:expect-report> still fails.

Are there any other files that still need to be modified? The expected diff still shows "()" instead of no content.

**Comment by AirQuick** [comment]
After modification, your `build_report.xml` should look like this:

```xml
...
    <echo message="   STEP 3: Convert Schematron to XSL"/>
...
      <factory name="net.sf.saxon.TransformerFactoryImpl"/>
      <param name="allow-foreign" expression="true"/>
      <param name="only-child-elements" expression="false"/>
      <param name="visit-text" expression="true"/>
      <param name="phase" expression="${xspec.phase}" unless:blank="${xspec.phase}"/>
      <xmlcatalog if:set="catalog">
...
```

No other change was necessary on my end.

**Comment by vincentml** [comment]
> I think XSpec should set `allow-foreign=true`, `only-child-elements=false` and `visit-text=true` for convenience, unless specified otherwise in `/x:desciption/x:param`. What do you think?

It is better that XSpec itself should not override default parameter settings for Schematron, but users of XSpec can specify parameter settings for Schematron using `<x:param>`.  For example, if someone has not specified Schematron parameters in their environment the behavior of XSpec will be the same. Likewise, if someone has specified parameters for Schematron in their environment they can specify the same parameter values in XSpec. This would, I think, match user expectation. 

However, it becomes more dicey when looking at the default values in different implementations of Schematron. The one in the [GitHub Schematron project](https://github.com/Schematron/schematron), which bundled with XSpec, is older. The one in oXygen is based on the one from GitHub and contains a number of enhancements. They have each different defaults.

| param               | GitHub                  | oXygen                  | 
|---------------------|-------------------------|-------------------------| 
| allow-foreign       | FALSE                   | FALSE                   | 
| only-child-elements | false, conditional true | true, conditional false | 
| visit-text          | FALSE                   | TRUE                    | 

It would be interesting to find out if the enhancements that oXygen has made to Schematron could be contributed to the GitHub Schematron project. This might be a question for @AlexJitianu

What I think we can do for XSpec is to add more information in the [wiki documentation](https://github.com/xspec/xspec/wiki/Writing-Scenarios-for-Schematron) about Schematron parameters.

**Comment by AirQuick** [comment]
Thanks, @vincentml 
Then I won't set any default in my upcoming pull request.

`allow-foreign` on Oxygen seems to be TRUE by default in its Preferences - XML - XML Parser - Schematron.

**Comment by vincentml** [comment]
> `allow-foreign` on Oxygen seems to be TRUE by default in its Preferences - XML - XML Parser - Schematron.

That is a good observation. In the oXygen Preferences panel the defaults for `allow-foreign` is true. I was looking in `Oxygen XML Editor 20/frameworks/schematron/impl/iso_schematron_skeleton.xsl` which has false as the default for `allow-foreign`.

**Comment by AlexJitianu** [comment]
> It would be interesting to find out if the enhancements that oXygen has made to Schematron could be contributed to the GitHub Schematron project. This might be a question for @AlexJitianu
Well, we usually create issues/pull request on the GitHub Schematron project with all the enhancements we consider worth making. We did the same with visit-text/only-child-elements parameters but, because we considered that the defaults should change, we didn't wait for the issues to reach a resolution and we made these changes in our distribution of Schematron.

**Comment by AirQuick** [comment]
I submitted #411. With it, `/x:description/x:param` works on XSpec for Schematron when using Ant.
If you like to test it now on the oXygen transformation scenario, clone the PR branch and follow the steps written in [`build.xml`](https://github.com/AirQuick/xspec/blob/7a1515a38a2272ef83598ae60c15ad84c6128cea/build.xml#L18-L34).

Once the PR gets merged and ported to the oXygen XSpec plugin, `x:param` will probably work on it, too.

Unfortunately the `@location` problem needs to be fixed in the upstream, as I wrote in the previous comment.

**Comment by AirQuick** [comment]
Just FYI. Using [schxslt](https://github.com/dmj/schxslt), `x:expect-report/@location` seems to work with text nodes. You don't need to set `x:param`.

**Comment by vincentml** [comment]
I had not seen [schxslt](https://github.com/dmj/schxslt) before. Very interesting! I will have to try using this Schematron implementation.

**Comment by AirQuick** [comment]
I added a Wiki page, [Testing Schematron with Text Nodes](https://github.com/xspec/xspec/wiki/Testing-Schematron-with-Text-Nodes), based on this issue.
