### ISSUE TITLE
Bug comparing expect dans result files that are the same

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#398]
Hi,

attached a reproductible xspec that fails, and it shouldn't. [bug-xspec-impl-1.0.0_deep-equal.zip](https://github.com/xspec/xspec/files/2468127/bug-xspec-impl-1.0.0_deep-equal.zip)

Try running `xspec/aggregate_EE.xspec` ; test result presents on the left a file reference (dxx.xml) for the result and on the right part the expected content. It says result and expected are different, but I can't see where, as result is not displayed. I use XSpec distributed with Oxygen 20.1, it should be a very recent one, as there is support for schematron.

If you do not have suppressed intermediate files (you may have to comment out `<delete .../>`  in build.xml), you'll find generated files for result and expect contents.

Then, modify `reproductible.xsl`to load the two intermediates files. This xsl only call `test=deep-equal(...)` and presents the result. Run it, and check that the two files are identical.

So, I can not understand why the HTML report says result and expect are different.

Thanks in advance,
Christophe

**Comment by cmarchand** [comment]
It should !
I send immediately a pull request.

**Comment by AirQuick** [comment]
#1500 will close this issue.
