### ISSUE TITLE
Saving expectations and results

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#403]
In a scenario with a `<x:expect`, tested XSLT or XQuery produces a result document. Sometimes, depending on result size, it is written to file, and HTML report show a link to this document.

May we have :
 - when result document is written to file, write to file also the expectation ?
 - an option to force to write result and expectation to disk, whatever the size ?

Hence, we will be able to open an external tool (no name, but I use a wonderful tool that can diff xml files), open expectation and result, and compare files

**Comment by galtm** [comment]
@cmarchand , are you still interested in this enhancement? In discussions of #1500, @AirQuick and I both thought the separate-file behavior was not commonly desired by users. Maybe we were wrong.

The attribute setting `<x:description result-file-threshold="0" ...>` fulfills the 2nd part of your request,

>an option to force to write result and expectation to disk, whatever the size ?

but this attribute's behavior is not documented.

**Comment by cmarchand** [comment]
I clearly do not remember why I open this issue 5 years ago !

I think it can be closed without any risk ! So I do !
