### ISSUE TITLE
References to maven in the wiki are outdated

### ISSUE THREAD

**Issue by yamahito** [xspec/xspec#418]
Hi folks,

I don't think https://github.com/xspec/xspec-maven-plugin-1 is mentioned on the maven page of the wiki; instead they talk about Adam and Daisy's implementations, which I think are probably less preferable (i.e. are out of date)...

**Comment by AirQuick** [comment]
@yamahito @cmarchand
In [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Maven), I've added https://github.com/xspec/xspec-maven-plugin-1 as primary.
I don't know the relationship among the implementations. So feel free to revise the description.

**Comment by cmarchand** [comment]
For information, [our xspec-maven-plugin](https://github.com/xspec/xspec-maven-plugin-1) is a fork of [Adam's one](http://github.com/adamretter/xspec-maven-plugin), as Adam didn't have time enough to maintain it. It is now largely out of date.
[Daisy's one](https://github.com/daisy/xspec-maven-plugin) is maintained by Bert Frees and Romain Deltour, and is better than Adam's one, but behind us.  
We did plan, with Romain, to merge ours and Daisy's. i.e. integrate Daisy's specificities into ours, and kill Daisy's one. But nothing has been done.  
Maybe we should register for an appointment in a beer station... Skelp should be Ok...

**Comment by AirQuick** [comment]
Thanks, @cmarchand 
I updated [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Maven) a bit to clarify that
* xspec/xspec-maven-plugin-1 is a fork of Adam's
* Adam's one is out of date

**Comment by AirQuick** [comment]
Closing now. To wrap it up, this issue has resulted in [this change](https://github.com/xspec/xspec/wiki/Running-with-Maven/_compare/bd58baa1995cce21d2865128c5e0100b11d1d73b...5cc3b48045ee3c291587ee8f38fafa2328954ac5).
Feel free to suggest further changes.
