### ISSUE TITLE
Some Scenario is fail on jenkins

### ISSUE THREAD

**Issue by Anil-XSpec** [xspec/xspec#422]
My xspec is working fine on oxygen and all scenario is passed but I have found some error in run the jenkins of our xspec. Below is error log:
Error at xsl:result-document on line 575 of generate-tests-utils.xsl:
  XTDE1490: Cannot write more than one result document to the same URI:
  file:/c:/XSpec/d164e0.xml
Transformation failed: Run-time errors were reported

Kindly advise how to resolve this type of issue.

**Comment by AirQuick** [comment]
Closing.

@Anil-XSpec 
If the problem happens on [v1.2.0](https://github.com/xspec/xspec/releases/tag/v1.2.0) or later, please let us know.
