### ISSUE TITLE
[XSLT 3.0 Support] Managing errors

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#500]
This issue is a specialisation of #127 concerning errors.

XSLT 3.0 added support for [try / catch](https://www.w3.org/TR/xslt-30/#try-catch). So we can define functions with a strict signature, that throw error when something goes wrong.

Here is an example of such a function :
```
<xsl:function name="conf:getConfVar" as="xs:string">
  <xsl:param name="conf" as="element(els-conf:conf)"/>
  <xsl:param name="varName" as="xs:string"/>
  <xsl:sequence select="
    if (exists($conf/els-conf:variable[@name=$varName]))
      then 
        $conf/els-conf:variable[@name=$varName]/@value
      else 
        (error(
          $conf:ERROR_MISSING_ENTRY,
          concat('Entry ',$varName,' is missing in environment configuration')
        ))
    "/>
</xsl:function>
```
Such a function can not be tested, as XSpec is not able to use try / catch.

I'd expect to be able to test this function like this :
```
<x:scenario...>
  <x:call function="conf:getConfVar">
    <x:param name="conf" xmlns="foo:bar">
      <conf>
        <variable name="foo" value="nothing"/>
      </conf>
    </x:param>
    <x:param name="varName" select="'missing'"/>
  </x:call>
  <x:expect error:code="ERROR_MISSING_ENTRY" error:description="nothing is missing in environment configuration"/>
</x:scenario>
```

I create this issue, as we are working for a pull request proposal.

**Comment by AirQuick** [comment]
At the moment, for my own use of this kind of test, I write a wrapper XSLT which includes the test target XSLT.
In the wrapper XSLT, I write a wrapper function which calls the test target function in `xsl:try` and catches the error information and returns them.
In XSpec, I write `<x:call function="the:wrapper-func">` with something like `<x:expect label="HC006" select="xs:QName('expath-err:HC006')" />`.

Anyway, yes, it is appreciated if there is a standard, simpler and viable method.
If you create a pull request, please make sure it doesn't *always* require XSLT 3.0.

**Comment by cmarchand** [comment]
I do exactly the same. But it's awful because it requires to have XSL code in xspec directory.
I'll be very careful to backward compatibility. Maybe, we could forbid the use of `error:*` attributes if there is no `/x:description/@xslt-version="3.0"`

**Comment by Nico-Amplexor** [comment]
In xsl:variable "xslt-version" why get version in xspec xslt-version attribute and not directly in xslt stylesheet like this?

```
<xsl:variable name="stylesheet" as="document-node()" 
  select="doc($stylesheet-uri)" />  
<xsl:variable name="stylesheet-version" as="xs:decimal" 
  select="doc($stylesheet-uri)/*[1]/@version" />
```

**Comment by AirQuick** [comment]
I don't know exactly why.
But I sometimes use XPath 3.x expression in .xspec file while the tested .xsl is still 2.0. Perhaps that's one of the reasons.

**Comment by AirQuick** [comment]
And yes, Saxon 9.7 is picky about the version when .xspec contains XPath 3.x:
```console
...
  XPST0003: Concatenation operator ('||') requires XPath 3.0 to be enabled
Errors were reported during stylesheet compilation
```
So you can't simply take the version from the tested stylesheet.

**Comment by Nico-Amplexor** [comment]
OK thanks.

**Comment by cmarchand** [comment]
@AirQuick : could you have a look at this clone : https://github.com/Nico-Amplexor/xspec/tree/issue/500
@Nico-Amplexor is actually on holidays, but I think he has done quite a good job...

**Comment by AirQuick** [comment]
Quick random thoughts:
* Success/Failure is determined only using some predefind rules? Isn't it more robust if we just expose a variable (e.g `$x:err`) which encapsulates all the error information? Then the user can test whatever she/he likes by using it like `<x:expect test="$x:err?code eq 100 and ends-with($x:err?module, '/foo.xsl')" />`?
* Can you provide some basic tests (putting some Success instances of `x:scenario` into `test/error.xspec`, for example)? Then we can easily understand the actual usage patterns.
* We'll need to update the schema if we update the grammar

(I just took a very rough look at the code changes. Sorry if I misunderstand something!)

**Comment by cmsmcq** [comment]
> XSLT 3.0 added support for [try / catch](https://www.w3.org/TR/xslt-30/#try-catch). So we can define functions with a strict signature, that throw error when something goes wrong.
>...
> I create this issue, as we are working for a pull request proposal.

This would be a good improvement, as would a parallel change for XQuery 3.0.  (I just had to add 'pending' to four of six tests I wrote this morning because XSpec lacks a way to say that what is expected is that a dynamic error will be raised.)

If there are active XSpec users working with XSLT 2.0 or XQuery 1.0 processors, I can understand the need to be careful about assuming support for dynamic errors and try/catch.  But I would guess that there are more XSLT 1.0 users out there (people using xsltproc or in-browser stylesheets) than 2.0-but-not-3.0 users.  (Of course, that's just my guess; I do not have data.)

**Comment by AirQuick** [comment]
> This would be a good improvement, as would a parallel change for XQuery 3.0.

Right now XSpec's XQuery implementation is way behind XSLT. The upcoming v1.3.0 fills some gaps. On  v1.4.0, XQuery will be mostly on a parity with XSLT (as far as I'm aware). It will be easier to implement new XQuery features then.

**Comment by AirQuick** [comment]
I have an implementation where you can set `@catch` in `<x:scenario>`.
With `<x:scenario catch="yes">`, its descendant-or-self scenarios will catch dynamic errors when invoking the tested module. The standard error variables including `$err:code` and `$err:description` are stored in `$x:result` as a map.

So, with the initial example (https://github.com/xspec/xspec/issues/500#issue-400638585), you would write a scenario like this:

```xml
<x:scenario... catch="yes">
  <x:call function="conf:getConfVar">
    <x:param name="conf" xmlns="foo:bar">
      <conf>
        <variable name="foo" value="nothing"/>
      </conf>
    </x:param>
    <x:param name="varName" select="'missing'"/>
  </x:call>
  <x:expect test="$x:result?err?code='ERROR_MISSING_ENTRY'"/>
  <x:expect test="$x:result?err?description='nothing is missing in environment configuration'"/>
</x:scenario>
```

If `conf:getConfVar()` didn't throw an error in the above example, `$x:result` contains its return items intact.

Is this fine with you, @cmarchand , @Nico-Amplexor , @cmsmcq ?
The implementation is available both for XSLT and XQuery. (requires 3.0 and 3.1 respectively)

**Comment by AirQuick** [comment]
Submitted #599
