### ISSUE TITLE
XProcSpec

### ISSUE THREAD

**Issue by nkutsche** [xspec/xspec#516]
Hi folks,

I found this [XProcSpec](http://daisy.github.io/xprocspec/) by chance (it is really good hidden) and I'm wondering why this is not included or at least mentioned here? Did I missed something?

In fact I have lots of use cases where I need a XProc testing framework and I did it always manually.

**Comment by AirQuick** [comment]
Maybe, somewhere in Wiki (possibly in [Running with XProc](https://github.com/xspec/xspec/wiki/Running-with-XProc)?), we could add a section titled "Looking for a framework for testing XProc scripts?" and introduce xprocspec there.

Or, are you looking for integrating xprocspec's grammar into XSpec?

**Comment by nkutsche** [comment]
> Or, are you looking for integrating xprocspec's grammar into XSpec?

I would appreciate that, but I didn't had a deeper look inside into XProcSpec, so I don't know how much effort it would cause.

So the easiest way would be to link it in the Wiki. Maybe as "Related projects"? Actually I wouldn't expect it in [Running with XProc](https://github.com/xspec/xspec/wiki/Running-with-XProc), as this is about a way to implement XSpec.

**Comment by cirulls** [comment]
XProcSpec is a useful tool (I used few years ago to test XProc pipelines) and is well [documented](https://daisy.github.io/xprocspec/www/documentation/index.html). We can definitely add a link. Following @nkutsche 's suggestions, we can create a Related Projects page on the wiki and add it there (that would be a good place for the [oXygen XSpec plugin](https://github.com/xspec/oXygen-XML-editor-xspec-support), it sits within the XSpec organisation but I don't think it is mentioned anywhere in the wiki). @AirQuick: what do you think?

And maybe we can also get in touch with @josteinaj to update the links in the XProcSpec's documentation to reference https://github.com/xspec/xspec (it is still linking to the old Google code repository).

**Comment by AirQuick** [comment]
*Related Projects* page is fine.

https://github.com/dmj/xproc-xspec might also be worth mentioning somewhere. Unlike XSpec's built-in XProc harness, it seems Schematron capable. I haven't used it myself, though.

**Comment by josteinaj** [comment]
@cirulls reference to xspec hereby updated.

**Comment by cirulls** [comment]
@josteinaj: thanks for updating the links.

I'll create a page Related Projects on the wiki and add links for xprocspec and xproc-xspec. If there are other XSpec related projects, feel free to mention them in this issue and I'll update the wiki page.

**Comment by cirulls** [comment]
Sorry for the wait, this went off my radar. I added a wiki page [Related Projects](https://github.com/xspec/xspec/wiki/Related-Projects) and added links to xprocspec, XProc XSpec, and the oXygen XSpec plugin.

@nkutsche: does this address your needs? Can I close this issue?

**Comment by nkutsche** [comment]
Great! Thanks.
