### ISSUE TITLE
document-node(...) typed parameters

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#517]
Hello,

We use XSLT we parameters typed as document-node() :
```
<xsl:param name="BO.CONF" required="true" as="document-node(element(conf))"/>
```
In the same XLST, we have functions that use this as a typed parameter :
```
  <xsl:function name="conf:getBoConf" as="element(els-conf:conf)" cache="true" visibility="public">
    <xsl:variable name="boConfDoc" select="$BO.CONF" as="document-node(element(els-conf:conf))"/>
    <xsl:sequence select="$boConfDoc/els-conf:conf"/>
  </xsl:function>
```

If we want to unit-test this XSLT, we *must* define such a parameter. In xspec, that's done like this :
```
<x:param name="BO.CONF">
    <conf>
        <variable name="BASEXML_PUBLI_USER" value="flash-rest-writer" as="xs:string"/>
    </conf>
</x:param>
```
XSpec compiler translates this as 
```
<xsl:variable name="BO.CONF-doc" as="document-node()">
  <xsl:document>
    <conf xmlns="http://www.lefebvre-sarrut.eu/ns/els/conf">
      <variable name="BASEXML_PUBLI_USER" value="flash-rest-writer" as="xs:string"/>
    </conf>
  </xsl:document>
</xsl:variable>
<xsl:param name="BO.CONF" select="$BO.CONF-doc/node()"/>
```
So it defines an un-typed parameter `BO.CONF`, which - according to [XSLT 2 specification](https://www.w3.org/TR/xslt20/#temporary-trees) - should be considered as a `document-node()`.
If I have a scenario that call `conf:getBoConf` function, I have an error :
```
[ERROR] Required item type of value of variable $boConfDoc is document-node(element(conf)); supplied value has item type element(conf)
```

How could I write such a scenario, to test my XSLT ? 
Thanks in advance,
Christophe

**Comment by AirQuick** [comment]
When you have
```xml
<x:param name="foo">
  <bar />
</x:param>
```

XSpec first wraps `<bar>` in a wrapper document node (`$foo-doc`) and then evaluate `@select` in the context of `$foo-doc`.
If you don't have `@select`, `child::node()` is assumed.
So in the above `x:param`, `$foo` is `$foo-doc/child::node()`, hence `<bar>` (i.e. `element(bar)`).

If you want to select the wrapper document node itself, you can specify it so in `@select`:

```xml
<x:param name="foo" select="self::document-node()">
  <bar />
</x:param>
```

Or one may prefer this:

```xml
<x:param name="foo" select="/">
  <bar />
</x:param>
```

**Comment by AirQuick** [comment]
I've seen this kind of questions for several times. So I [updated](https://github.com/xspec/xspec/wiki/Writing-Scenarios/_compare/9ad60b1232192ec6084bf5cc3fb03470f7b12e48...a9a1a51e9a698c80356708a648a5c6a169a5bcd3) Wiki to describe the behavior in a little more detail.
Although this behavior isn't applicable only to function calls, I updated the [*Function Scenarios* section](https://github.com/xspec/xspec/wiki/Writing-Scenarios#function-scenarios) just because there was no other example to update.

**Comment by AirQuick** [comment]
Closing this issue, assuming that the update Wiki matches the problem.

@cmarchand 
If the updated Wiki isn't clear enough to resolve the problem, please let us know.
