### ISSUE TITLE
Prepare XSpec for release v0.5.0

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#52]
Prior to the XSpec release v0.5.0, update the README and LICENSE files, the wiki and the release notes.

**Comment by AirQuick** [comment]
Is this wiki page still necessary?
https://github.com/xspec/xspec/wiki/User-Guide
Seems like it's orphaned.

**Comment by AirQuick** [comment]
Made minor updates to https://github.com/xspec/xspec/wiki/Running-Scenarios
See its page history for details.

**Comment by AirQuick** [comment]
Added color legends to https://github.com/xspec/xspec/wiki/Code-Coverage

**Comment by cirulls** [comment]
I removed the orphaned page User-Guide, content in this page went into [What is XSpec](https://github.com/xspec/xspec/wiki/What-is-XSpec), [Installation on Mac and Linux](https://github.com/xspec/xspec/wiki/Installation-on-Mac-and-Linux) and [Installation on Windows](https://github.com/xspec/xspec/wiki/Installation-on-Windows).

**Comment by cirulls** [comment]
I'm fine with changes in [Running Scenarios](https://github.com/xspec/xspec/wiki/Running-Scenarios), thanks for doing it.

**Comment by cirulls** [comment]
Thanks for adding the colour legends on [Code Coverage](https://github.com/xspec/xspec/wiki/Code-Coverage).
