### ISSUE TITLE
Update Wiki for BaseX server

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#578]
#577 
> ### Further work
> Update [Wiki](https://github.com/xspec/xspec/wiki/Running-with-BaseX), based on the test

Also [*How to Run the Test Suite Locally*](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) should be updated. (https://github.com/xspec/xspec/pull/577#issuecomment-505213186)

**Comment by galtm** [comment]
> Also [_How to Run the Test Suite Locally_](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) should be updated.

While you're there, can you please also fix the typo, where it says "it it recommended" instead of "it is recommended"? Thanks!

**Comment by AirQuick** [comment]
@galtm 
Can you try fixing the typo? I think you're allowed to edit Wiki pages. Feel free to correct any page at any time.

**Comment by galtm** [comment]
@AirQuick : You're right. The system let me edit the page, so I fixed the typo.

**Comment by AirQuick** [comment]
Thanks for fixing it. Also please feel free to edit more than typo. Wiki is version controlled by git. So you won't lose previous versions even if you make bold changes.

**Comment by galtm** [comment]
OK, I will keep that in mind. In particular, my PR #475 will require some wiki changes.

**Comment by AirQuick** [comment]
> Update Wiki, based on the test

[Done](https://github.com/xspec/xspec/wiki/Running-with-BaseX#run-an-xspec-test-for-xquery-with-basex-server) ([diff](https://github.com/xspec/xspec/wiki/Running-with-BaseX/_compare/3c985b9f556d024b09ae43b9cc5580195d02d2fe...fdc0f9914ea365194a52d8a96620c1b3e2198ef3))

**Comment by AirQuick** [comment]
> Also [*How to Run the Test Suite Locally*](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) should be updated. (https://github.com/xspec/xspec/pull/577#issuecomment-505213186)

Done ([diff](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally/_compare/a076c0ab0b65c1b3b0cd05725651fe9df5e67971...a3d52b2aad9a2fa2caf78e321021e62aee4ce5c9))
