### ISSUE TITLE
Make the HTML presentation of differences distinguish between 'element name is different' and 'element contains some difference somewhere'

### ISSUE THREAD

**Issue by cmsmcq** [xspec/xspec#579]
[RFE]

When the expected result of a function call is an element, and some descendant text node is different, the HTML display of the test shows uses a pink background for the text nodes which correspond to each other in the obtained result and the expected result and which differ.  That makes sense.

It also uses a pink background for the element names of all of their ancestor elements.  

![Screen Shot 2019-06-20 at 11 22 42 AM](https://user-images.githubusercontent.com/4857689/59869263-23467e80-9350-11e9-8730-ec18f1d52af0.png)

This suggests to at least some users (e.g. me) that XSpec thinks the element names differ between the obtained result and the expected result, which is manifestly not the case.  I have been looking at test reports like the one shown in the attached image for a couple of weeks now (trying to make XSpec stop reporting a test failure when the result is correct but XSpec's whitespace handling has somehow created a difference between the expected result and the actual result), and today for the first time I realized that the pink element names in the display don't mean "the name of the element is different" but "there is a difference somewhere inside this element."

It would be easier to understand the display if the pink background were reserved for nodes which differ, and the element names of ancestor nodes used a different background color.  Perhaps violet or pale indigo would work.

**Comment by AirQuick** [comment]
The diff style needs some improvement.
Right now the style is either `same` or `diff` based on custom `deep-equal()`. ([code](https://github.com/xspec/xspec/blob/69eff644d093a131b2c64778479ec73f71662066/src/reporter/format-utils.xsl#L315-L328))
