### ISSUE TITLE
Add build.xml to a Maven artifact

### ISSUE THREAD

**Issue by nkutsche** [xspec/xspec#584]
I wrote an own [XSpec Maven Plugin](https://github.com/nkutsche/xspec-maven-plugin/) which calls this [build.xml](https://github.com/xspec/xspec/blob/master/build.xml) internally. Unfortunately I had to add the complete XSpec framework zipped to the [project git repository](https://github.com/nkutsche/xspec-maven-plugin/blob/master/src/main/resources/xspec-1.3.0.zip) because the Maven artifacts do not contain the `build.xml`.

It would be much cleaner if I could use the Maven dependency logic to refer the XSpec Framework.

**Comment by cirulls** [comment]
@nkutsche: thanks for the heads-up, I also saw your issue on the maven plugin repository. 

It would be good to get @cmarchand 's opinion on that as he usually creates the maven artifacts for XSpec when a new XSpec release is available.

**Comment by AirQuick** [comment]
What do you think, @cmarchand?

**Comment by cmarchand** [comment]
build.xml was not packaged inside XSpec Maven Plugin because it does not use it, and because build.xml is not part of XSpec Maven Plugin.
But XSpec implementation which is packaged as a maven artifact, available on maven central, should have build.xml inside, as build.xml is part of implementation.

So, I have to add build.xml to package process, and this issue is a bug.

**Comment by AirQuick** [comment]
Thanks, @cmarchand 

> So, I have to add build.xml to package process, and this issue is a bug.

Do we need to revise [`pom.xml`](https://github.com/xspec/xspec/blob/master/pom.xml)?

**Comment by cmarchand** [comment]
Yes, we do. And we need to revise also the -sources classifier, that do not contain `build.xml`.

**Comment by cmarchand** [comment]
@AirQuick : what is the naming conventions for issues branches ?

**Comment by AirQuick** [comment]
It is appreciated you can submit a pull request for the required change. We're going to release v1.4.0 soon (not within a few days, but within a few weeks). Hopefully we can include this fix.

We don't have any explicit naming conventions for the branches at the moment.

**Comment by cmarchand** [comment]
Pull request created.
