### ISSUE TITLE
Deprecate Saxon 9.7 or less

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#596]
Saxon 9.7 or less should be deprecated explicitly:

* In Release Note
* In Wiki (probably *Installation*)
* In run time message?

Rationale:

* Burden on development and testing, both on XSLT and XQuery, primarily because of limited support of XPath/XSLT/XQuery 3.x, partially because of differences in command interface
* No longer maintained by Saxonica

**Comment by AirQuick** [comment]
@xspec/xspec 
I'd like to propose

* Create a Wiki page, titled *Requirements*, under *Installation* section.
* Move *Requirements* blocks from [*Installation on Mac and Linux*](https://github.com/xspec/xspec/wiki/Installation-on-Mac-and-Linux#requirements) and [*Installation on Windows*](https://github.com/xspec/xspec/wiki/Installation-on-Windows#requirements) to the new page.

and in the new page, add these warnings

* Saxon 9.7 (or less) is deprecated. XSpec is not tested regularly on 9.7.
* For the moment, XSpec will be tested only occasionally on 9.7. (*1)
* At some point in the near future, XSpec will stop being tested at all on 9.7 and probably will stop functioning on 9.7 HE (*2)

[1] I'm testing XSpec occasionally on 9.7 for some practical reasons. So I'll continue it for the moment.
[2] ["All XSLT 3.0 features require at least Saxon-PE."](http://www.saxonica.com/documentation9.7/index.html#!using-xsl/xslt30)

**Comment by cirulls** [comment]
@AirQuick: this sounds good to me, the deprecation warning will be very useful for helping people migrating to the latest Saxon.

**Comment by AirQuick** [comment]
> * Create a Wiki page, titled _Requirements_, under _Installation_ section.
> * Move _Requirements_ blocks from [_Installation on Mac and Linux_](https://github.com/xspec/xspec/wiki/Installation-on-Mac-and-Linux#requirements) and [_Installation on Windows_](https://github.com/xspec/xspec/wiki/Installation-on-Windows#requirements) to the new _Requirements_ page.

Done.

**Comment by AirQuick** [comment]
> * In run time message?

Done in #625. Thanks for the review, @cirulls and @galtm.

**Comment by cirulls** [comment]
I think the move to Java 8 for testing XSpec and the deprecation message for Saxon 9.7 could be mentioned explicitly in the highlights for the next release notes so that users are aware of it.

**Comment by AirQuick** [comment]
> I think the move to Java 8 for testing XSpec and the deprecation message for Saxon 9.7 could be mentioned explicitly in the highlights for the next release notes so that users are aware of it.

How we communicate it, I'll leave it up to you.
Ironically, for the first time, we have continuous testing on Saxon 9.7 :)
