### ISSUE TITLE
Namespace declarations need to be on x:description element (not a descendant), in some circumstances

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#598]
Some parts of the compiler code seem to assume that all the necessary namespace declarations occur on the `x:description` element. For example, overriding a global parameter using `<x:param name="e:globalparam" xmlns:e="...">` does not work if `x:description` does not have `xmlns:e="..."`.

**Comment by galtm** [comment]
If this limitation is considered a bug, I'd like to try fixing it at least for XSLT. XQuery seems trickier, and I might look into that later.

**Comment by AirQuick** [comment]
I think this is a bug. At least it doesn't seem to have been designed deliberately.
Fixing it only for XSLT will be fine. It's appreciated if you can leave a brief comment, for the record, about why fixing XQuery isn't straightforward.

**Comment by galtm** [comment]
Here is what I have in mind on the XSLT side: For each element in the XSpec file that has a namespace declaration, copy the declarations where needed, to either the compiler output or the compiler's intermediate parameters. There is already a `mode="x:copy-namespaces"` template in `generate-common-tests.xsl`, and I am looking to broaden that template's `@match` attribute. I'm not sure yet whether namespace declarations located in imported XSpec files will require additional considerations.


> brief comment, for the record, about why fixing XQuery isn't straightforward.

I don't think this declaration-copying approach will work for XQuery because the compiled XQuery file won't have XML elements in all the right places that can carry the namespace declarations. Copying all namespace declarations from the entire XSpec file to the top of the compiled XQuery file won't work, because they might conflict with each other when placed at the same scope. Maybe it is possible to use URI-qualified names in the compiled XQuery file wherever there isn't a spot where a prefix (used in the XSpec file) can be bound to the URI. However, I think it'll be significantly more work than the XSLT approach and there could be barriers I haven't thought of.

**Comment by AirQuick** [comment]
Thanks for the useful comment. It surely sounds difficult to handle XQuery.

**Comment by AirQuick** [comment]
XSLT has been fixed.
Not fixed XQuery yet. It will require significantly more work than XSLT. (https://github.com/xspec/xspec/issues/598#issuecomment-528326808) Please feel free to reopen this, if anyone can propose a fix for XQuery.
