### ISSUE TITLE
test/*.xspec files violate schema

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#60]
[***.xspec** files](https://github.com/xspec/xspec/tree/ba5f97c903d0022d322d7af7e379b6fbcaf35ee6/test) do not pass validation with [**xspec.rnc**](https://github.com/xspec/xspec/blob/07c0c60ff9a8cd7c6e8623ba797e906ce1a84746/src/schemas/xspec.rnc).
```
Main validation file: ...\test\xspec-variable.xspec
Schema: ...\src\schemas\xspec.rnc
Engine name: Jing
Severity: error
Description: element "t:variable" not allowed here; expected element "t:import", "t:param", "t:pending" or "t:scenario"
```
Schema or *.xspec, which one is correct?
The essentially same question raised in #59. Filing this issue to address it explicitly.

**Comment by AirQuick** [comment]
List of validation errors:

* Undefined `variable` element is used
  * generate-tests-utils.xspec
  * xspec-rule.xspec
  * xspec-variable.xspec

* Undefined `apply` element is used
  * xspec-rule.xspec

* Label is missing from `expect` (this seems to be just a bug of .xspec file)
  * xspec-result-naming-collision.xspec

**Comment by cirulls** [comment]
I confirm there are inconsistencies between the test suite and the RNG Schema. 

@AirQuick : are you fine if we address this in v0.6.0? What is your take on these missing elements? Shall we include them in the RNG Schema?

**Comment by AirQuick** [comment]
I'm fine with 0.6.

What is the current development status of  `variable` and `apply`? I'm relatively new to XSpec and didn't notice the elements until recently 😮 
For `variable`, [Wiki](https://github.com/xspec/xspec/wiki/Compilation#variables) says, "This is not implemented yet". So what is the current status and plan?
The `apply` element is also briefly mentioned in the same [Wiki](https://github.com/xspec/xspec/wiki/Compilation#sut). Does it imply it's still an experimental feature?

**Comment by galtm** [comment]
I would like to add some support for XSpec variables in XSLT tests, and before creating a new issue I looked to see if there was already one. I found this issue, which has some overlap with what I was planning. Here is what I had in mind for my work:

1. Add x:variable to the RelaxNG schema. (That's included in this issue, but this issue also suggests other RNG changes.)

2. Enhance src/compiler/... files where needed, to support variables. I think the support is mostly there, but some patterns didn't work that I expected to work. A "TODO" comment in test/xspec-variables.xspec also suggests that the back end support for variables is not quite finished.

3. Enhance test/xspec-variable.xspec to cover more cases that use XSpec variables.

4. Maybe add something to test/generate-xspec-tests.xspec to cover the specific tweaks from item 2? I'm not exactly sure what the vision is for this file. I'm still looking over the existing test files to see how they are organized.

Should I create a new issue for my work, and mention in this one that the `variable` element is being covered in the new issue?

**Comment by cirulls** [comment]
@galtm: thanks for being willing to work on this. If you can, please use this existing issue for tracking and discussing your work, I'm going to re-assign the issue to you (you should have received an invite via GitHub, accept it so I can re-assign the issue). When you think you are ready with the code, please submit a [new pull request](https://github.com/xspec/xspec/pulls) with your changes. Make sure you work from the latest version of `master` as several pull requests were recently merged and I'm planning to merge more in the next days. You can also run the test suite on your machine before submitting a pull request (there is some documentation for Windows [here](https://github.com/xspec/xspec/issues/117#issuecomment-415974380)), but don't worry if you can't, our CI systems Travis and AppVeyor will automatically run the test suite when you submit a pull request.  

Regarding the work you sketched, feel free to submit a pull request containing 1, 2, and 3 (you can omit 4 for now, better to get a review on the major changes first).

@AirQuick: does any of your outstanding pull requests address this issue? I don't think so but I thought I'd better check.

**Comment by AirQuick** [comment]
> @AirQuick: does any of your outstanding pull requests address this issue?

No, they don't change `x:variable`.

**Comment by AirQuick** [comment]
#### Some random thoughts

* `x:variable` seems useful. Completing its functionality will be appreciated.
* We can discuss what to do with the details of `x:variable` in a new pull request.
* I hope the pull request doesn't collide with [my latest pull request branch](https://github.com/AirQuick/xspec/tree/test-deps-2018-12-04) so much. My branch is way too ahead of the current master. If the pull request contains substantial changes, I'm not sure if I can merge it to [my 130+ pull requests](https://github.com/xspec/xspec/pulls/AirQuick).
* If `x:variable` is implemented well in XSLT, I hope it gets implemented in XQuery as well by the same developer at the same time. That would reduce the total development cost greatly. I recently fixed [some XQuery issues](https://github.com/xspec/xspec/pulls?utf8=%E2%9C%93&q=is:open+is:pr+author:AirQuick+XQuery) and found the current XQuery implementation kind of messy, because of XQuery's nature (XSpec compiler has to output literal text statements).
* [Wiki](https://github.com/xspec/xspec/wiki/Compilation#variable-value) says, "...one using `@select`, one using content, and one using `@href`. As with xsl:variable, they must use one and exactly one of these attributes." I think it's wrong. `@select` should be able to work with content or `@href`


#### Further work
`x:variable` is dispatched to `mode="test:generate-variable-declarations"` template, so `x:variable` will automatically fulfill the following features and thus should be tested.

* `x:variable/@name` should be EQName (#456) and should be added to the EQName test (#455).
* `xspec-variable.xspec` should be removed from the schema test exclusion list (#363).
* `x:variable/@href` should precede `x:variable/node()` (#307).
* `x:variable/@as` should be tested just like `x:param/@as` tested in (#349).
* `x:variable` should not hardcode `x:` (#472).
* `x:variable/node()` should handle whitespace-only text node (#352, #417)

**Comment by galtm** [comment]
@cirulls and @AirQuick, thanks for your comments, which were valuable. I'll use this issue for my work.

Regarding colliding with your 130+ pull requests, should I wait until those have been integrated into the master branch, and then do my work off the new master branch? While I'm waiting, I can get up to speed on the implementation of XSpec for XQuery.

About the wiki being wrong, I believe you are correct. Would it work to change "As with xsl:variable, they must use one and exactly one of these attributes." to something like, "Content and `@href` are mutually exclusive. The `@select` attribute can appear alone or in combination with either content or `@href`."? I will plan to include testing for the combination of `@href` with `@select` and the combination of content with `@select`.

**Comment by cirulls** [comment]
> Regarding colliding with your 130+ pull requests, should I wait until those have been integrated into the master branch, and then do my work off the new master branch?

@galtm: I'm trying to review at least one pull request a day so if you wait it may take a while before you even start working on it. I would suggest to create a branch from the current `master` branch of XSpec, do your work in your branch, and regularly update your branch with what is merged daily on `master` (this process is called a [git merge or git rebase](https://www.atlassian.com/git/tutorials/merging-vs-rebasing), I can help out if you are not familiar with it). This would also allow to review your future pull request more quickly as it will contain everything that is in `master` (hopefully @AirQuick can review it instead of me). Does this sound ok?

**Comment by galtm** [comment]
@cirulls: OK, that sounds fine.

**Comment by AirQuick** [comment]
> Would it work to change "As with xsl:variable, they must use one and exactly one of these attributes." to something like, "Content and @href are mutually exclusive. The @select attribute can appear alone or in combination with either content or @href."?

And "As with xsl:variable" may be revised as "As with x:param". I updated Wiki.

**Comment by AirQuick** [comment]
> Maybe add something to test/generate-xspec-tests.xspec to cover the specific tweaks from item 2? I'm not exactly sure what the vision is for this file. I'm still looking over the existing test files to see how they are organized.

I think `test/generate-xspec-tests.xspec` is only for very low-level verification. That is, `test/generate-xspec-tests.xspec` verifies the XSLT snippet generated by the XSpec compiler (`generate-xspec-tests.xspec`). In most cases, I don't think you need to test such low-level details.

**Comment by AirQuick** [comment]
> Regarding colliding with your 130+ pull requests, should I wait until those have been integrated into the master branch, and then do my work off the new master branch?

It's pretty much ok for you to start developing on top of the current master and submit the pull request right now.

If and only if the change conflicts with [my latest pull request branch](https://github.com/AirQuick/xspec/tree/test-deps-2018-12-04) substantially, I would like to ask merging `x:variable` after my branch, not only because of the collision but also because my branch has more tests ([177 tests](https://ci.appveyor.com/project/xspec/xspec/builds/20823611)) compared to the current master ([91 tests](https://ci.appveyor.com/project/xspec/xspec/builds/20856704)).

**Comment by AirQuick** [comment]
> While I'm waiting, I can get up to speed on the implementation of XSpec for XQuery.

If you don't mind XQuery personally much (I actually don't... 🙄 ), I think you can forget about it at the moment and just implement XSLT now. (XSpec for XQuery is far from maturity anyway; even `x:expect[@test][@select]` [doesn't work](https://github.com/xspec/xspec/issues/440).) 
But, even in that case, it is very much appreciated if you could *try* implementing XQuery immediately after implementing XSLT and at least leave some comments to clarify what to do next for completing `x:variable` on XQuery.

**Comment by AirQuick** [comment]
The only remaining issue is this:

> * Undefined `apply` element is used
>   * xspec-rule.xspec

and it's commented out property with `TODO` comment:

https://github.com/xspec/xspec/blob/4a3ae575b55e785099582d13942831279b4f3ee1/test/end-to-end/cases/xspec-rule.xspec#L31-L58

So I think we can close this issue. Implementing `x:apply` should be handled in a dedicated issue or pr.

**Comment by AirQuick** [comment]
> Implementing `x:apply` should be handled in a dedicated issue or pr.

#1459 removes `x:apply` code.
