### ISSUE TITLE
Automatically generate release notes

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#601]
I have been looking at ways to automatically generate release notes. I usually add a note to the draft release notes every time a pull request is merged. However, this process is very manual and it requires following the activity on the master branch (which I do but sometimes I have breaks of few weeks and lots of GitHub notifications to process). 

I tried out the [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator/) which is a tool for automatically generating changelog. It looks like it has [several options](https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples) and it is fairly well documented. I was able to generate a changelog of all our releases (including the upcoming v1.4.0) with a single command from my machine, I include the changelog in the next comment to give an idea. The result is not as good as manually curated release notes but it takes a fraction of the time it usually takes me to compile release notes.  

I wonder if this could be of any use and if it is worth playing with github-changelog-generator (or other tools) to generate automatically these release notes rather than compiling them by hand. Or alternatively if it is a good complement to release notes (maybe the CHANGELOG could feature in the master branch to keep track of all the changes across releases). 

Any feedback or suggestion is welcome!

**Comment by cirulls** [comment]
I'm attaching the file here below, it is a Markdown file but I had to change the file extension, it looks like GitHub doesn't allow to upload .md file.

[CHANGELOG.md.log](https://github.com/xspec/xspec/files/3580274/CHANGELOG.md.log)

For my own record, I generated the release notes with this command:

```
github_changelog_generator
```

with the following configuration stored in `.github_changelog_generator`:

```
user=xspec
project=xspec
token=my_private_token_here
future-release=v1.4.0
enhancement-label="**New features and enhancements**"
bugs-label="**Bug fixes**"
issue-line-labels=enhancement,bug,test,documentation
max-issues=1000
```

**Comment by AirQuick** [comment]
Looks very useful. I understand how tedious to maintain the list by hand. Especially when it's a table.

A downside would be that it doesn't contain additional contributors. Your handpicked list always have them along with the pr author names, which is very nice. I don't think this downside is a showstopper, though.

**Comment by cirulls** [comment]
@AirQuick: Thanks for your feedback. For release v1.4.0 I will use my handpicked draft release notes but I will experiment with the automatic generated changelog for v1.5.0. github-changelog-generator does not seem to have an option for pulling out all the contributors in a pull request but I'll investigate if there is a way to add them. 

I'll shortly raise another issue which may help keeping the commit log clean and help parsing release notes automatically.

**Comment by AirQuick** [comment]
Generating release notes is fully automated as of v1.6.0. The generator is a simple XSLT stylesheet which I'd be happy to share. Unfortunately I can't share it, for the stylesheet includes some closed libraries.
