### ISSUE TITLE
test:* elements in src/compiler/generate-tests-utils.xsl

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#62]
src/compiler/generate-tests-utils.xsl has some `test:*` elements such as [this](https://github.com/xspec/xspec/blob/8931b371bd619feeeee25bd7014d8a677ab88505/src/compiler/generate-tests-utils.xsl#L79-L120).
What are they for?
Are they to be migrated to [generate-tests-utils.xspec](https://github.com/xspec/xspec/blob/master/test/generate-tests-utils.xspec)?

**Comment by cirulls** [comment]
@AirQuick : Is this now fixed by the merge in #83 (commit https://github.com/xspec/xspec/commit/120b3316aef2c1106287dc7c5270f3ed49062c68)?

**Comment by AirQuick** [comment]
It's still unclear what they are for. They exist in the initial [commit](https://github.com/xspec/xspec/commit/54f6e15de57cf90d8180cf1896f159d9948d61ed#diff-f3d9cf7431a4f91e794fd0a66c026a33). Perhaps they are for testing XSpec using Jeni's old [framework](http://www.jenitennison.com/xslt/utilities/unit-testing/)...?
Whatever they are, I don't see a reason to retain them once they are copied to `test/*.xspec`. I'll submit a pull request to remove them for simplifying the source code.

**Comment by cirulls** [comment]
I don't know either why they are in there but it makes much more sense to migrate them to the test folder so that they can be executed by the automated test suite.
