### ISSUE TITLE
Conventions for commit messages and pull requests

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#622]
In order to facilitate the automatic generation of release notes (see #601) and to enforce conventions in commit messages and pull requests, it could be useful to implement a commit linter. This is an automatic check that makes sure that commit messages and pull request follow a convention. Here are [some reasons](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#why-use-conventional-commits) for using a commit linter for open source projects.

I implemented [Commit Lint](https://www.commit-lint.com) on one of my personal repositories in order to give an idea on how it works and looks like. Commit Lint enforces a commit message convention (I chose [Angular](https://www.commit-lint.com/conventions)) and shows a green flag if the commit message and pull request title conform to the convention or a red flag if they break it.

Here is an example of a [successful](https://github.com/cirulls/vimrc/pull/1) commit message and pull request title (note `feat:` in the commit message and pull request title):

![image](https://user-images.githubusercontent.com/13256236/64549898-9cd78280-d329-11e9-8e2f-3c9c639fa87f.png)

Here is an example of a [failed](https://github.com/cirulls/vimrc/pull/2) commit message and pull request title (no type specified in the commit message):

![image](https://user-images.githubusercontent.com/13256236/64549931-b4af0680-d329-11e9-93c7-f0f4ac337883.png)

Here are [some examples of commit messages](https://github.com/angular/angular/commits/master) following the Angular convention. The list of types in a commit message (i.e. the start of a commit message) is [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type). 

Do XSpec maintainers and contributors think it could be useful to implement this in the xspec repo? I can easily implement it but I would like to get your feedback first since this will have an impact on how pull requests are raised.

I also think it would be good to write a `CONTRIBUTING.md` page describing how to contribute to XSpec (at the moment we only have two paragraphs in the README file). Technicalities like the commit lint and the CI could also feature in such a page. Again, I'm happy to prepare a draft.

**Comment by AirQuick** [comment]
Nice idea. Will it work well with our squash-and-merge strategy?

Establishing `CONTRIBUTING.md` sounds good too.

**Comment by cirulls** [comment]
I think so, here is an example of how it will look like when doing a squash-and-merge:

![image](https://user-images.githubusercontent.com/13256236/64630555-47fd4000-d3ed-11e9-968d-0077d0f8c594.png)

As long as the maintainer doesn't change the main commit message after the commit lint checks, that should work and stay green. I will also write down instructions on how to amend a commit message already pushed to GitHub, this will happen a lot for new contributors.

**Comment by AirQuick** [comment]
Thanks for the image.

Will it require every commit contained in a PR to follow the convention? For example, #138 consists of 13 commits. If all the 13 commits must follow the convention, it might be too stern. Also, if we do squash-and-merge in the end, each commit is not that important.

**Comment by cirulls** [comment]
No, only the last commit (and the PR title) must follow the convention. I tried amending my broken commit message in https://github.com/cirulls/vimrc/pull/2 and it looks like this:

![image](https://user-images.githubusercontent.com/13256236/64632258-a8da4780-d3f0-11e9-9cc5-a445e20c1a9d.png)

Note that it shows the first commit as red because of breaking the naming conventions but the last commit and final check result are green.

**Comment by AirQuick** [comment]
Great.

`xslt`, `xquery` and `schematron` might be good candidates for the `scope`.

**Comment by AirQuick** [comment]
Assuming we take the Angular convention, do you have any proposal for the details, @cirulls?
If you have, we can follow it for v1.6.0.

**Comment by cirulls** [comment]
@AirQuick: I submitted #756 with an initial draft for contributing guidelines, it contains conventions and examples for git commit messages following the Angular conventions. Feel free to comment directly in that pull request.
