### ISSUE TITLE
Schematron 'expect nothing unexpected' option?

### ISSUE THREAD

**Issue by tgraham-antenna** [xspec/xspec#670]
Schematron testing currently checks only specific `assert` or `report` or checks whether any error- or fatal-level `assert` or `report` has fired.  Other than the checking by error level, there is no reporting of an unlisted `assert` or `report` being fired.

This can be a feature, since a `scenario` can be written to check just one thing, but it can also be a hindrance, since an unexpected `assert` or `rule` can indicate a problem with the Schematron or with your understanding of the data and/or Schematron.

I check my XSpec test files against the Schematron using Oxygen to make sure that I am testing what I think I'm testing.  Yesterday, I had an unexpected `assert` with one of my files that turned out to be a bug in my Schematron.

If there was an 'expect nothing unexpected' option, then I would need to do fewer checks in Oxygen and I could write more tests in the same time and could potentially find more bugs sooner.

For this test document:

````
<!-- Unrecognized PI -->
<?unknown?>
<test/>
````

and this Schematron:

````
    <rule context="processing-instruction()[not(name() = ('a', 'b'))]">
      <assert test="name() = ('a', 'b')" role="error"
	      id="unknown-pi"
	>Unknown processing instruction type: '<value-of select="name()"/>'</assert>
      <assert test="exists(saxon:get-pseudo-attribute('bogus')[. ne ''])" role="error"
	      id="bogus"
	>Needs a 'bogus' pseudo-attribute: '<value-of select="name()"/>'</assert>
    </rule>
````

this XSpec passes because it checks only one of the two `assert`:

````
    <x:scenario label="pi-05">
        <x:context href="pi-05.xml"/>
        <x:scenario label="Only known PIs should be present">
            <x:expect-assert id="unknown-pi"/>
        </x:scenario>
    </x:scenario>
````

Maybe I wrote the second `assert` later. (Which I did, just to make this example.)  I don't currently have a check for it.  Checking by error level wouldn't help, since they are both `error`.

I would like to have the option of having XSpec save me from myself by reporting when there is an `assert` or `report` that I was not expecting.

**Comment by AirQuick** [comment]
To achieve that using the current implementation, one could possibly write like this?

```xml
<x:scenario label="Only known PIs should be present">
	<x:expect-assert id="unknown-pi" />
	<x:expect-assert count="1" />
</x:scenario>
```

**Comment by AirQuick** [comment]
@vincentml 
Any thoughts?

**Comment by tgraham-antenna** [comment]
'count' does not show in https://github.com/xspec/xspec/wiki/Writing-Scenarios-for-Schematron, so I didn't know about it.

It could be a workaround, thank you, though presumably it would also require `<x:expect-assert count="0" />` in scenarios as well.

**Comment by vincentml** [comment]
The suggestion by @AirQuick is exactly what I would do for this kind of test. 

An expect-assert to check for the specific assert with an id:

`        <x:expect-assert id="unknown-pi"/>`

and an expect-assert to check that only the expected number of asserts are thrown, in this case 1 is expected:

`        <x:expect-assert count="1"/>`

**Comment by tgraham-antenna** [comment]
Now that I know about `count`, that is sufficient.

**Comment by AirQuick** [comment]
[Updated](https://github.com/xspec/xspec/wiki/Writing-Scenarios-for-Schematron/_compare/1bef2e0b2898a166cc43157f7b9bf498fdeab6bb...a90ee8f9c8f6554dfe4bab9790ace2eab2ea2da4) Wiki to mention `@count` based on this use case. Feel free to edit further.
