### ISSUE TITLE
Test fails in 1.4 but worked in 1.2

### ISSUE THREAD

**Issue by tofi86** [xspec/xspec#691]
I'm sorry, but I just cannot find the error.
This test (see attached zip) worked in XSpec 1.2 but fails in 1.4.

[xspec-test.zip](https://github.com/xspec/xspec/files/3778463/xspec-test.zip)

Can you help me debugging this issue? Thanks!

Best, Tobias

**Comment by AirQuick** [comment]
v1.3.0 fixed a bug where whitespace-only text nodes are ignored when comparing the actual result and the expected result. [Relnote](https://github.com/xspec/xspec/releases/tag/v1.3.0):

> * Handling whitespace-only text nodes has been fixed and [documented](https://github.com/xspec/xspec/wiki/Writing-Scenarios#whitespace-only-text-nodes) (#346, etc.)

In your test case, the actual result and the expected result have different whitespace-only text between elements. They used to be ignored on comparison. v1.3.0 or later no longer ignores them.

Assuming the tested function (`pa:resolve_metadata`) is returning the correct result including whitespace-only text nodes, there are two possible ways to make the test case work:

1. Do not use `@href` in `x:param` and `x:expect`. Write the parameter and the expectation XML snippets directly in `x:param` and `x:expect`. For example,

    ```xml
    <x:call>
        <x:param select="//parsx:meta">
            <projekt ...>
            ...
            </projekt>
        </x:param>
    </x:call>
    <x:expect>
        <ausgabe>
        ...
        </ausgabe>
    </x:param>
    ```

    In this case, the whitespace-only text nodes are discarded in the first place when the snippets are loaded.

1. Continue using `@href`. Write the *exact* whitespace-only text nodes in the external XML files referenced by `@href`. For example, if you keep `source.xml` as it is, `expected.xml` would be
    ```xml
    <ausgabe id="ausgabe-1" name="E-Book" typ="ebook" xmlns="https://www.parsx.de/ns/4.0"><auspraegungen>
    					<auspraegung id="ausgabe-1_auspraegung-1" name="E-Book: EPUB (generierter Name)"/>
    				</auspraegungen><kennungen>
    					<kennung typ="isbn">978-3-498-02065-2</kennung>
    				</kennungen><untertitel>...
    ```

**Comment by tofi86** [comment]
Thanks for the hint! It workes now.

Any chance to add some kind of setting to ignore whitespace when loading input/expected data via `@href` from external files?

**Comment by AirQuick** [comment]
> Any chance to add some kind of setting to ignore whitespace when loading input/expected data via `@href` from external files?

I haven't tested it extensively, but enabling Saxon option `RECOGNIZE_­URI_­QUERY_­PARAMETERS` and adding Saxon-specific `?strip-space=yes` to the URI seems to strip all the whitespace-only text nodes from the specified doc:

```console
C:\test>set saxon_cu
SAXON_CUSTOM_OPTIONS=--recognize-uri-query-parameters:true

C:\test>find "strip-space" metaCascade.xspec

---------- METACASCADE.XSPEC
                                <x:param name="meta" select="document('../resolve_metadata/source.xml?strip-space=yes')//parsx:meta" as="element()"/>
                        <x:expect label="Erfolgreich: Metadaten von 'ausgabe-1' aufgelﾃｶst" href="./resolve_metadata/expected.xml?strip-space=yes" select="parsx:ausgabe"/>

C:\test>C:\xspec\tags\v1.4.0\bin\xspec.bat metaCascade.xspec
...
Testing with SAXON HE 9.9.1.5
...
passed: 1 / pending: 0 / failed: 0 / total: 1
...
```
