### ISSUE TITLE
V 1.1.0 published on maven does not contain XSLTCoverageTraceListener.class

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#730]
Release 1.1.0 published on maven does not contain XSLTCoverageTraceListener.class. It was an error, and as people rely on it, it should be corrected.

Solution is to extract tag: v1.1.0, commit #2dba695, create a maintenance branch on this, modify pom to correct jar content, and publish a V 1.1.1 on maven central, which is just a patched V1.1.0 with class added.

I'll send a PR, but I also will publish the V1.1.1 on maven central, as there is a strong requirement in xspec-maven-plugin use. As it is only a patch, it's not required to include it in main repo. And this patch already exist in master branch.

**Comment by AirQuick** [comment]
v1.2.0 or later doesn't serve your use case?

**Comment by cmarchand** [comment]
Well, I have a xspec-maven-plugin release that has a dependency on 1.1.0-SNAPSHOT, which include XSLTCoverageTraceListener class. But I have no idea of when this SNAPSHOT has been build. I'd like to replace it by a 1.1.1 but xspec API has changed between.

Maybe I was too quick to create issue. I would like to create issue before sending PR, but I'm not sure I'll send a PR for this. It's a special release of xspec-maven-plugin, that has been created only for my company, and the SNAPSHOT has been removed from Nexus....

I'll probably close this issue, but keep it open for now, just to trace...

**Comment by cmarchand** [comment]
So.  I solved this by creating a 1.0.9 from a 1.1.0-SNAPSHOT jar I had in my local repo. The commit used to generate this SNAPSHOT was no longer in my repos.
Problem solved. Forget it.
