### ISSUE TITLE
ID in report HTML is not unique

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#78]
**test.xsl** (does nothing)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" />
```

**test.xspec** (just fails)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description stylesheet="test.xsl" xmlns:x="http://www.jenitennison.com/xslt/xspec">
	<x:scenario label="Test scenario">
		<x:context />
		<x:expect label="Must fail" test="false()" />
	</x:scenario>
</x:description>
```

This scenario generates a report HTML like this:
```xhtml
      <div id="d3e4">
         ...
         <h3 id="d3e4">Test scenario</h3>
```

The `id` values are not unique.

(Personally I do not need to have this issue fixed right now. I just needed to file an issue for recording the fact.)

**Comment by vincentml** [comment]
My initial attempt to fix this broke the link target highlighting that was introduced in #79
