### ISSUE TITLE
XSLT Code Coverage report uses excessively small font in some browsers

### ISSUE THREAD

**Issue by galtm** [xspec/xspec#796]
When I generate a code coverage report using the XSLT Code Coverage transformation scenario in the XSpec project, the font size of the XSLT code appearing in the report looks too small in certain browsers. The screen capture shows Chrome (fairly small), Firefox (even smaller), and Edge (looks good) on Windows.

![codecoveragereport](https://user-images.githubusercontent.com/40716346/74971514-3d0ff800-53ee-11ea-901a-65e8fe93adc1.png)

Reports I generated while reviewing #738 show the same problem. Maybe I just didn't notice. Reports I generated from a significantly older XSpec version look fine, suggesting that this isn't caused by a change in browsers, hardware, or other things external to XSpec.

**Comment by AirQuick** [comment]
This may be related to #388 .
`src/reporter/test-report.css` probably made some assumption about `font-family` when specifying `font-size`. #388 probably broke that assumption. (Such assumption does not work across platforms anyway.)
