### ISSUE TITLE
Useless href in report HTML 

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#85]
**test.xsl** (does nothing)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" />
```

**test.xspec** (pending)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description stylesheet="test.xsl" xmlns:x="http://www.jenitennison.com/xslt/xspec">
	<x:scenario label="Test scenario" pending="not yet implemented" />
</x:description>
```

This scenario generates a report HTML like this:
```xhtml
            <tr class="pending">
               <th>(<strong>not yet implemented</strong>) <a href="#d3e4">Test scenario</a></th>
               <th></th>
            </tr>
```

`<a/>` is defined with `href`, but its link target does not exist. (No element has `id="d3e4"`.)

(Personally I do not need to have this issue fixed right now. I just needed to file an issue for recording the fact.)

**Comment by cirulls** [comment]
I tried this out and confirm this seems to be a bug, the `href` is produced and it is useless. This also occurs when the pending scenario contains other blocks like `<x:expect>`. I guess it has lower priority but I file it as a bug for now.
