### ISSUE TITLE
Allow selection of Schematron phase

### ISSUE THREAD

**Issue by yamahito** [xspec/xspec#851]
Feature request to allow control of which phase is being tested - perhaps a root attribute like @schematron-phase?

**Comment by vincentml** [comment]
Hi @yamahito 

This can already be done by including a param element :

```
<x:param name="phase">thephase</x:param>
```

**Comment by yamahito** [comment]
Nice!  I can see it is documented under 'writing tests', which I missed initially.  Sorry!

**Comment by AirQuick** [comment]
You may also need `x:param` when you have to test [Schematron with text nodes](https://github.com/xspec/xspec/wiki/Testing-Schematron-with-Text-Nodes). Just FYI.
