### ISSUE TITLE
Ignore certain nodes in expected results

### ISSUE THREAD

**Issue by tofi86** [xspec/xspec#87]
From the [oXygen webinar](https://www.oxygenxml.com/events/2017/webinar_unit_testing_xslt_with_xspec_and_oxygen.html):
> Is it possible to ignore certain nodes/values from the expected results?

Nice feature request! Add an `@ignore` attribute to be able to ignore certain nodes...

**Comment by AirQuick** [comment]
I thought so, too. The use case wasn't that clear though.
For some cases, [three dots (`...`)](https://github.com/xspec/xspec/wiki/Writing-Scenarios#expectations) would help.

**Comment by tofi86** [comment]
> For some cases, three dots (...) would help.

Does this work for Attribute values as well?



> The use case wasn't that clear though.

You may have a chunk of XML you'd like to compare which contains generated IDs or the like. And they should be ignored when comparing the expected result...

**Comment by tofi86** [comment]
> For some cases, three dots (...) would help.

BTW: I didn't even know this functionality exists! This is awesome! You should highlight it on the wiki page!

**Comment by AirQuick** [comment]
> Does this work for Attribute values as well?

I tried it just now. This result

```xml
<foo bar="baz">
  <qux><quux /></qux>
</foo>
```

matches this expectation

```xml
<foo bar="...">...</foo>
```
So I think the feature is working for the attribute values as well. Does it cover your use case?

> BTW: I didn't even know this functionality exists! This is awesome! You should highlight it on the wiki page!

Quite agreed. I didn't notice the feature until a few months ago. 😮

**Comment by tofi86** [comment]
@georgebina @AlexJitianu the "ignore" feature is already built in in XSpec! See comments in this thread!

I think we can close the issue as the use case requested in the webinar is already covered...
Do you agree?

**Comment by AirQuick** [comment]
Looks like right now we don't have a dedicated test file for the three dots feature. I'll add it. Hopefully it will also serve as a feature example.

**Comment by mmh-docufy-de** [comment]
Hi, I was asking this during the webinar. And I learned from a colleague afterwards about the three dot feature. The example above is pretty impressive. 
What seems not to be covered by this are optional attributes, in a situation where it does not matter if they are present or not. 
I guess I would rather withdraw this idea and write more precise tests; I plan to know more about my data :-)
Anyway, thanks for picking this up so quick!

**Comment by georgebina** [comment]
Yes, I agree, this solves most use cases.
For more complex cases one can use another stylesheet that imports the original one and filters the result as needed, then test that. For example, if we have a stylesheet `test.xsl` that just copies the XML to the output:

```xml
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    version="2.0">
    <xsl:template match="node() | @*">
        <xsl:copy>
            <xsl:apply-templates select="node() | @*"/>
        </xsl:copy>
    </xsl:template>
</xsl:stylesheet>
```

and we want to ignore "xml:*" attributes when we test, then we can use something like `testDriver1.xsl`:

```xml
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    version="2.0">
    <xsl:import href="test.xsl"/>
    
    
    <xsl:template match="/">
        <gigi>TEST</gigi>
    </xsl:template>
    
    <xsl:template match="/*" mode="test">
        <xsl:variable name="result">
            <xsl:apply-templates select="." mode="#default"/>
        </xsl:variable>
        <xsl:apply-templates select="$result" mode="filter"/>
    </xsl:template>
    
    <xsl:template match="node() | @*" mode="filter">
        <xsl:copy>
            <xsl:apply-templates select="node() | @*" mode="filter"/>
        </xsl:copy>
    </xsl:template>
    <!-- remove all attributes from the XML namespace -->
    <xsl:template match="@xml:*" mode="filter"/>
</xsl:stylesheet>
```

and in the XSpec we can use

```xml
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec" 
    stylesheet="testDriver1.xsl">
    <x:scenario
        label="Scenario for testing template with match '/'">
        <x:context mode="test">
            <test xml:id="idF4Fdfd84F" xml:base="sample/">
                <value>78</value>
            </test>
        </x:context>
        <x:expect label="Check result to the the same, except the xml:* attributes">
            <test>
                <value>78</value>
            </test>
        </x:expect>
    </x:scenario>
</x:description>
```

Hope this helps!
George

**Comment by mmh-docufy-de** [comment]
Thx a lot, George!

**Comment by AirQuick** [comment]
> Looks like right now we don't have a dedicated test file for the three dot feature. I'll add it. Hopefully it will also serve as a feature example.

I dumped working and nonworking examples and added them to one of the pending pull requests:
* [Scenarios](https://raw.githubusercontent.com/AirQuick/xspec/b0cf299091b517c95f18225b8799df3225b8e98e/test/end-to-end/cases/xspec-three-dots.xspec)
* Their [results](http://htmlpreview.github.com/?https://raw.githubusercontent.com/AirQuick/xspec/b0cf299091b517c95f18225b8799df3225b8e98e/test/end-to-end/cases/expected/xspec-three-dots-result-norm.html)

**Comment by AirQuick** [comment]
Closing this.

To sum up,
* Three dot features is documented in [Wiki](https://github.com/xspec/xspec/wiki/Writing-Scenarios#expectations)
* Three dot feature is in automated tests: [Test](https://github.com/xspec/xspec/blob/master/test/end-to-end/cases/xspec-three-dots.xspec), [Result](http://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/master/test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html)
* For more complicated filtering, you can use a technique (wrapper test driver) introduced in https://github.com/xspec/xspec/issues/87#issuecomment-283307085
