### ISSUE TITLE
Stylesheets with global variables not supported?

### ISSUE THREAD

**Issue by willemvlh** [xspec/xspec#873]
When I have a stylesheet with global variables that refer to nodes in the source document, Saxon returns a compilation error:
```
run-xslt-test:
     [echo] Running XSLT Tests...
     [java] Testing with SAXON EE 9.8.0.12
     [java] Test
     [java] Error at char 1 in xsl:variable/@select on line 11 column 196 of GFK.xsl:
     [java]   XPDY0002: The context item for axis step root/broadcastdays is absent
     [java] The context item for axis step root/broadcastdays is absent
```
I see that after the initial xspec compilation, the test itself is invoked with xsl:initial-template, so there is no obviously no context. Is this a limitation? Or is it possible to set some kind of default input document?

**Comment by AirQuick** [comment]
It is a limitation at the moment. The tested stylesheet is invoked with no source document.
For some reason I don't know, the source document is not defined in the [XSpec schema](https://github.com/xspec/xspec/blob/master/src/schemas/xspec.rnc).

A possible workaround would be rewriting your styleseet
```xslt
   <xsl:variable name="global-var" select="root/broadcastdays" />
```
with `xsl:param` which is `/` by default
```xslt
   <xsl:param name="source-doc" select="/" />
   <xsl:variable name="global-var" select="$source-doc/root/broadcastdays" />
```
and providing `$source-doc` from XSpec:
```xspec
   <x:param name="source-doc" href="uri/of/source/doc.xml" />
```

**Comment by AirQuick** [comment]
#892 provides some ways of setting the global context, although it has its own weirdness. For details, see the **Global context item where global xsl:param and xsl:variable are evaluated** section in the pull request description.

**Comment by dwcramer** [comment]
What if the URI of the resource is the thing you want to resolve?
