### ISSUE TITLE
Passing multiple catalogs to the XSpec ANT transformation

### ISSUE THREAD

**Issue by AlexJitianu** [xspec/xspec#898]
Hi,

A common user of Oxygen and XSpec was asking if the catalogs configured in Oxygen are passed automatically to XSpec. The XSpec framework in Oxygen uses the ANT transformation so we rely on the `catalog` property which at first glance looks like it has to be just one file path. In Oxygen, there is an editor variable named `${xmlCatalogFilesList}` that expands to a comma separated enumeration of catalogs URLs.

Do you think it makes sense to enhance the `catalog` property to support such enumerations? Because if it did, then Oxygen's transformations could make use of `${xmlCatalogFilesList}` and the user would automatically benefit from the already configured catalogs. Or do you see another solution?

Thanks,
Alex

**Comment by AirQuick** [comment]
Sounds reasonable.
* The current `build.xml` converts `catalog` to `xspec.catalog.url` in order to work around a Saxon [bug](https://saxonica.plan.io/issues/3025#note-8) which is not fixed on Saxon 9.7. After we throw away Saxon 9.7 ([soon](https://github.com/xspec/xspec/issues/891)), we won't need the conversion. By removing the conversion, `catalog` should work just fine with `${xmlCatalogFilesList}`. (I haven't tested it, though.)
* Per another Saxon [bug](https://saxonica.plan.io/issues/3935), the semicolon separated list requires Saxon 9.8.0.15 or later. Oxygen ~21.x bundled with older Saxon versions may have a problem. Still, such users can duplicate and edit the transformation scenario.

**Comment by AirQuick** [comment]
Unfortunately this may not be an instant task. Ant [`catalogpath`](https://ant.apache.org/manual/Types/xmlcatalog.html) seems to accept only native paths, whereas `${xmlCatalogFilesList}` is a collection of URLs possibly including non `file:` one.

**Comment by AirQuick** [comment]
So I have implemented this feature as follows. If this is fine, I'll create a pull request after releasing v1.6.0.
* Default `catalog` property in `xspec.framework` is now `${xmlCatalogFilesList}`.
* Introduce a new Ant property `catalog.is.uri`
  * Default `false` in `build.xml`.
  * Default `true` in `xspec.framework`.
  * Will not be documented in Wiki for the time being.
* If `catalog.is.uri` is true, `build.xml` first creates a temporary catalog file where all URIs in `catalog` property are referenced by `nextCatalog` elements.
  * Typically it looks like this:
    ```xml
    <catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
       <nextCatalog catalog="http://my-catalog-server.example.com/catalog.xml"/>
       <nextCatalog catalog="file:/C:/Program%20Files/Oxygen%20XML%20Editor%2022/frameworks/dita/catalog.xml"/>
       <nextCatalog catalog="file:/C:/Program%20Files/Oxygen%20XML%20Editor%2022/frameworks/dita/DITA-OT3.x/plugins/org.dita.base/catalog-dita.xml"/>
       ...
    ```
  * Relative URIs are resolved with URL of Ant `basedir` property.
  * All subsequent `<xslt>` and `<java>` tasks in `build.xml` use this temp catalog file.

**Comment by AlexJitianu** [comment]
Wow! That was quick! :) It sounds great! I will add an issue on our side to make sure we don't miss this feature when we update the built-in framework.

**Comment by cmarchand** [comment]
I use the same technic in xspec-maven-plugin when user specifies a catalog in plugin configuration. I create a catalog (to resolve xspec impl & schematron impl files) that references (using next-catalog) the user' one.

**Comment by AirQuick** [comment]
#980 implements this.
