### ISSUE TITLE
Scenario with x:expect/@ref linked to a big document generates files in current directory

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#93]
See https://github.com/xspec/xspec-maven-plugin1/issues/3 for full description.

```xml
<x:description 
  xmlns:x="http://www.jenitennison.com/xslt/xspec" 
  stylesheet="../../main/xsl/identity.xsl">
 <x:param name="debug" select="false()"/>
 <x:scenario label="Scenario comparing to a file" xml:base="../resources/">
    <x:context href="input.xml"/>
    <x:expect label="The expected file" select="/*" href="output.xml"/>
  </x:scenario>
</x:description>
```

Files are like this :
```
src/
├── main
│   └── xsl
│       └── identity.xsl
└── test
    ├── resources
    │   ├── input.xml
    │   └── output.xml
    └── xspec
        └── identity.xspec
```
If `input.xml` and `output.xml` are 1000+ elements, temp files are generated in **current directory**.

They should be generated in **the same directory than compiled XSL** and/or result file, to allow a simple clean.

I'll file a push request if I'm able to.

**Comment by cmarchand** [comment]
Created Pull Request : https://github.com/xspec/xspec/pull/94

**Comment by AirQuick** [comment]
Closing per [94](https://github.com/xspec/xspec/pull/94#issuecomment-286084106)
