### ISSUE TITLE
Automate Maven deployment

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#932]
Maven deployment depends on individual skills and has been a bit cumbersome. I'm thinking to automate it.

I searched GitHub Marketplace for a possible simple solution and [action-maven-publish](https://github.com/marketplace/actions/action-maven-publish) appears to satisfy the requirement described in [Wiki](https://github.com/xspec/xspec/wiki/Deploy-XSpec-artifact-to-Maven-Central). Its [source code](https://github.com/samuelmeuli/action-maven-publish/blob/master/index.js) looks simple and transparent.

@cmarchand 
What do you think?

**Comment by AirQuick** [comment]
@cmarchand 
Regarding this part of [Wiki](https://github.com/xspec/xspec/wiki/Deploy-XSpec-artifact-to-Maven-Central#instructions-for-first-time-setup):

> For example, use [https://oss.sonatype.org](https://oss.sonatype.org), create an account there to get a login and password.
> 
> First, declare the authentication in your `~/.m2/settings.xml` :
> 
> ```xml
> <settings>
>  <servers>
>   <server>
>    <id>ossrh</id>
>    <username>your_username</username>
>    <password>your_password</password>
>   </server>
>  </server>
> </settings>
> ```


Based on [this answer](https://community.sonatype.com/t/support-for-organizations-in-oss-sonatype-org/2164/2), I presume the following procedure would work:

1. I create an account at https://issues.sonatype.org/secure/Signup!default.jspa for this automation purposes only
1. You grant (or, perhaps, ask someone in sonatype.org to grant) the created account the permission to deploy to `io.xspec/xspec` 

What do you think?

**Comment by cirulls** [comment]
This would be a great feature to add in order to speed up the release cycle and make it less dependent on specific individual being available.

I did [the initial setup of passwords and GPG keys](https://github.com/xspec/xspec/wiki/Deploy-XSpec-artifact-to-Maven-Central#instructions-for-first-time-setup) on my machine in order to deploy previous releases and I think I could reuse the existing credentials using [GitHub secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) which are [supported by action-maven-publish](https://github.com/marketplace/actions/action-maven-publish#secrets). 

Something useful to bear this in mind when using GitHub secrets:

```
Secrets are environment variables that are encrypted and only exposed to selected actions. Anyone with collaborator access to this repository can use these secrets in a workflow.

Secrets are not passed to workflows that are triggered by a pull request from a fork. 
``` 

I would be happy to work on this following the above requirements and I have some time in May to dedicate to this issue. But I'm happy to leave it to @AirQuick and @cmarchand if you want to work on it - it's an interesting task!

**Comment by AirQuick** [comment]
Thanks @cirulls 
First things first... I don't know how `io.xspec` group at Sonatype has been operated till today.
Is [this](https://issues.sonatype.org/secure/ViewProfile.jspa?name=xspec-io) the `io.xspec`'s authoritative account at Sonatype JIRA? Do @cirulls and @cmarchand share that one account?

**Comment by AirQuick** [comment]
> Something useful to bear this in mind when using GitHub secrets:

And [this](https://stackoverflow.com/a/57917698/11853330). So we should use `samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709` while developing this automation. Once we confirm the developed automation works, we should fork the `samuelmeuli/action-maven-publish` repository under `https://github.com/xspec` and use `xspec/action-maven-publish@v1` thereafter.

**Comment by AirQuick** [comment]
@cirulls or @cmarchand 
Can you leave "Confirmed" comment to [this Jira ticket](https://issues.sonatype.org/browse/OSSRH-57324), so that I can work or back you up on any deployment issues even when both of you are inactive?

**Comment by cmarchand** [comment]
Yes, with @cirulls , we share the same account, the one you link above. I can send you account login / password if required by private mail. Send me your private mail address to one of my privates mail addresses defined in my account.
This Jira account is able to publish in groupId io.xspec, and descendants... I think my Jira accounts owns xspec-io account, or has sufficient privileges on, but I'm not sure.
For the GPG, you have to use your own certificate.

I will not work on automation tasks, I let you do this. You are much more advanced than I am.

So, "Confirmed".

**Comment by AirQuick** [comment]
Thanks for the clarification, @cmarchand 
Rather than sharing the credential, I would like to just add my account. Can you write "I confirm that this user should receive access" comment directly to this Jira ticket? https://issues.sonatype.org/browse/OSSRH-57324

**Comment by AirQuick** [comment]
Working on this branch: https://github.com/xspec/xspec/commits/auto-deploy-maven
Right now all the secrets are just `dummy`.

**Comment by AirQuick** [comment]
GPG secrets have been set and are working: https://github.com/xspec/xspec/runs/657082433#step:4:1451

Now we need to:
- have either @cmarchand or @cirulls write "Confirmed" in this Jira ticket: https://issues.sonatype.org/browse/OSSRH-57324
- settle the slightly new version scheme (#940)

**Comment by cmarchand** [comment]
Done.

**Comment by cirulls** [comment]
@AirQuick: it's looking good, you are much more advanced in this than me. I'll be happy to review the PR or configuration when it's ready.

**Comment by AirQuick** [comment]
Thanks @cirulls 
Fortunately someone is actively working on an official GitHub Action to [add GPG sign support](https://github.com/actions/setup-java/pull/59). So I will use `samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709` for the meantime and later migrate to the official GitHub Action.

I'm [setting up](https://issues.sonatype.org/browse/OSSRH-57441) a dedicated account for the automated deployment. Directly the account gets approved, I'll remove [`skipRemoteStaging`](https://github.com/xspec/xspec/blob/00e422ba62ee20283546b7fed5b9b44afc0d660b/pom.xml#L266-L267) to see if the artifacts are uploaded correctly to OSSRH. After that, I'll change [the target branch](https://github.com/xspec/xspec/blob/00e422ba62ee20283546b7fed5b9b44afc0d660b/.github/workflows/maven-deploy%20.yml#L6-L7) to `master` and reinstate [`autoReleaseAfterClose`](https://github.com/xspec/xspec/blob/00e422ba62ee20283546b7fed5b9b44afc0d660b/pom.xml#L262-L265). At this stage, I'll ask your review.

**Comment by AirQuick** [comment]
Now the automated deployment is working in the [`auto-deploy-maven`](https://github.com/xspec/xspec/tree/auto-deploy-maven) branch. Two `2.0-SNAPSHOT`s have been [deployed](https://oss.sonatype.org/content/repositories/snapshots/io/xspec/xspec/2.0-SNAPSHOT/) so far. The last action log is [here](https://github.com/xspec/xspec/runs/664224869#step:4:1493).

If we merge the `auto-deploy-maven` branch to the `master` branch, each commit to the master branch will deploy another `2.0-SNAPSHOT`. As far as I know, stale SNAPSHOTs will be [deleted automatically](https://issues.sonatype.org/browse/OSSRH-33316?focusedCommentId=422828).

@cmarchand and @cirulls,
Does it look fine so far?

**Comment by cirulls** [comment]
@AirQuick: I'll have a look later on today and give you some feedback.

**Comment by cirulls** [comment]
@AirQuick: it looks good to me. I checked the deployed snapshots on [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/io/xspec/xspec/2.0-SNAPSHOT/) and the action logs. Good stuff that stale snapshots are automatically deleted, that's going to be really useful when pushing to master. When GPG support will be available in GitHub Actions, I would be good to use that.

Do you want to merge it now to see how it works on master or prefer to wait for the new version scheme (#940)?

**Comment by AirQuick** [comment]
Opened #959
