### ISSUE TITLE
Java 9 modules support

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec#938]
Linked to https://github.com/xspec/xspec-maven-plugin-1/issues/46, jars that are published today do not respect Java 9 modules requirements.
We need to add :
 - a module-info.class
 - compliant package names
We need to define :
 - a module name
 - if we embed schematron implementation or if add a dependency

**Comment by cmarchand** [comment]
@AirQuick : may I contact you via private mail ?

**Comment by AirQuick** [comment]
For this Java 9 issue?

**Comment by cmarchand** [comment]
Yes.

**Comment by AirQuick** [comment]
You can reach me at github.sgn3ynjd8g@airquick.dev but keep in mind I'm not familiar with Java :)

**Comment by AirQuick** [comment]
@cmarchand 
Can we close this issue?

For the record, we now have these:

- (automatic) module name
  https://github.com/xspec/xspec/blob/838ff9efce04552e885cbe40dd6f65d155b8a262/pom.xml#L158
- XSLT stylesheets stored in in distinct directories
  https://github.com/xspec/xspec/blob/838ff9efce04552e885cbe40dd6f65d155b8a262/pom.xml#L81
  https://github.com/xspec/xspec/blob/838ff9efce04552e885cbe40dd6f65d155b8a262/pom.xml#L102-L112

**Comment by cmarchand** [comment]
I agree, we can close this one.
Thanks a lot

**Comment by AirQuick** [comment]
Thanks, @cmarchand 
Closing this.
