### ISSUE TITLE
Version scheme

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#940]
Right now, the Oxygen add-on has [strange version numbers](https://github.com/xspec/xspec/blob/fc3d36262a3415211ceca4f686e6f4dac8b1df22/oxygen-addon.xml#L15-L21). To get everything aligned, I'm thinking to change the version number scheme a little bit.

Suppose that the version number consists of three parts, `X.Y.Z`, as we have now. I'm thinking to use the `Z` part for pre-releasing:

- Whenever a commit is made into the `master` branch, deploy it to Sonatype as `X.Y-SNAPSHOT`.

  - Omit the `Z` part for simplicity. (See [this](https://stackoverflow.com/a/47065909/11853330) for Maven version comparison.)
  - Deployment is done by automation (#932).

- Whenever a notable change is made into the `master` branch, increment `Z` in `oxygen-addon.xml` and update the [add-on changelog](https://github.com/xspec/xspec/blob/fc3d36262a3415211ceca4f686e6f4dac8b1df22/editors/oxygen/add-on/description/latest.xhtml#L16-L52).

  - Do not push a _git_ tag. Do not publish a GitHub pre-release. Do not announce it.

- When we want to release a stable version, perform this procedure:
  1. Increment `Z` in `oxygen-addon.xml`.
  2. Notify the [XSpec discussion list](http://groups.google.com/group/xspec-users) of the upcoming `X.Y` release. (Ignore the `Z` part for simplicity.)
  3. After a while, increment `Z` and release it:
     1. Write `X.Y.Z` (without `-SNAPSHOT`) to `oxygen-addon.xml` and `pom.xml`.
     2. Push `vX.Y.Z` _git_ tag and publish `vX.Y.Z` GitHub release.
  4. Announce the availability of `vX.Y`. (Ignore the `Z` part for simplicity.)

@xspec/xspec
@cmarchand
What do you think?
Here's an example timeline:

|        | `master` branch commit timeline                               | Oxygen add-on release (oxygen-addon.xml) | Maven deployment (pom.xml)    | _git_ tag | GitHub Release | Release Announcement |
|--------|-------------------------------------------------------------|------------------------------------------|-------------------------------|---------|----------------|----------------------|
|        | Release (#890)                                              | `0.0.8`                                    | `1.6.0`                         | `v1.6.0`  | `v1.6.0`         | `v1.6.0`               |
|        | Bump Maven version (#902)                                   | (unreleased)                             | `2.0.0-SNAPSHOT` (not deployed) | (none)  | (none)         | (none)               |
|        | Bump Oxygen add-on version (#914)                           | `0.0.9`                                    | `2.0.0-SNAPSHOT` (not deployed) | (none)  | (none)         | (none)               |
| We're here >> | ...trivial or under-the-hood changes...                     | (unreleased)                             | `2.0.0-SNAPSHOT` (not deployed) | (none)  | (none)         | (none)               |
|        | Automate Maven deployment (#932)                            | (unreleased)                             | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | Notable feature or fix                                | (unreleased)                             | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Release__ to Oxygen add-on channel                            | `2.0.0`                                    | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | ...trivial or under-the-hood changes...                     | (unreleased)                             | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | Notable feature or fix                                | (unreleased)                             | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Release__ to Oxygen add-on channel                            | `2.0.1`                                    | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | ...trivial or under-the-hood changes...                     | (unreleased)                             | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | Notable feature or fix                                | (unreleased)                             | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Release__ to Oxygen add-on channel                            | `2.0.2`                                    | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | ...trivial or under-the-hood changes...                     | (unreleased)                             | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Release__ to Oxygen add-on channel (Stable Release Candidate) | `2.0.3`                                    | `2.0-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Stable Release__                                              | `2.0.4`                                    | `2.0.4`                         | `v2.0.4`  | `v2.0.4`         | `v2.0`                 |
|        | Bump Maven version to start the next development              | (unreleased)                             | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | ...trivial or under-the-hood changes...                     | (unreleased)                             | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | Notable feature or fix                                | (unreleased)                             | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Release__ to Oxygen add-on channel                            | `2.1.0`                                    | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | ...trivial or under-the-hood changes...                     | (unreleased)                             | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | Notable feature or fix                                | (unreleased)                             | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Release__ to Oxygen add-on channel                            | `2.1.1`                                    | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | ...trivial or under-the-hood changes...                     | (unreleased)                             | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Release__ to Oxygen add-on channel (Stable Release Candidate) | `2.1.2`                                    | `2.1-SNAPSHOT`                  | (none)  | (none)         | (none)               |
|        | __Stable Release__                                              | `2.1.3`                                    | `2.1.3`                         | `v2.1.3`  | `v2.1.3`         | `v2.1`                 |

**Comment by galtm** [comment]
I don't have a lot of experience with the tradeoffs of different release numbering practices, but aligning the numbers from the Oxygen perspective with the numbers in other areas seems like a step forward.

**Comment by AirQuick** [comment]
Thanks @galtm for the input.

The only drawback I see is that [the _git_ tags](https://github.com/xspec/xspec/tags) and [the GitHub releases](https://github.com/xspec/xspec/releases) will no longer ends with `.0`. That would be acceptable, I think.

Looking forward to hearing from @cirulls and, in particular, @cmarchand regarding the Maven version.

**Comment by cmarchand** [comment]
Hum... All releases preformed until now did not introduce non compatibility with previous releases, and except 1.0.0, were all minor releases, which is consistant with [semantic versionning](https://semver.org/). [Abstract is also available](https://rollout.io/blog/best-practices-when-versioning-a-release/).

Each release should be released as M.m.0, allowing to create patches to correct the initial release, if required - yes our work is perfect, but we still sometime embed foreign pull requests that may contain bugs. 😇

On the opposite, we could start to construct xspec project, where all delivered files are build. From this point of view, I'd put in [oxygen-addon.xml](https://github.com/xspec/xspec/blob/2855c30c17eee198e13b35649f06f24bc0fbf970/oxygen-addon.xml#L21) this value :
```
   <xt:version>${project.version}</xt:version>
```
At build time, `${project.version}` will be replaced by version value defined in `pom.xml`, and all versions will be aligned, even in SNAPSHOTs.

**Comment by AirQuick** [comment]
Thanks @cmarchand for the insight.

Each release will still start from M.m.0, although it will be published only to the Oxygen add-on.
If we have any critical bug after the stable release, we will still fix it and increment the patch version and release to all the channels (Oxygen add-on, Maven, _git_ tag and GitHub Release). So I think the version is still semantic.

Putting `<xt:version>${project.version}</xt:version>` is an idea. But it requires another automation or error-prone manual task. Just letting `pom.xml` stay at `2.0-SNAPSHOT`, `2.1-SNAPSHOT` and so on until the stable release seems light-weight and compatible with the Maven version semantic based on this discussion: https://stackoverflow.com/a/47065909/11853330

**Comment by cirulls** [comment]
> aligning the numbers from the Oxygen perspective with the numbers in other areas seems like a step forward.

I agree with @galtm, aligning the numbers in the XSpec version and add-on version will make everything more consistent and easier to track in case of bugs.

**Comment by AirQuick** [comment]
I opened #981 for releasing Oxygen v2.0.0 add-on.
