### ISSUE TITLE
Reorganize src/compiler/

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#948]
There are 7 `generate-*.*` files in [`src/compiler/`](https://github.com/xspec/xspec/tree/master/src/compiler). I think they are structured and named in a very confusing way.

- At a glance, there are 7 generators which you may think generate 7 different outputs. But actually, there are only 2 generators (XQuery and XSLT).
- `*-helper.*` and `*-utils.*`... Whenever I touch the code, I wonder what their roles are and how they are different.

Any thoughts?

**Comment by galtm** [comment]
I also find the file names confusing. I don't have strong opinions about anything I'm writing here, so feel free to adopt or adapt the parts you like and ignore the rest.

Possible recasting of file names/locations, with the aim of distinguishing among top-level compiler files, subordinate compiler files, and files used at the test runner stage:

- src/compiler/compile-xslt-tests.xsl (renamed from generate-xspec-tests.xsl; this is a Master file in Oxygen)
- src/compiler/compile-xslt-tests-helper.xsl (renamed from generate-tests-helper.xsl)
  -- Include comment at top of file indicating that Schematron testing uses this file, too?
  -- Maybe "helper" can be improved upon, as it is fairly generic. Keep the query helper file in sync.
  -- Alternate idea is xslt-compiler-helper.xsl
- src/compiler/compile-query-tests.xsl (renamed from generate-query-tests.xsl; this is a Master file in Oxygen)
- src/compiler/compile-query-tests-helper.xsl (renamed from generate-query-helper.xsl)
  -- Alternate idea is query-compiler-helper.xsl
- src/runner/test-runner-utils.xsl (renamed from generate-tests-utils.xsl; alternate idea is src/compiler/postcompilation-utils.xsl)
- src/runner/test-runner-utils.xquery (renamed from generate-query-utils.xql; alternate idea is src/compiler/postcompilation-utils.xquery)
- No change in src/common, src/reporter,  or src/schematron/*.xsl

Miscellaneous questions:
- Should src/schematron/iso-schematron move to something like lib/iso-schematron? My impression (correct me if wrong) is that this folder is the Schematron code as is, not original source code belonging to the XSpec project.
- Is there a reason for different file name extensions in generate-query-utils.xql versus xspec-utils.xquery? If not, can we standardize on one extension for the XQuery files that are in scope for this round of refactoring?
- Were you thinking about moving code among files, or only changing file names/locations?

**Comment by AirQuick** [comment]
> * Should src/schematron/iso-schematron move to something like lib/iso-schematron? My impression (correct me if wrong) is that this folder is the Schematron code as is, not original source code belonging to the XSpec project.

Opened #992.

> * Is there a reason for different file name extensions in generate-query-utils.xql versus xspec-utils.xquery? If not, can we standardize on one extension for the XQuery files that are in scope for this round of refactoring?

No reason except that Oxygen suggested `.xquery` in **File** - **New** menu when I was creating new XQuery files. Do you know which one is popular? I don't have any XQuery expertise nor any preference.
Shall we follow BaseX (`.xq` for main and `xqm` form lib) mentioned [here](https://stackoverflow.com/q/51637619)?

> * Were you thinking about moving code among files, or only changing file names/locations?

Including moving code among files. Particularly `test:*` items. They seem to be remnants of Jeni's older [framework](http://www.jenitennison.com/xslt/utilities/unit-testing/).

**Comment by AirQuick** [comment]
`compile-xslt-tests.xsl` and `compile-query-tests.xsl` as the master files look nice and clear. Thanks for the idea.
You may possibly have even better ideas for the other files if we consider moving code among files?

**Comment by galtm** [comment]
> even better ideas for the other files if we consider moving code among files?

Maybe after any near-term code relocation is further along, we can take a fresh look at how to characterize the different files and reconsider file naming.

**Comment by galtm** [comment]
> Shall we follow BaseX (`.xq` for main and `xqm` form lib) mentioned [here](https://stackoverflow.com/q/51637619)?

That sounds fine to me.

**Comment by AirQuick** [comment]
Opened #994 for XQuery file names.

**Comment by AirQuick** [comment]
Opened #1194 for `generate-*-utils.*`

**Comment by AirQuick** [comment]
Opened #1162 for `generate-*-tests.xsl`.

As for the rest of the files in `src/compiler/`, I'll open another pull request after completing #1162.

**Comment by AirQuick** [comment]
Opened #1205 for `generate-*-helper.xsl`.

**Comment by AirQuick** [comment]
#1223 completes this reorg. It ended up with more changes than I had initially thought and we had discussed here. It's by no means final. Please feel free to propose any other forms.

**Comment by galtm** [comment]
Thanks for making all these improvements! :) They will surely make it easier for everyone to maintain this code and maybe also make it easier for new contributors to join this project.
