### ISSUE TITLE
The 'debug' parameter in generate-test-utils.xsl shadows the compiled stylesheet

### ISSUE THREAD

**Issue by ndw** [xspec/xspec#985]
There's a declaration for a `debug` parameter in the `generate-test-utils.xsl` module. Unfortunately, that module is imported after the compiled stylesheet so it conflicts with any `debug` parameter declared by the imported stylesheet.

As far as I can tell, the parameter isn't actually used at the moment as all references to it are commented out. I propose that the declaration should be commented out as well. If the feature is implemented, the parameter should be more uniquely named (perhaps by putting it in the xspec namespace).

**Comment by AirQuick** [comment]
I happened to be planning to isolate unused lines. Fixed in #988.
